Adicionando pagina de documentação /docs
BrasilAPI/BrasilAPI pull request #101
Opened 2020-07-21 09:23 UTC by CarlosZiegler

Ola, aqui esta uma proposta para documentação com swagger, de acordo com a issue #14 .

- Criado pagina /docs
- Incluido arquivo Json da documentacao, na pasta /docs
- Incluido na root um arquivo de css para o estilo da pagina
- Criado arquivo /pages/_app.js para importar folha de estilo para pagina docs
- Add no package.json swagger-ui-react

Segue alguns screenshots da pagina docs:

![Screenshot 2020-07-21 at 11 17 36](https://user-images.githubusercontent.com/38855507/88036535-f876bd00-cb43-11ea-884d-12e8394a547d.png)
![Screenshot 2020-07-21 at 11 17 36](https://user-images.githubusercontent.com/38855507/88036407-cd8c6900-cb43-11ea-81c8-d8bde6ac0887.png)
![Screenshot 2020-07-21 at 11 17 20](https://user-images.githubusercontent.com/38855507/88036415-d0875980-cb43-11ea-9928-a826560f3e78.png)

OBS: Rota DD esta retornando erro.

2020-07-21 09:46 UTC, CarlosZiegler commented
Rota DDD nao esta funcionando corretamente, acredito que por isso nao esta fazendo o deploy.

2020-07-21 12:56 UTC, wesleyburlani commented
Olá Carlos, estava vendo o projeto aqui e, apesar do arquivo `[ddd].js` ter um comentário especificando um exemplo de rota como sendo `/api/cities/v1/ddd/21` , os testes do projeto apontam para a rota `/api/ddd/v1/{ddd}`, que seria a rota utilizada. De qualquer modo, a rota de DDD não está funcionando mesmo, usando a rota `/api/ddd/v1/{ddd}` o retorno é "502: BAD_GATEWAY, NO_RESPONSE_FROM_FUNCTION".

2020-07-21 13:04 UTC, CarlosZiegler commented
Ola Wesley, vou modificar meu Pr aqui, valeu o toque .... E sim nao ta rodando mesmo... estranho ...

2020-07-29 18:06 UTC, lucianopf commented
Mestre @CarlosZiegler primeiamente obrigado pelo PR! :rocket: 

Tenho 2 pontos de atenção aqui:
1 - Vc ta adicionando um arquivo `yarn.lock` sendo que na real a gnt usa `package-lock`, eu removeria o yarn do PR e manteria apenas o package-lock :eyes: 

2 - A build ta dando erro , eu até mandei rebuildar pra testar mas continua dando problema :cry: 

```
15:03:49.432 | > Build error occurred
-- | --
15:03:49.434 | ReferenceError: window is not defined
15:03:49.434 | at Object.<anonymous> (/vercel/1bf7104b/node_modules/swagger-ui-react/swagger-ui.js:1:208)
15:03:49.434 | at Module._compile (internal/modules/cjs/loader.js:1156:30)
15:03:49.434 | at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
15:03:49.434 | at Module.load (internal/modules/cjs/loader.js:1000:32)
15:03:49.434 | at Function.Module._load (internal/modules/cjs/loader.js:899:14)
15:03:49.434 | at Module.require (internal/modules/cjs/loader.js:1042:19)
15:03:49.434 | at require (internal/modules/cjs/helpers.js:77:18)
15:03:49.434 | at Object.<anonymous> (/vercel/1bf7104b/node_modules/swagger-ui-react/index.js:37:41)
15:03:49.434 | at Module._compile (internal/modules/cjs/loader.js:1156:30)
15:03:49.434 | at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
15:03:49.457 | error Command failed with exit code 1.
15:03:49.458 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
15:03:49.468 | Error: Command "yarn run build" exited with 1
15:03:51.617 | Done with "package.json"
```

2020-07-30 09:20 UTC, otaciliolacerda commented
Oi @CarlosZiegler, parabéns pela iniciativa. Gostaria de elaborar um pouco mais no ponto 2 dado pelo @lucianopf:

Isso parece ser um problema com SSR (server side rendering). Pela mensagem de erro parece que há uma tentativa de renderizar o component `<SwaggerUI />` no servidor (por isso o `window not defined`). Apesar de não ter uma solução definitiva há uma discussão em andamento em [swagger-ui/issues/6136](https://github.com/swagger-api/swagger-ui/issues/6136)

2020-07-30 15:30 UTC, RodriAndreotti commented
Senhores, permitem que eu sugira uma alternativa ao SwaggerUI?
Sei que é a ferramenta mais usada hoje para documentação, mas eu gostei bastante de um projeto OpenSource de documentação chamado ReDoc, no meu ver ele tem até uma estética um pouco mais refinada que o Swagger UI.

Talvez, se a lib estiver dando dor de cabeça para publicar, possa ser uma alternativa.

Seguem links:
[Repositório](https://github.com/Redocly/redoc)
[Preview](https://redocly.github.io/redoc/)

2020-08-03 18:21 UTC, CarlosZiegler commented
Opa, eu estava até o pescoço semana passada, essa semana vou dar uma olhadinha, mas bora implementar isso aí @RodriAndreotti que quero aprender a usar também hahah..

2020-08-03 21:12 UTC, RodriAndreotti commented
> 
> 
> Opa, eu estava até o pescoço semana passada, essa semana vou dar uma olhadinha, mas bora implementar isso aí @RodriAndreotti que quero aprender a usar também hahah..

Cara, se eu te falar que o negócio é fácil demais para implementar vc acredita?
É só baixar o repositório mesmo, e jogar o arquivo.json exportado do swagger-editor apontando para ele.
Se quiser tentar, para eu não atravessar seu PR, pode fazer ai, e se precisar de ajuda é só dar um toque.

Mas eu implementei nesse link aqui: https://neoedu.com.br/api-doc, caso queira dar uma olhada.

2020-08-04 09:19 UTC, CarlosZiegler commented
@RodriAndreotti Sensacional esse REDOC, muito mais simples de implementar. Eu tomei a liberdade de pegar seu código do json e salvar aqui como exemplo para futuras implementações, pode ser? Estava dando um conflito de versão do lodash, eu arrumei no meu repo e mandei novamente. @lucianopf também exclui o arquivo yarn.lock, passou batido mesmo, bom que nas próximas eu me atento a isso. @otaciliolacerda Da uma olhada no que o @RodriAndreotti comentou, a implementação fica mais simples, pelo menos eu achei :) . @RodriAndreotti da uma olhada no meu PR e se tiver algo a arrumar, tome frente ai !!!!

2020-08-04 13:11 UTC, RodriAndreotti commented
> 
> 
> @RodriAndreotti Sensacional esse REDOC, muito mais simples de implementar. Eu tomei a liberdade de pegar seu código do json e salvar aqui como exemplo para futuras implementações, pode ser? Estava dando um conflito de versão do lodash, eu arrumei no meu repo e mandei novamente. @lucianopf também exclui o arquivo yarn.lock, passou batido mesmo, bom que nas próximas eu me atento a isso. @otaciliolacerda Da uma olhada no que o @RodriAndreotti comentou, a implementação fica mais simples, pelo menos eu achei :) . @RodriAndreotti da uma olhada no meu PR e se tiver algo a arrumar, tome frente ai !!!!

Cara, de minha parte, não há problema nenhum em usar o meu json, só peço para não publicar ele, pois não é de uma API pública, é do sistema da empresa que trabalho, porém o próprio site do redoc tem um json tbm para uso, caso queira disponibilizar publicamente ;-)

Com relação ao PR, vou dar uma olhada mais tarde, eu queria pegar algo para desenvolver aqui tbm, mas estou tão corrido por esses dias que é capaz de eu pegar algo e terminarem antes de mim... kkk

2020-08-04 13:49 UTC, RodriAndreotti commented on pages/api-doc/index.js
> +export default function index2() {
Neste caso não seria melhor usar só index() para o nome da função?

2020-08-04 14:23 UTC, CarlosZiegler commented on pages/api-doc/index.js
> +export default function index2() {
Sim @RodriAndreotti, arrumei ja, e sobre o arquivo, nao vou publicar nao, seria apenas para consulta mesmo, achei bem interessante e completo para estudos.

2020-08-04 14:47 UTC, RodriAndreotti commented on pages/api-doc/index.js
> +export default function index2() {
Pode usar sim cara, sem problema, incluso, para gerar esse json eu usei um serviço chamado apimatic (https://www.apimatic.io/), na versão grátis ele permite modelar um API só, mas é suficiente às vezes. Ele permite importar modelos de json, de curl etc, e gera os endpoints prontos para vc só ajustar a documentação, depois de pronto é só exportar o json no formato openapi e usar no redoc (eles até tem um portal de documentação também, mas gostei mais do redoc, justamente por ser hospedado em nosso servidor)

2020-08-04 18:50 UTC, CarlosZiegler commented on pages/api-doc/index.js
> +export default function index2() {
Que massa, muito aprendizado nesse PR, valew mesmo as dicas e sinta-se a vontade de corrigir o PR :)

2020-08-04 19:19 UTC, RodriAndreotti commented on pages/api-doc/index.js
> +export default function index2() {
Opa... bom que deu para aprender alguma coisa, qualquer coisa é só gritar ;-)

2020-08-04 20:26 UTC, CarlosZiegler commented
Adicionando screenshots:
![Screenshot 2020-08-04 at 22 25 44](https://user-images.githubusercontent.com/38855507/89341354-76d57200-d6a1-11ea-97af-f5d0e3f956d5.png)
![Screenshot 2020-08-04 at 22 25 38](https://user-images.githubusercontent.com/38855507/89341359-789f3580-d6a1-11ea-8665-396bcbb9183f.png)
![Screenshot 2020-08-04 at 22 25 24](https://user-images.githubusercontent.com/38855507/89341360-7937cc00-d6a1-11ea-93dd-dc9e6533f4d0.png)

2020-08-05 07:23 UTC, otaciliolacerda commented on package.json
> +    "redoc": "^2.0.0-rc.35",
É ok utilizar versão alpha?

2020-08-05 07:24 UTC, otaciliolacerda commented on pages/api-doc/index.js
> +import Documentation from './doc.json'
Eu sugiro utilizar YAML para tornar mais legível.

2020-08-05 07:25 UTC, otaciliolacerda commented on pages/api-doc/doc.json
> +    "version": "1.0.5",
Não seria `1.0.0` (versão inicial)?

2020-08-05 07:26 UTC, otaciliolacerda commented on pages/api-doc/doc.json
> +  "swagger": "2.0",
Poderíamos utilizar a OpenAPI v3

2020-08-05 07:54 UTC, otaciliolacerda commented
Peguei o JSON desse PR e converti para utilizar v3 e YAML: [Exemplo](https://gist.github.com/otaciliolacerda/ef8c545ceac7b4c3b6585ecc53218156)

Também tive que modificar alguns campos pois não passavam na validação do swagger editor. Talvez seja a diferença da v2 para v3.

Para ter algo visual, basta copiar & colar o conteúdo do yaml no [swagger editor](https://editor.swagger.io/)

2020-08-05 13:31 UTC, RodriAndreotti commented on package.json
> +    "redoc": "^2.0.0-rc.35",
Cara, para ser sincero, eu acho que o dev não deve ter alterado os releases tags do repositório:
https://github.com/Redocly/redoc/tags
Pois todos estão como RC, mas com a experiência que tive, ele funciona sem problemas.

2020-08-05 13:34 UTC, RodriAndreotti commented on pages/api-doc/doc.json
> +  "swagger": "2.0",
Concordo, se existe uma especificação um pouco mais recente, é sempre bom trabalhar para manter a compatibilidade por mais tempo.

2020-08-05 13:35 UTC, RodriAndreotti commented on pages/api-doc/index.js
> +import Documentation from './doc.json'
Por incrível que pareça eu acho o json mais legível, mas é só questão de opinião mesmo :-p

2020-08-05 13:38 UTC, otaciliolacerda commented on package.json
> +    "redoc": "^2.0.0-rc.35",
Vi que a versão anterior não suporta OpenAPI v3.

2020-08-05 13:40 UTC, otaciliolacerda commented on pages/api-doc/index.js
> +import Documentation from './doc.json'
O exemplo que coloquei usando `yaml` e OpenAPI v3 pode ser facilmente convertido para `json`. O exemplo corrige algumas coisas do `json` que peguei daqui.

2020-08-05 13:44 UTC, RodriAndreotti commented on pages/api-doc/index.js
> +import Documentation from './doc.json'
Na realidade para o front não tem tanta diferença, acho que o redoc lê os dois sem problemas, vai da preferência de cada um mesmo, aliás, até o próprio swagger editor já consegue exportar como json, se quiser (incluso, convertendo de swagger 2 para openapi tbm)
Mas essas conversões automáticas nem sempre ficam 100%, então é legal dar uma revisada para garantir que está tudo certo.

2020-08-05 13:47 UTC, RodriAndreotti commented on package.json
> +    "redoc": "^2.0.0-rc.35",
Eu estava fuçando o changelog dele aqui, e parece que o suporte básico rola desde 2017 já:
https://github.com/Redocly/redoc/blob/master/CHANGELOG.md#200-alpha1-2017-11-23
Não sei se faltou ele complementar algo nas especificações, mas, teoricamente teria suporte.

2020-08-05 13:59 UTC, CarlosZiegler commented on pages/api-doc/index.js
> +import Documentation from './doc.json'
Ola pessoal, então queria saber uma coisa, no modelo que usei eu pego o Json e aponto no spec do componente redoc, com o Yaml seria a mesma coisa?

2020-08-05 14:02 UTC, CarlosZiegler commented on pages/api-doc/doc.json
> +    "version": "1.0.5",
Ja corrigi, valeu mesmo!!!

2020-08-05 14:04 UTC, RodriAndreotti commented on pages/api-doc/index.js
> +import Documentation from './doc.json'
Sim... a mesma coisa, pelo que sei ele lê os dois formatos, se vc pegar uma url de um yaml e jogar no demo online dele, é possível ver o funcionamento:
https://redocly.github.io/redoc/

2020-08-05 14:10 UTC, CarlosZiegler commented
@otaciliolacerda , converti seu documento Yaml para Json e coloquei no PR, pois achei mais simples de implementar. Da uma olhada se esta tudo OK. E obrigado pela ajuda, com a ajuda de vocês ficou muito bom e o melhor eu aprendi muito. Realmente muito obrigado a vocês dois. Se tiver algo errado por favor me corrijam, tomem frente no PR, melhor que contribuir é aprender! hahah

2020-08-05 14:18 UTC, CarlosZiegler commented on pages/api-doc/doc.json
> +  "swagger": "2.0",
Ja alterei também, de acordo com o Yaml do @otacilio eu gerei um json, e atualizei o doc.json.

2020-08-10 20:31 UTC, lucianopf commented
Dúvida, a ideia é a rota ser `/docs` ou `/api-doc` mesmo? 🤔 

No momento um deploy testavel ta aqui https://brasilapi-ls5vpzy2k.vercel.app/api-doc#tag/CEP! ^^

2020-08-10 22:56 UTC, RodriAndreotti commented
> 
> 
> Dúvida, a ideia é a rota ser `/docs` ou `/api-doc` mesmo? 🤔
> 
> No momento um deploy testavel ta aqui https://brasilapi-ls5vpzy2k.vercel.app/api-doc#tag/CEP! ^^

Bom, não sou o proprietário do PR, mas me parece melhor só /docs
Ele deve ter usado a mesma rota que usei no exemplo que mandei a ele, mas meu cenário era um pouco diferente... rs

2020-08-11 04:46 UTC, CarlosZiegler commented
Bom dia, @lucianopf ja fiz a alteração para /docs. Realmente estava me baseando no que o @RodriAndreotti falou.

2020-10-20 17:37 UTC, williamtorres1 approved these changes

2020-11-01 20:06 UTC, lucianopf approved these changes

2020-11-01 20:06 UTC, lucianopf commented on package.json
> +    "core-js": "^3.6.5",
Um ponto que não é um block pra esse PR é tentar deixar as versões fixadas no `package.json` pra evitar bumps considerados minors de dependências externas que podem quebrar o comportamento que esperamos.

2020-12-10 16:25 UTC, murilohns requested changes
Cara ficou muito bom seu PR, o único ponto de atenção é que a rota de `DDD` está errada, mesmo que essa rota não esteja funcionando =[

2020-12-10 16:25 UTC, murilohns commented on pages/docs/doc.json
> +    "/cities/v1/ddd/{ddd}": {
Apesar dessa rota não estar funcionando, o endpoint correto é `ddd/v1/{ddd}`

2020-12-10 16:45 UTC, murilohns approved these changes

2020-12-10 17:41 UTC, closed without merging

2020-12-10 17:53 UTC, murilohns commented
Fui ajeitar a branch pro merge e acabei fechando o PR e tirando os commits sem querer, mas não precisa se desesperar não @CarlosZiegler, eu já to desesperado por nós dois!

Jaja corrijo isso :D

2020-12-10 19:26 UTC, CarlosZiegler commented on pages/docs/doc.json
> +    "/cities/v1/ddd/{ddd}": {
Ola @murilohns . Eu ja resolvi isso pelo git mesmo, depois confere se atualizou ai ....

2020-12-10 19:28 UTC, CarlosZiegler commented
Mas nem eh sexta feira ainda... hahaha