Inclusão de ícone, e ajuste do título da página
BrasilAPI/BrasilAPI pull request #103
Opened 2020-07-27 00:44 UTC by thiagofrugis

Opa, comecei a dar uma olhada no projeto recentemente.
Gostei da ideia de transformar bastante coisa em API, e como estou aprendendo algumas coisas novas, quero tentar ajudar nesse projeto.

Realizei a inclusão de um ícone e renomeei o título da página por enquanto.

2020-07-29 18:08 UTC, lucianopf commented on components/Layout.js
> +export default Layout;
Sugestão:

Que tal a gnt quebrar essa linha aqui pro Github não ficar gritando com:
![github](https://user-images.githubusercontent.com/8251208/88836664-6ad34700-d1ad-11ea-9528-8512e91db733.png)

2020-07-29 18:09 UTC, lucianopf commented
Boa tarde mestre @thiagofrugis , curti a ideia e o PR hein! :rocket: :clap: 

Fiquei com uma dúvida, será que não vale usar a logo proposta pelo @filipedeschamps no favicon tbm? :thinking:

2020-07-30 16:28 UTC, thiagofrugis commented
Opa,
Claro, acho legal a ideia de colocar o ícone certo.

Só coloquei aquele por estar analisando ainda o projeto.

Mas podemos mudar sim.

Obrigado pela sugestão.
Grade abraço

On Wed, 29 Jul 2020 at 15:10, Luciano Pellacani Franca <
notifications@github.com> wrote:

> Boa tarde mestre @thiagofrugis <https://github.com/thiagofrugis> , curti
> a ideia e o PR hein! 🚀 👏
>
> Fiquei com uma dúvida, será que não vale usar a logo proposta pelo
> @filipedeschamps <https://github.com/filipedeschamps> no favicon tbm? 🤔
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/filipedeschamps/BrasilAPI/pull/103#issuecomment-665818127>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJSO7LHFSYMDNYPOE45RRNLR6BQYJANCNFSM4PIH3PFQ>
> .
>

2020-11-13 00:30 UTC, Nikolassantos requested changes
Achei as alterações ótimas , só não sei se esse icone na pagina sera a melhor escolha, talvez algo vetorizado seria melhor.

2020-11-13 00:30 UTC, Nikolassantos commented on components/Layout.js
> +export default Layout;
Qual o problema dessa linha ? desculpa sou iniciante

2020-11-13 01:20 UTC, RodriAndreotti commented on components/Layout.js
> +export default Layout;
Se abrir o arquivo no Github (clicar no título do arquivo) você consegue ver o ícone que o @lucianopf comentou, o Github reclama em alguns arquivos quando o fim do arquivo não tem um "Enter" depois do fim do código.

2020-11-17 03:17 UTC, BrunoS3D commented on components/Layout.js
> +export default Layout;
@Nikolassantos 

![image](https://user-images.githubusercontent.com/21183964/99342094-dd098d80-2869-11eb-98c0-b4cceed9bc7c.png)

Isso é apenas por convensão e boas práticas entre os devs, serve para que o `diff` seja mais legível o possível.

2021-01-11 20:37 UTC, murilohns commented
@thiagofrugis muito obrigado pela contribuição!

Tenho alguns pontos que gostaria de discutir aqui:

### FavIcon

Curti muito a ideia, à título de comparação o antes e depois é esse: 
![image](https://user-images.githubusercontent.com/18074134/104234690-903dcf80-5432-11eb-8389-8df6556cf5e8.png)

O que eu não achei legal foi a imagem escolhida, mas não por ser a bandeira do Brasil, e sim por que o projeto usa em todos os lugares uma imagem parecida com essa:

![brasilapi-logo-small](https://user-images.githubusercontent.com/18074134/104234806-c11e0480-5432-11eb-8513-b51903478a3d.png). O que acha de deixar o FavIcon nesse mesmo padrão?

### Como os componentes foram montados

O que costumamos separar são os componentes menores né? Mas o que você separou foi o componente principal (nomeando ele como `Layout`) e deixou as outras partes como antes, será que essa abordagem é a melhor?

Olhando o `pages/index`, com as alterações que você fez, eu consigo ver 3 componentes: `Header`, `Logo` e `PoweredBy` (Ou algo assim), e talvez essa separação fizesse mais sentido.

Porém, além disso eu preciso te perguntar: Valeria a pena separar em componentes dessa forma? Eles não são reutilizados em nenhum lugar 🤔 

Nota: Não tenho muita experiência com React, é minha visão mesmo

2021-02-19 14:26 UTC, murilohns commented
O PR #251 resolveu esse problema.

Vou fechando esse PR por conta disso =]

2021-02-19 14:26 UTC, closed without merging