fix: update repository URL
BrasilAPI/BrasilAPI pull request #125
Opened 2020-11-16 15:25 UTC by josepholiveira

This PR changes the links for the repository URL from [filipedeschamps/brasilAPI)(http://github.com/filipedeschamps/brasilAPI) to link to the organization [brazilAPI/brazilAPI](https://github.com/BrasilAPI/BrasilAPI) on everyplace it's being linked.

2020-11-16 16:07 UTC, AugustoResende approved these changes

2020-11-16 19:58 UTC, lucasbastianik approved these changes

2020-11-17 01:45 UTC, brunolemos approved these changes

2020-11-17 03:05 UTC, BrunoS3D requested changes

2020-11-17 03:05 UTC, BrunoS3D commented on package.json
>      "url": "https://github.com/filipedeschamps/BrasilAPI/issues"
```suggestion
    "url": "https://github.com/BrasilAPI/BrasilAPI/issues"
```

2020-11-18 16:23 UTC, BrunoS3D approved these changes

2020-11-18 16:24 UTC, merged