🖼  contributors embed image using hidden feature of github
BrasilAPI/BrasilAPI pull request #134
Opened 2020-11-17 11:59 UTC by lucasbastianik

Atualizei as imagens dos Contribuidores que antes eram apontadas diretamente para o link específico da CDN do Github para uma Hidden Feature do Github onde adicionando o `.png` ao fim do link do usuário e utilizando a querystring `?size` para dimensionar o tamanho do avatar que é embedado no README.

Com isso:
- Facilita a edição dos contribuidores no README pois os links dos avatares costumam ser extensos
- Garantimos que o Github busque a CDN mais próxima de quem tiver acessando
- Conseguimos requisitar a imagem do tamanho correto e não precisamos redimensionar ela dentro do README

Pensei aqui se poderia haver algum efeito colateral futuro e a única coisa que enxergo seria se o usuário alterar o nome dele no Github, mas até aí, passa a ser um ponto positivo pois a foto dele irá parar de aparecer e terá que ser feito a alteração tanto da imagem quanto dos links (que seria inevitável).

2020-11-17 17:20 UTC, r3nanp approved these changes

2021-01-11 16:43 UTC, lucianopf approved these changes
😱 Caraaaca muito melhor assim! 🚀 

Só fazer um rebase com a master e acho que podemos mergear

Se precisar de ajuda com o rebase é só falar que eu tento puxar aqui do meu lado e te mostro os passos 😬

2021-01-11 19:14 UTC, murilohns requested changes
@lucasbastianik Esse PR tá tirando os 3 últimos contribuidores:

@CarlosZiegler, @otaciliolacerda e @RodriAndreotti

Consegue adicionar de novo?

2021-01-11 19:54 UTC, RodriAndreotti commented
> 
> 
> @lucasbastianik Esse PR tá tirando os 3 últimos contribuidores:
> 
> @CarlosZiegler, @otaciliolacerda e @RodriAndreotti
> 
> Consegue adicionar de novo?

Estou me sentindo excluído 😭😭😭😭😭

2021-01-16 01:05 UTC, lucasbastianik commented
> 😱 Caraaaca muito melhor assim! 🚀
> 
> Só fazer um rebase com a master e acho que podemos mergear
> 
> Se precisar de ajuda com o rebase é só falar que eu tento puxar aqui do meu lado e te mostro os passos 😬

Me dá uma luz como fazer, please 🙏

2021-01-16 01:06 UTC, lucasbastianik commented
> @lucasbastianik Esse PR tá tirando os 3 últimos contribuidores:
> 
> @CarlosZiegler, @otaciliolacerda e @RodriAndreotti
> 
> Consegue adicionar de novo?

Pode deixar que vou ajeitar aqui e adiciona vocês tbm senhores 😉

2021-01-16 01:21 UTC, lucasbastianik commented
@lucianopf rapaz, não é que eu consegui?! Hahahahaha 

+1 aprendizado no dia de hoje aqui hein 🧠✨

Acho que agora podemos mergeá-lo.

2021-01-18 16:43 UTC, lucianopf commented
Uhuuul!! 🚀 @lucasbastianik 

Que notícia massa mano! 😄
O Git é uma loucura e aprender essas técnicas avançadas te salvam muito trabalho! 😬 👏

2021-01-18 16:43 UTC, murilohns approved these changes

2021-01-18 16:43 UTC, merged