feat: Adicionado integração com os correios para rastreamento de objetos
BrasilAPI/BrasilAPI pull request #151
Opened 2020-11-20 18:26 UTC by igorjunior

## Rastreamento de objetos integrado aos serviços dos Correios.

### Rotas adicionadas

```
/api/rastreio/v1/[codigo] => Lista os eventos do rastreamento do objeto
```

2021-01-18 20:56 UTC, Caaddss commented
Marcando a issue relacionada
#56

2021-02-17 17:49 UTC, pedrosancao commented
Olá, peço licença para deixar algumas considerações.

Gostei da sua implementação, assim como a biblioteca [talesluna/RastroJS](https://github.com/talesluna/RastroJS), seu código consulta no site dos Correios e faz _parse_ do HTML, é essencialmente um _crawler_.

Há um risco de parar de funcionar caso o layout da página seja alterado (faz anos que não muda, mas existe a possibilidade), por causa disso sugiro mudar a versão de "v1" para "beta".

Para uma versão estável podemos pensar em serviços alternativos de _fallback_ como por exemplo o [webservice SOAP dos Correios](https://www.correios.com.br/enviar-e-receber/precisa-de-ajuda/manual_rastreamentoobjetosws.pdf) (apesar de precisar de credenciais)

---

Tendo decidido sobre como lidar com esse risco, acho que para aprovar esse PR as seguintes tarefas precisam ser realizadas:

- [ ] Revisar pacotes importados (me parece que foram adicionados vários sem necessidade)
- [ ] Organizar commits com rebase ou squash (as mensagens não são muito significativas)
- [ ] Merge do branch main para resolver os conflitos
- [ ] Criar casos de teste (vi no histórico que foram apagados, por que?)
- [ ] Criar documentação do endpoint no README e página `/docs`

---

Você criou o pacote rastreio-promise e importou aqui, pessoalmente tenho minhas ressalvas em relação a manutenção desse código em uma biblioteca externa e preferiria se fosse utilizado um serviço na pasta `services` (uma coisa não elimina a outra) - é uma estrutura muito parecida com o "CEP promise", mas essa está na mesma dentro da organização BrasilAPI.

2021-02-17 17:54 UTC, pedrosancao requested changes
Vejo os seguintes pontos a serem observados

- [ ] Revisar pacotes importados (me parece que foram adicionados vários sem necessidade)
- [ ] Organizar commits com rebase ou squash (as mensagens não são muito significativas)
- [ ] Merge do branch main para resolver os conflitos
- [ ] Criar casos de teste (vi no histórico que foram apagados, por que?)
- [ ] Criar documentação do endpoint no README e página `/docs`

2021-02-17 17:54 UTC, pedrosancao commented on package.json
> +    "styled-components": "^5.1.1"
todos esses pacotes são necessários?

2021-02-17 17:54 UTC, pedrosancao commented on pages/api/rastreio/v1/[codigo].js
> +  });
sugiro que seja removido

2021-07-09 01:22 UTC, feliperbroering commented
morreu a ideia?

2021-12-21 18:48 UTC, Kalgros20 commented
> morreu a ideia?

acho que surgiu essa fita aqui no lugar: https://proxyapp.correios.com.br/v1/sro-rastro/ , é do app do correios e aparentemente funciona bem. Procede? Se for o caso podemos matar esse PR e a Issue lá no Repo.

2021-12-21 18:49 UTC, lucianopf commented
> > morreu a ideia?
> 
> acho que surgiu essa fita aqui no lugar: https://proxyapp.correios.com.br/v1/sro-rastro/ , é do app do correios e aparentemente funciona bem. Procede? Se for o caso podemos matar esse PR e a Issue lá no Repo.

Opa, então seria parar de usar a lib e usar direto esse serviço, né?

2021-12-21 18:59 UTC, Kalgros20 commented
> > > morreu a ideia?
> > 
> > 
> > acho que surgiu essa fita aqui no lugar: https://proxyapp.correios.com.br/v1/sro-rastro/ , é do app do correios e aparentemente funciona bem. Procede? Se for o caso podemos matar esse PR e a Issue lá no Repo.
> 
> Opa, então seria parar de usar a lib e usar direto esse serviço, né?

Acho que bem por aí mesmo. Gostaria de mais opiniões sobre a estabilidade desse endpoint... Não sou muito familiar com ele não. 👀

2023-04-20 18:58 UTC, closed without merging