Feature: API para consulta de carros por placa
BrasilAPI/BrasilAPI pull request #163
Opened 2020-12-01 01:35 UTC by fabmont

Este PR implementa consulta de carros por placa com auxílio da lib open-source [sinesp-api](https://github.com/Sorackb/sinesp-api). A issue que este PR está linkado é #137.

Para testar o endpoint, basta navegar até a rota `/api/car/v1/:placaDoVeiculo`.

Como discutido na issue, criei algumas funções utils para lidar (mesmo que brevemente) com a normalização dos dados da API. Escrevi essas utils no proprio arquivo do endpoint, pois não sabia se existe algum padrão para lidar com funções de tratamento em outro lugar. Com isso, como o Next usa ES6+ e o Jest não, ficou dificil passá-las nos testes, então deixei o codigo do teste dessas funções comentados . Qualquer feedback com relação a isso é bem-vindo.

![](https://media3.giphy.com/media/mIMsLsQTJzAn6/giphy.gif)

2020-12-02 12:12 UTC, schneiderl submitted a review, later dismissed
Oi @fabmont
Deixei só um pequeno comentário na tua PR.

Obrigado pela PR, mestre. 👍

2020-12-02 12:12 UTC, schneiderl commented on tests/car-v1.test.js
> +// describe('/car/v1 (Utils - formatBrandModel)', () => {
Nós precisamos manter esses testes comentados? 
Até onde eu conheço a API (quase nada), os testes que estão descomentados já parecem cobrir as possíveis respostas da API.

2020-12-02 15:08 UTC, fabmont commented on tests/car-v1.test.js
> +// describe('/car/v1 (Utils - formatBrandModel)', () => {
Fala Lucas! Obrigado pela sugestão, o que ocorre é o seguinte:
Existem duas funções helpers que ajudam a tratar algumas coisas para retornar uma resposta mais redonda e bem tratada.
Essas duas funções estão no proprio arquivo da rota do endpoint, que são escritas em ES6+, quando importamos essas funções no arquivo do Jest, que é escrito em commonJS, ocorre alguns erros.
Se você souber o que podemos fazer com relação a isso, seria ótimo.
Os testes comentados nesse caso se referem a essas duas funções.

2020-12-03 18:58 UTC, jeffersonsimaogoncalves commented
@fabmont esta api de consulta se encontra desatualizada.

Verifiquei qual serviço que está sendo utilizado e encontrei a mensagem que a versão da api de consulta se encontra parcialmente desativada.

https://github.com/100n0m3/API-Carros

a dependência **sinesp-api** utiliza nas requisições o endpoint da API-Carros.

2020-12-04 15:30 UTC, fabmont commented
> @fabmont esta api de consulta se encontra desatualizada.
> 
> Verifiquei qual serviço que está sendo utilizado e encontrei a mensagem que a versão da api de consulta se encontra parcialmente desativada.
> 
> https://github.com/100n0m3/API-Carros
> 
> a dependência **sinesp-api** utiliza nas requisições o endpoint da API-Carros.

Tem razão @jeffersonsimaogoncalves, uma outra alternativa seria usar o endpoint oficial que o app do sinesp usa.
Porém tem request limit e precisamos também verificar a legalidade de usá-la, uma vez que não é pública.

2020-12-04 16:17 UTC, jeffersonsimaogoncalves commented
> > @fabmont esta api de consulta se encontra desatualizada.
> > Verifiquei qual serviço que está sendo utilizado e encontrei a mensagem que a versão da api de consulta se encontra parcialmente desativada.
> > https://github.com/100n0m3/API-Carros
> > a dependência **sinesp-api** utiliza nas requisições o endpoint da API-Carros.
> 
> Tem razão @jeffersonsimaogoncalves, uma outra alternativa seria usar o endpoint oficial que o app do sinesp usa.
> Porém tem request limit e precisamos também verificar a legalidade de usá-la, uma vez que não é pública.

Então fiz alguma pesquisa e não encontrei nenhum endpoint atualizado, o que usado no aplicativo, está com outras formas de autenticação e verificação da requisição está sendo enviada do aplicativo oficial do Sinesp cidadão.

2020-12-04 19:17 UTC, alvarofernandoms requested changes

2020-12-04 19:17 UTC, alvarofernandoms commented on yarn.lock
> +# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
@fabmont, o que você acha de remover esse lock (já que o projeto está usando npm) e ignorá-lo no `.gitignore`?  😉

2021-01-18 21:00 UTC, Caaddss commented
Marcando a issue relacionada

#137

2021-09-25 03:27 UTC, LorhanSohaky commented on pages/api/car/v1/[plate].js
> +import microCors from 'micro-cors';
O que acha de refatorar para o novo padrão? Agora há um `import app from '@/app';`

2021-09-25 03:27 UTC, LorhanSohaky commented on pages/api/car/v1/[plate].js
> +  return code;
Será que não deveria gerar uma exception se for um código diferente?

2021-09-25 03:27 UTC, LorhanSohaky commented on pages/api/car/v1/[plate].js
> +      const removedPrefix = model.replace(new RegExp('^(IMP/)'), '').split(' ');
Não estou muito familiarizado com a área de carros, mas para que situação remover o prefixo I faz sentido?

2021-09-25 03:27 UTC, LorhanSohaky commented on yarn.lock
> +# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
Up

2021-09-25 03:27 UTC, LorhanSohaky commented on pages/api/car/v1/[plate].js
> +      year: anoModelo,
Ainda estamos em discussão (seria até legal vc opinar), mas estamos pensando em padronizar as respostas das APIs. Uma das ideias é que o conteúdo da resposta seja em português e o caminha da rota também

2021-09-25 03:27 UTC, LorhanSohaky commented on package.json
> +    "sinesp-api": "^2.0.2"
```suggestion
    "sinesp-api": "2.0.2"
```

2022-03-07 23:47 UTC, fabmont commented on pages/api/car/v1/[plate].js
> +      year: anoModelo,
Show! uma vez que a API é voltada para o 🇧🇷, podemos manter tudo em português.

2022-07-18 19:04 UTC, rayanmarcus commented
Essa PR podia ir pra frente, hein! Agregaria muito pra Brasil API!

2022-07-18 19:12 UTC, murilohns commented
Pelo que vi esse projeto do sinesp-api usa a [api carros](https://github.com/100n0m3/API-Carros) por trás, e ela tem um limite de requisições. Pra aumentar esse limite existem os planos pagos.

Tem alguma fonte de dados gratuita?

2022-11-11 20:03 UTC, b2evandro commented
Essa api ficou fora do ar.

2023-01-22 02:30 UTC, LorhanSohaky commented
@fabmont , alguma sugestão de como seguir com esse PR?

2023-01-26 20:34 UTC, fabmont commented
Fiquei muito tempo sem dar uma olhada em que passo isso está.
Mas muitas barreiras foram colocadas nas APIs do governo para obter os dados dos veículos - implementaram o SSO do gov.br se não me engano.
Preciso investigar melhor isso.

2023-01-27 11:23 UTC, LorhanSohaky commented
@fabmont você pode remover o yarn.lock?

2023-01-28 00:44 UTC, LorhanSohaky requested changes
Acho que só ficou pendente os comentários antigos

2023-01-28 00:44 UTC, LorhanSohaky commented on pages/api/car/v1/[plate].js
> +import microCors from 'micro-cors';
Acho que isso ainda ficou pendente

2023-01-28 00:44 UTC, LorhanSohaky commented on pages/api/car/v1/[plate].js
> +  return code;
Aqui também

2023-03-21 02:13 UTC, simaomeyrer commented on pages/api/car/v1/[plate].js
> +      const removedPrefix = model.replace(new RegExp('^(IMP/)'), '').split(' ');
Pelo padrão que vi o `I`ou `IMP` se refere a carros importados, isso aparece no documento do veículo também

2024-11-16 01:33 UTC, josebruno2020 commented
Fala pessoal, blz?
Algum update sobre esse PR? Seria muito legal e útil ter esse serviço disponível! 🚀

2026-03-09 19:03 UTC, dorathoto commented
Apesar da consulta ser pública a SINESP coloca um conta gotas na busca, restringindo somente para aparelhos androids e ios, poucas consultas, precisa estar com GPS ligado e sem modo desenvolvedor no celular ainda sim 1 consulta por minuto. Ou seja é público só pra inglês ver, porque limitam e dificultam tudo, como o CEP no brasil

2026-04-11 22:55 UTC, lucianopf commented
Olá @fabmont, a ideia de consulta de veículos por placa é interessante, mas há questões importantes antes do merge.

**Questões que bloqueiam:**

**1. Acesso não oficial ao SINESP**

A lib `sinesp-api` é uma integração reverse-engineered com o SINESP, não uma API pública oficial. O SINESP não disponibiliza uma API pública aberta — o acesso é feito contornando o sistema, o que pode violar os Termos de Uso do serviço governamental.

**2. LGPD e dados pessoais**

Dados de veículos (proprietário, chassis, etc.) são dados pessoais cobertos pela Lei Geral de Proteção de Dados (LGPD). Expor esses dados publicamente via uma API sem autenticação levanta sérias questões legais que precisariam de análise antes de qualquer implementação.

**3. Cache de dados sensíveis por 24h**

```js
const CACHE_CONTROL_HEADER_VALUE = 'max-age=0, s-maxage=86400, ...'
```

Cachear por 24 horas o status de "veículo roubado" é perigoso — um veículo roubado poderia aparecer como "regular" durante horas após o boletim de ocorrência.

**4. PR muito antigo — requer rebase e atualizações**

O PR é de 2021 e o projeto mudou muito — `app()` wrapper, Vitest em vez de Jest, novas convenções de handler, etc.

Esta feature provavelmente precisa de uma discussão em issue na comunidade sobre viabilidade legal antes de qualquer implementação técnica.

2026-08-07 22:45 UTC, lucianopf commented
Olá! Este PR está parado há mais de 2 anos sem atividade do autor, com mudanças solicitadas na revisão que não foram aplicadas (ou base muito desatualizada). Estamos fechando para limpar a fila, mas **sinta-se à vontade para reabrir** quando quiser retomar — basta rebasear na main e ajustar conforme as solicitações de review. 🙏

Se a feature ainda for desejada, um PR novo com base atualizada tem muito mais chance de aprovação.

2026-08-07 22:45 UTC, closed without merging