Criação de endpoint /artistas utilizando a API Vagalume
BrasilAPI/BrasilAPI pull request #175
Opened 2020-12-16 17:35 UTC by arcticlimer

Com base na issue #157, criei um endpoint com uma integração à API Vagalume que retorna dados de um artista/banda. Como por exemplo as músicas de maior sucesso, bandas/artistas relacionados, gênero musical e outros.

closes #157

2020-12-17 10:21 UTC, RodriAndreotti commented
Seria interessante utilizar a rota do endpoint em Inglês, pergunto pois notei que as outras rotas que já temos meio que estão seguindo este padrão (no caso, banks, pois DDD e CEP são siglas... rs)

2020-12-17 12:31 UTC, arcticlimer commented
> Seria interessante utilizar a rota do endpoint em Inglês, pergunto pois notei que as outras rotas que já temos meio que estão seguindo este padrão (no caso, banks, pois DDD e CEP são siglas... rs)

Sim, acabei percebendo isso depois, pensei também em criar uma rota de `music` pra englobar isso dentro, porque `artistas` é um pouco amplo, e talvez depois expandir essa rota pra trazer informações sobre letras de músicas ou álbuns também.

2020-12-17 13:18 UTC, RodriAndreotti commented
> 
> 
> > Seria interessante utilizar a rota do endpoint em Inglês, pergunto pois notei que as outras rotas que já temos meio que estão seguindo este padrão (no caso, banks, pois DDD e CEP são siglas... rs)
> 
> Sim, acabei percebendo isso depois, pensei também em criar uma rota de `music` pra englobar isso dentro, porque `artistas` é um pouco amplo, e talvez depois expandir essa rota pra trazer informações sobre letras de músicas ou álbuns também.

É uma ideia legal tbm.

2020-12-17 13:28 UTC, hubertokf commented
Caindo de paraquedas, acho que artist faz sentido. Pode-se adicionar artistas que não sejam apenas músicos mas sim qualquer tipo de artista. 

No futuro ainda, pode haver outra rota pra musics e essa referencia os artistas e assim por diante. Assim como movies, novels, books ou paintings.

Já que essa informação vem do vagalume e assim só possui músicos, a rota pode ser definida como /musics/artists ou mais especificamente:

- /musics para pegar todas as músicas
- /musics/<id> para pegar uma música específica
- /musics/<id>/artists para pegar os músicos de uma música
- /musics/artists/ para obter todos os músicos
- /musics/artists/<id> para obter um músico específico

Não sei como funciona a api do vagalume mas essa estrutura seria interessante. Vale um mapeamento da API do vagalume pra entender quais informações são entregues por ela.

2020-12-18 02:59 UTC, filipedfs commented
Vim aqui fazer um fork do projeto para começar a pensar na API e já tem uma PR pra minha ideia! haha Muito legal.

Só um comentário:

Eu não usaria o termo "artista" para definir músicos, porque artista pode ser instrumentista, compositor, pintor, dançarino, ator, etc. Na issue #157 eu comentei hoje como acho que poderia ser, mas o escopo seria bem maior.

Eu não sei exatamente quais as informações que a API Vagalume retorna, mas os conceitos que tenho em mente para informação referente a músicos são:

**composer** - "compositor", quem cria música
**arranger** - "arranjador", quem faz arranjo de música
**performer** - "intérprete", quem executa música (pode ser uma pessoa ou um grupo, que pode ou não ser também compositor)
**lyricist** - "letrista", quem cria texto para música
**work** - obra musical

Como falei na issue, esses termos estão relacionados com minha experiência musical que é com música de concerto, mas acho que essas definições servem para qualquer tipo de música.

2020-12-18 03:32 UTC, arcticlimer commented
> Vim aqui fazer um fork do projeto para começar a pensar na API e já tem uma PR pra minha ideia! haha Muito legal.
> 
> Só um comentário:
> 
> Eu não usaria o termo "artista" para definir músicos, porque artista pode ser instrumentista, compositor, pintor, dançarino, ator, etc. Na issue #157 eu comentei hoje como acho que poderia ser, mas o escopo seria bem maior.
> 
> Eu não sei exatamente quais as informações que a API Vagalume retorna, mas os conceitos que tenho em mente para informação referente a músicos são:
> 
> **composer** - "compositor", quem cria música
> **arranger** - "arranjador", quem faz arranjo de música
> **performer** - "intérprete", quem executa música (pode ser uma pessoa ou um grupo, que pode ou não ser também compositor)
> **lyricist** - "letrista", quem cria texto para música
> **work** - obra musical
> 
> Como falei na issue, esses termos estão relacionados com minha experiência musical que é com música de concerto, mas acho que essas definições servem para qualquer tipo de música.

Concordo, mas acaba que pela API Vagalume em si generalizar os músicos (O que faz todo sentido, por que tem uma base de dados gigante lá, entre artistas solo e bandas, não daria para classificar tudo), não tem uma separação dessas categorias lá, talvez no máximo por gênero musical, então nesse escopo acho que seja aceitável termos a rota /music/v1/artist para isso.

2021-05-08 23:23 UTC, lnfernandobr requested changes
Deixei vários comentários. Por favor, veja-os.

2021-05-08 23:23 UTC, lnfernandobr commented on pages/api/music/v1/artist/[artist].js
> +  const artist = request.query.artist;
Você pode extrair o artist. Assim:
```
const { artist } = request.query;

```

2021-05-08 23:23 UTC, lnfernandobr commented on pages/api/music/v1/artist/[artist].js
> +  if (artistData.type === 'ARTIST_NOT_FOUND') response.status(404);
Recomendo extrair esse `ARTIST_NOT_FOUND` em uma variável, ou até mesmo um enum de types.

2021-05-08 23:23 UTC, lnfernandobr commented on pages/api/music/v1/artist/[artist]/[music].js
> +  if (/NOT_FOUND$/.test(music.type)) response.status(404);
Use
```
if (/NOT_FOUND$/.test(music.type)) {
  response.status(404);
}

```

Para manter o padrão

2021-05-08 23:23 UTC, lnfernandobr commented on services/vagalume.js
> +const musicNotFound = {
Para manter o padrão, deixe esse `musicNotFound` em caixa alta

2021-05-08 23:23 UTC, lnfernandobr commented on services/vagalume.js
> +    switch (response.status) {
Há necessidades de usar um Swtich para um único status de 404? Pq não usar um if?? Ou até mesmo um objeto mapper

2021-05-08 23:23 UTC, lnfernandobr commented on services/vagalume.js
> +// Função principal de filtragem dos dados da API vagalume.
Comentário irrelevante, pelo nome da função agente já sabe o uso dela

2021-05-08 23:23 UTC, lnfernandobr commented on services/vagalume.js
> +// Funções helper para a filtragem
idem

2021-05-08 23:23 UTC, lnfernandobr commented on services/vagalume.js
> +  const url = 'https://api.vagalume.com.br/search.php';
Recomendo criar um env para adicionar essas urls. Algo como  `env.settings.vagalume.urlBase`. Caso haja mudanças na url, vc só altera naquele lugar

2021-05-08 23:23 UTC, lnfernandobr commented on services/vagalume.js
> +  if (data.type === 'notfound') return artistNotFound;
Por favor, seguir um padrão aqui. Ou `song_notfound` e `not_found` ou `songNotfound` e `notfound`. Extrair em variaveis esses status também. Usar os `{ }` para o `if`

2021-05-08 23:23 UTC, lnfernandobr commented on services/vagalume.js
> +  // Precisamos colocar o 404 na rota, pois a API retorna 200 mesmo
Não entendi esse comentário com o código abaixo, explique-me, por favor.

2021-05-08 23:23 UTC, lnfernandobr commented on services/vagalume.js
> +  999999: 'Outro',
Isso não faz sentido, `9999`?

2021-05-08 23:23 UTC, lnfernandobr commented on services/vagalume.js
> +    translations: translate.map(createTranslation),
Um map que não transforma o content?

2022-01-24 21:14 UTC, closed without merging