feat(project): add commitzen standardize commit messages
BrasilAPI/BrasilAPI pull request #204
Opened 2021-01-27 12:19 UTC by allangrds

## Contexto
## Checklist
## Como testar

Reference #199

2021-01-27 19:57 UTC, PauloGoncalvesBH reviewed
boa implementação @allangrds.
O que acha de fazer 2 outras implementações nesse PR?
1. Incluir informação no _CONTRIBUTING.md_ sobre a convenção de commit que deve ser seguido (nem todos usam git pelo terminal).
2. Colocar actions em pipeline para validar o commit.
Sugestão: https://github.com/wagoid/commitlint-github-action
Exemplo de pipeline usando essa action: https://github.com/PauloGoncalvesBH/ServeRest/blob/trunk/.github/workflows/continuous_integration.yml#L22

2021-01-27 21:40 UTC, PauloGoncalvesBH commented on .github/workflows/commitlint.yml
> +
Vi que criou uma nova pipeline de execução em PR apenas para o _commit lint_, e que já temos uma pipeline que executa apenas em PR, que é o `e2e-tests.yml`.
O que acha de unificar a nova pipe com a já existente para ficar claro que é um conjunto de validações de PR?

### Sugestão
Fazer parecido com o que fiz nesse PR que está em draft: https://github.com/BrasilAPI/BrasilAPI/pull/201/files

Dessa forma a exibição no PR ficaria próximo a isso:
![Captura de tela de 2021-01-27 18-39-18](https://user-images.githubusercontent.com/29241659/106057624-ff702080-60ce-11eb-913e-0dd1fa175345.png)

2021-01-28 16:10 UTC, PauloGoncalvesBH approved these changes
Ótima contribuição @allangrds

2021-01-28 20:10 UTC, murilohns requested changes
Fala @allangrds, tudo certo?

Fui testar seu PR, e o `commitzen` me pediu até meu CPF e RG pra fazer um _commit_!

Apesar de curtir muito a ideia de padronizar as mensagens de _commit_, acho que isso pode desencorajar pessoas a contribuírem com o projeto.

Podemos deixar isso de forma mais aberta, como um instruções no `contributing.md`, deixando como sugestão a mensagem de _commit_ que as pessoas devem escrever.

Alguns problemas que vejo em implantar o _commitzen_ são:
1. Nem todos podem ter conhecimento  em inglês
2. Pode desencorajar novos contribuidores devido à quantidade de perguntas do _commitzen_
3. Pode ser o primeiro PR de alguém na vida, e ter tanto empecilhos pra um único _commit_ não é tão atrativo

2021-02-23 16:49 UTC, lucianopf commented
Concordo com os pontos do querido @murilohns @allangrds , o que acha? 🙏

2021-02-23 16:55 UTC, allangrds commented
Farei ainda hoje as alterações :)

2021-03-09 16:59 UTC, allangrds commented
@PauloGoncalvesBH @murilohns @lucianopf PR alterado com os ótimos comentários do @murilohns.

2021-03-09 21:19 UTC, PauloGoncalvesBH requested changes

2021-03-09 21:19 UTC, PauloGoncalvesBH commented on CONTRIBUTING.md
> +> Caso esse padrão não seja seguido o commit será abortado. Se conseguir criar tal commit, a pipeline no [pull request](#pull-requests-prs) irá detectar e quebrar.
```suggestion
```

Esse comportamento não é mais válido com as últimas implementações.

2021-03-10 12:54 UTC, PauloGoncalvesBH approved these changes

2021-03-11 19:03 UTC, PauloGoncalvesBH submitted a review, later dismissed

2021-03-11 20:39 UTC, pedrosancao commented
@allangrds tudo bom? Eu vi que você atualizou a lista de contribuidores mas ainda falou algumas das novas pessoas (inclusive eu 😄), pensando nisso criei um comando na PR #274 para fazer essa atualização, ai minha _sugestão_ é remover o _commit_ com essa alteração no readme para deixar o PR apenas com o commitzen. E a atualização das pessoas que contribuíram fica na outra PR.

O que acham?

2021-03-11 22:22 UTC, murilohns approved these changes

2021-03-12 12:41 UTC, murilohns approved these changes

2021-03-12 12:42 UTC, merged