Cria endpoint de feriados nacionais
BrasilAPI/BrasilAPI pull request #256
Opened 2021-02-14 22:36 UTC by pedrosancao

Olá pessoal, antes de fazer esse _pull request_ eu fiz um levantamento da situação desse recurso:

- O recurso foi solicitado nas _issues_ #68 e #118, nas duas ocasiões foram mencionados feriados nacionais e municipais.
- Existe três _pull requests_ para esse recurso em revisão: #121, #161 e #169 

As considerações feitas nesses PR estão relacionadas às limitações de acessar uma API externa, então optei por uma abordagem diferente.

No primeiro momento gerar uma lista apenas dos feriados nacionais, por ano. Existem alguns algoritmos para calcular os feriados móveis (Carnaval, Páscoa e Corpus Christi) e eles estão bem documentados na [wikipedia][computus]. Usando esses algoritmos é possível gerar a lista sem depender de um serviço externo.

Posteriormente pensamos em fornecer os feriados estaduais e municipais, incrementando os recursos fornecidos.

---

Nesse _pull request_:
- criei um serviço para isolar a lógica do cálculo;
- inclui a documentação no README e na pagina `docs`;
- criei os testes E2E
![tests-passing](https://user-images.githubusercontent.com/5047991/107891067-1bf7bf80-6efb-11eb-8485-4322e73f7ea9.png)

O que vocês acham dessa abordagem/implementação?

[computus]: https://en.wikipedia.org/wiki/Computus

2021-02-15 02:09 UTC, RafaelPena31 approved these changes

2021-02-21 20:35 UTC, Nikolassantos submitted a review, later dismissed

2021-02-21 23:17 UTC, raulpy271 requested changes

2021-02-21 23:17 UTC, raulpy271 commented on services/holidays/index.js
> +export default function getNacionalHolidays(year) {
Olá @pedrosancao

Está um pouco díficil de entender como a função `getNacionalHolidays` funciona, eu sei que ela converte  a matriz com feriados para um objeto, mas, o processo interno não ficou claro pra mim.

Uma sugestão para deixar essa função mais clara seria criar uma função intermediária que convertesse a matriz retornada por `getNacionalHolidaysByMonth` para um objeto, depois chama-la dentro da função da linha 73, com isso ela ficaria menor.

Além disso, acho que o nome da função `getNacionalHolidaysByMonth` não está claro, pelo nome imagina-se que seu argumento é um mês, minha sugestão seria: `getNationalHolidaysInAMatrix`.

O que vocês acham?

2021-02-22 00:05 UTC, pedrosancao commented on services/holidays/index.js
> +export default function getNacionalHolidays(year) {
Olá Raul, obrigado pelo feedback. Eu também não fiquei completamente satisfeito com essa função, pensando na sua sugestão acho melhor "desmontar" as _arrow functions_ e usar mais variáveis para facilitar a leitura/entendimento ao invés de uma função intermediária, sobre o nome gostei bastante e varia um pequeno ajuste: `getNationalHolidaysAsMatrix`.

2021-02-22 01:01 UTC, raulpy271 commented on services/holidays/index.js
> +export default function getNacionalHolidays(year) {
Concordo contigo, acho que mais variáveis com bons nomes vão ajudar

2021-02-22 02:28 UTC, pedrosancao commented
@raulpy271 refatorei/renomeei os métodos destacados na sua revisão. Essencialmente separei as etapas de percorrer e reduzir a matriz usando variáveis com nomes significativos, o resultado ficou um pouco mais verboso mas achei bem mais fácil de ler.

Se houver mais alguma consideração só falar 😄

2021-02-22 09:47 UTC, RodriAndreotti commented
> 
> 
> @raulpy271 refatorei/renomeei os métodos destacados na sua revisão. Essencialmente separei as etapas de percorrer e reduzir a matriz usando variáveis com nomes significativos, o resultado ficou um pouco mais verboso mas achei bem mais fácil de ler.
> 
> Se houver mais alguma consideração só falar 😄

Cara, bom dia!
Não cheguei a revisar o PR ainda, mas sobre seu comentário, se me permitir, vou deixar uma opinião pessoal.
Hoje em dia tenho visto que muitos tem se preocupado com as funções ficarem "muito verbosas", pessoalmente acho que isso não deveria ser uma preocupação, me explico:

Nem sempre quem desenvolve uma rotina será a mesma pessoa que dará manutenção a ela, e mesmo nos casos quando isso acontece, a pessoa já não lembra mais o que fez, quantas vezes já peguei código de 2 ou 3 anos atrás e não lembrava uma vírgula do código... rs

Um código verboso o torna, como vc mesmo disse, mais fácil de ler (eu diria até auto-documentado), se tiver o docblock ainda, muito melhor. Acho que parte da preocupação com a verbosidade do código em JS vem por conta do tamanho do asset, talvez, mas será que é realmente um impacto tão grande?

Eu vejo um uso muito grande das arrow functions, mesmo em contextos onde elas não são necessárias, e, eu acho horrível para entender o que elas fazem, pois muitas vezes não estão associadas a variáveis, estão em callbacks, ou outras formas que a tornam meio confusas. O que costumo fazer para facilitar a leitura é, se não vou precisar do contexto (this) do pai, sempre dou preferência a usar functions normais, assim batendo o olho no código já consigo notar logo de cara que aquilo é uma função, ainda que anônima.

Para quem já está bem mais familiarizado com o JS (ou outras linguagens que suportem arrow funcions, agora até PHP suporta... rs) pode ser que isso que falei seja besteira, mas cabe lembrar que muitos projetos programadores iniciantes também assumem, e eles podem sofrer um pouco com essa manutenção... rs

Bom, mas é isso, só queria mesmo deixar meu pitaco sobre a verbosidade do código... rs

No demais, parabéns pelo ótimo PR!

2021-02-22 12:31 UTC, pedrosancao commented
Pessoal, eu tinha usado como base para esse PR um código bem específico de um projeto pessoal, e ainda não estou satisfeito com o resultado aqui. Agora com os testes criados fica fácil refatorar, então minha tenho intenção de simplificar ao máximo o código aqui, por isso vou deixar a PR como _draft_

2021-02-22 13:28 UTC, raulpy271 commented
Bom dia @RodriAndreotti!

Eu concordo contigo, eu também acho que não devemos hésitar em por nomes nas funções, se for um nome representativo sempre ajuda. Apesar dessas nomes deixarem a função maior, não necessariamente ela fica mais complexa, mais importante que deixar as funções com menos linhas é deixa-las com menos responsabilidade.

E sobre arrow functions eu não acho que elas sejam um problema para legibilidade, o problema é que geralmente se daclara arrow functions sem atribuí-las um nome, como você citou.

Concorda?

2021-02-22 13:29 UTC, raulpy271 commented
Obrigado pela atenção, @pedrosanca. Depois irei rever as alterações

2021-02-22 17:42 UTC, RodriAndreotti commented
> 
> 
> Bom dia @RodriAndreotti!
> 
> Eu concordo contigo, eu também acho que não devemos hésitar em por nomes nas funções, se for um nome representativo sempre ajuda. Apesar dessas nomes deixarem a função maior, não necessariamente ela fica mais complexa, mais importante que deixar as funções com menos linhas é deixa-las com menos responsabilidade.
> 
> E sobre arrow functions eu não acho que elas sejam um problema para legibilidade, o problema é que geralmente se daclara arrow functions sem atribuí-las um nome, como você citou.
> 
> Concorda?

Sim, foi neste sentido mesmo que quis dizer, pois é uma ferramenta também, que usada corretamente é ótima, mas quando mal usada atrapalha muito a legibilidade.

Quanto a menos responsabilidades, na realidade, sou totalmente de acordo com os princípios SOLID (Neste caso com o S, principalmente), acho que uma função/método só deve ter um motivo para existir, e principalmente um motivo para ser alterada.

2021-02-23 16:11 UTC, lucianopf commented on services/holidays/index.js
> +  return `${date.getFullYear()}-${formatedMonth}-${formatedDay} 00:00:00`;
Dúvida: dado que o feriado ocorre no dia todo não seria melhor especificar apenas o dia sem horas? 😬 
`YYYY-MM-DD`

```suggestion
  return `${date.getFullYear()}-${formatedMonth}-${formatedDay}`;
```

2021-02-23 16:17 UTC, lucianopf reviewed
Só deixei um pequeno comentário pra fomentar a discussão mas já deixo claro que achei o PR animal e dps dessa decisão podemos seguir com approve! 🤩

2021-02-23 16:32 UTC, RodriAndreotti commented
> 
> 
> Só deixei um pequeno comentário pra fomentar a discussão mas já deixo claro que achei o PR animal e dps dessa decisão podemos seguir com approve! 🤩

Seria o momento de pensarmos numa padronização de formatos de data/hora para o projeto? :-p

2021-02-23 16:43 UTC, lucianopf commented
> > Só deixei um pequeno comentário pra fomentar a discussão mas já deixo claro que achei o PR animal e dps dessa decisão podemos seguir com approve! 🤩
> 
> Seria o momento de pensarmos numa padronização de formatos de data/hora para o projeto? :-p

Mestre, acho que tem 2 padrões já no JS que a galera usa pra APIs, ISOString e dateonly que é o `YYYY-MM-DD` cada um tem seu uso e não sei se cabe usar apenas 1 em toda API se cada endpoint é meio que um serviço isoladinho, o que acha? 🤔 

Aaa e pfv, se lembra de outros formatos que a galera costuma usar no JS pfv fica a vontade de comentar! ^^

2021-02-23 16:55 UTC, RodriAndreotti commented
> 
> 
> > > Só deixei um pequeno comentário pra fomentar a discussão mas já deixo claro que achei o PR animal e dps dessa decisão podemos seguir com approve! 🤩
> > 
> > 
> > Seria o momento de pensarmos numa padronização de formatos de data/hora para o projeto? :-p
> 
> Mestre, acho que tem 2 padrões já no JS que a galera usa pra APIs, ISOString e dateonly que é o `YYYY-MM-DD` cada um tem seu uso e não sei se cabe usar apenas 1 em toda API se cada endpoint é meio que um serviço isoladinho, o que acha? 🤔
> 
> Aaa e pfv, se lembra de outros formatos que a galera costuma usar no JS pfv fica a vontade de comentar! ^^

Na realidade a minha ideia era justamente trabalhar com os dois formatos, eu falei em definir justamente porque já peguei muita API para mexer, que em cada endpoint a data vem de um jeito, em um endpoint está como dd/mm/yyyy, outro com yyyy-mm-dd, outro ainda como yy-mm-dd.

Aliás, aqueles endpoints da CPTEC em soap tinham umas neuras assim, que tentei normalizar... kkk

Não sei se poderíamos considerar isso como uma padrão, mas talvez um manual de boas práticas, se a data contém horário, trazemos um ISOString e se não o dateonly, que, em ambos casoso, concordo plenamente que é o mais indicado para se retornar, pois é compatível com qualquer linguagem que o cliente for usar.

Mas acho que isso seria interessante acrescentar no contributing, o que acha?

2021-02-23 16:57 UTC, lucianopf commented
> > > > Só deixei um pequeno comentário pra fomentar a discussão mas já deixo claro que achei o PR animal e dps dessa decisão podemos seguir com approve! 🤩
> > > 
> > > 
> > > Seria o momento de pensarmos numa padronização de formatos de data/hora para o projeto? :-p
> > 
> > 
> > Mestre, acho que tem 2 padrões já no JS que a galera usa pra APIs, ISOString e dateonly que é o `YYYY-MM-DD` cada um tem seu uso e não sei se cabe usar apenas 1 em toda API se cada endpoint é meio que um serviço isoladinho, o que acha? 🤔
> > Aaa e pfv, se lembra de outros formatos que a galera costuma usar no JS pfv fica a vontade de comentar! ^^
> 
> Na realidade a minha ideia era justamente trabalhar com os dois formatos, eu falei em definir justamente porque já peguei muita API para mexer, que em cada endpoint a data vem de um jeito, em um endpoint está como dd/mm/yyyy, outro com yyyy-mm-dd, outro ainda como yy-mm-dd.
> 
> Aliás, aqueles endpoints da CPTEC em soap tinham umas neuras assim, que tentei normalizar... kkk
> 
> Não sei se poderíamos considerar isso como uma padrão, mas talvez um manual de boas práticas, se a data contém horário, trazemos um ISOString e se não o dateonly, que, em ambos casoso, concordo plenamente que é o mais indicado para se retornar, pois é compatível com qualquer linguagem que o cliente for usar.
> 
> Mas acho que isso seria interessante acrescentar no contributing, o que acha?

Boooa mestre, concordo contigo! 😬 

Será que seria uma boa adicionar ao guia de contribuição alguns formatos padrões de dados tipo data? 🤔  (curti mesmo a ideia hein! hehehe)

Seria bom até pra apontar no review como guia 😬

2021-02-23 17:08 UTC, RodriAndreotti commented
> 
> 
> > > > > Só deixei um pequeno comentário pra fomentar a discussão mas já deixo claro que achei o PR animal e dps dessa decisão podemos seguir com approve! 🤩
> > > > 
> > > > 
> > > > Seria o momento de pensarmos numa padronização de formatos de data/hora para o projeto? :-p
> > > 
> > > 
> > > Mestre, acho que tem 2 padrões já no JS que a galera usa pra APIs, ISOString e dateonly que é o `YYYY-MM-DD` cada um tem seu uso e não sei se cabe usar apenas 1 em toda API se cada endpoint é meio que um serviço isoladinho, o que acha? 🤔
> > > Aaa e pfv, se lembra de outros formatos que a galera costuma usar no JS pfv fica a vontade de comentar! ^^
> > 
> > 
> > Na realidade a minha ideia era justamente trabalhar com os dois formatos, eu falei em definir justamente porque já peguei muita API para mexer, que em cada endpoint a data vem de um jeito, em um endpoint está como dd/mm/yyyy, outro com yyyy-mm-dd, outro ainda como yy-mm-dd.
> > Aliás, aqueles endpoints da CPTEC em soap tinham umas neuras assim, que tentei normalizar... kkk
> > Não sei se poderíamos considerar isso como uma padrão, mas talvez um manual de boas práticas, se a data contém horário, trazemos um ISOString e se não o dateonly, que, em ambos casoso, concordo plenamente que é o mais indicado para se retornar, pois é compatível com qualquer linguagem que o cliente for usar.
> > Mas acho que isso seria interessante acrescentar no contributing, o que acha?
> 
> Boooa mestre, concordo contigo! 😬
> 
> Será que seria uma boa adicionar ao guia de contribuição alguns formatos padrões de dados tipo data? 🤔 (curti mesmo a ideia hein! hehehe)
> 
> Seria bom até pra apontar no review como guia 😬

Acho que seria muito interessante sim, talvez se tentarmos sempre trabalhar com padrões ISO, ou alguma outra norma internacional que garanta que os dados sejam entregues num formato compatível com a maioria das linguagens de programação que possam vir a consumir os dados.

Vou ver se sobra um tempinho para tentar atualizar o guia de contribuição, pelo menos com a data, hoje, e podemos ir adicionando outros tipos de dados de acordo com as necessidades que forem aparecendo (talvez até o formato monetário, separando moeda com seu código internacional (BRL, USD, COP etc) e definição de formato (com vírgula ou ponto, com sinal de - ou () para indicar números negativos, e por ai vai)

2021-02-23 17:25 UTC, pedrosancao commented on services/holidays/index.js
> +  return `${date.getFullYear()}-${formatedMonth}-${formatedDay} 00:00:00`;
Obrigado pela revisão Luciano.
O motivo de eu ter feito com a hora zerada foi o _parse_ do `new Date()`, mas repensando agora não faz sentido resolver um problema do lado do cliente na API, acho que a sugestão faz todo o sentido, mas como afeta os testes e outros pontos precisa de uma atualização um pouco maior do que a sugerida.
A noite eu faço as alterações.

2021-02-23 17:32 UTC, pedrosancao commented
Pessoal, criei a issue #262 para prosseguir com a discussão sobre os formatos de data globalmente no projeto.

A próxima atualização farei o merge para corrigir o conflito e as alterações para retornar apenas a data (sem hora).

2021-02-23 17:40 UTC, murilohns commented on services/holidays/index.js
> +function getNacionalHolidaysUnordered(year) {
Algumas funções ficaram em portuinglês, se puder ajeitar de `Nacional` pra `National` nesses lugares pra manter o padrão fica melhor 👍🏾

2021-02-23 17:50 UTC, pedrosancao commented on services/holidays/index.js
> +function getNacionalHolidaysUnordered(year) {
Boa! Foi erro de digitação essa aí

2021-02-23 22:13 UTC, pedrosancao commented
Adicionei as seguintes atualizações:
- resolução de conflitos com a _branch_ master;
- remoção do fragmento de hora no código, testes e documentação;
- correção e melhorias de nomenclaturas;
- adição do campo de tipo para permitir expansão futura sem modificar estrutura da resposta;
- criação de teste para verificar ordenação.

2021-02-24 13:52 UTC, murilohns reviewed
Obrigado pela contribuição @pedrosancao, deixei apenas um comentário pra simplificar o código, mas no demais está ótimo!

Assim que corrigir isso posso aprovar =]

2021-02-24 13:52 UTC, murilohns commented on services/holidays/index.js
> +  return holidays.sort((a, b) => {
```suggestion
  return holidays.sort((a, b) => a.date > b.date)
```

💅🏾

2021-02-24 15:07 UTC, pedrosancao commented on services/holidays/index.js
> +  return holidays.sort((a, b) => {
Infelizmente essa alteração não passou no caso de teste que verifica a ordenação.

2021-02-24 16:16 UTC, murilohns approved these changes

2021-02-24 16:18 UTC, lucianopf approved these changes
🚀 ❤️

2021-02-24 16:20 UTC, merged

2021-03-09 13:56 UTC, klucass commented
Olá pessoal,

parabéns pelo belo trabalho. Estive olhando a API de feriados e notei que ele considera somente a terça-feira de carnaval como feriado. Olhando outras fontes de feriados nacionais oficiais, como o site da Anbima (https://www.anbima.com.br/feriados/) percebi que eles consideram a segunda e a terça-feiras como feriados baseados na resolução 2516 do BACEN (https://www.bcb.gov.br/pre/normativos/res/1998/pdf/res_2516_v2_P.pdf).

Acho que seria o caso de discutir a inclusão da segunda-feira de carnaval na lista de feriados móveis calculados pela páscoa, o que acham?

2021-03-09 17:16 UTC, RodriAndreotti commented
Cara, posso estar enganado, mas me parece que segunda-feira de carnaval é ponto facultativo (tal como o sábado que antecede o carnaval), só é considerada feriado mesmo pelo sistema bancários (talvez por isso a resolução do BACEN)

2021-03-13 16:34 UTC, pedrosancao commented
> Olá pessoal,
> 
> parabéns pelo belo trabalho. Estive olhando a API de feriados e notei que ele considera somente a terça-feira de carnaval como feriado. Olhando outras fontes de feriados nacionais oficiais, como o site da Anbima (https://www.anbima.com.br/feriados/) percebi que eles consideram a segunda e a terça-feiras como feriados baseados na resolução 2516 do BACEN (https://www.bcb.gov.br/pre/normativos/res/1998/pdf/res_2516_v2_P.pdf).
> 
> Acho que seria o caso de discutir a inclusão da segunda-feira de carnaval na lista de feriados móveis calculados pela páscoa, o que acham?

Obrigado pelo comnentário @klucass. Concordo com o comentário do @RodriAndreotti, essa instrução é especifica sobre o setor bancário, os feriados com data fixa são baseados em lei federal conforme [esse comentário](https://github.com/BrasilAPI/BrasilAPI/blob/ba1ee59ab768a7da81a7991112d5e6147fa1d4de/services/holidays/index.js#L73), não há lei federal para a terça feira de carnaval, mas pelo que olhei a maioria dos estados tem uma lei específica declarando essa data como feriado estadual, por isso mantive.

Assim como a segunda feira de carnaval é a Sexta feira Santa/Paixão de Cristo que é feriado apenas em algumas localidades, até deixei o código com a referência dessa data, não há um consenso nacional sobre ser feriado, por isso ficaram de fora.