Preço e prazo de fretes pelos correios
BrasilAPI/BrasilAPI pull request #260
Opened 2021-02-22 23:13 UTC by pedrosancao

Novo PR para dar continuidade ao #76 devido à falta de aceso para adicionar _commits_ no repositório do colega que abriu o PR.

Proponho as seguintes tarefas:

- [x] corrigir conflitos com _branch_ principal
- [x] separar responsabilidades dos serviços ([e99f63e](https://github.com/pedrosancao/BrasilAPI/commit/e99f63e54d0bd8dcf8c85831eaa02fda199a2d97))
- [ ] padronizar mensagens de erro desse recurso e outros _endpoints_ BrasiAPI
- [ ] criar documentação
  - [ ] no README
  - [ ] na página `/docs`

Se alguém quiser pegar algum item pra fazer avisa aqui para adicionar a permissão no meu _fork_ e a gente não fazer duplicado 😉 

Resolve: #232

2021-02-23 16:45 UTC, lucianopf reviewed
Mestre @pedrosancao deixei uns comentários aí mas fica a vontade de dar dismiss! 😬

2021-02-23 16:45 UTC, lucianopf commented on pages/api/shipping/v1/calculate-price.js
> +    return response.status(422).json(err);
Dúvida:

Não seria mandar uma mensagem definida ou um objeto explícito ao invés de só remover alguns atributos antes de enviar? 😬

2021-02-23 16:45 UTC, lucianopf commented on pages/api/shipping/v1/calculate-price.js
> +        more_info: 'httos://brasilapi.com.br',
```suggestion
        more_info: 'https://brasilapi.com.br/docs',
```

2021-02-23 16:45 UTC, lucianopf commented on services/shipping/index.js
> +import makeRequest from '../soapRequestService';
Dúvida:
Sei que a API do correios é SOAP e usa XML mas será que esse precisa ser o nome do serviço que se conecta ao correios?

Eu talvez colocaria a lógica de montar a querystring e de fazer o parse do XML aqui dentro desse service tendo em vista que ele é apenas usado por esse serviço 🤔 😬

2021-02-23 16:45 UTC, lucianopf commented on services/soapRequestService/index.js
> +    .join('&');
Sugestão cosmética: Já usou o método `Object.entries`? Esse método é muito massa e evita um pouco acessar o objeto na chave como a gnt fazia antes quando só tinha o Object.keys 😬 

https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Global_Objects/Object/entries

<img width="393" alt="Screen Shot 2021-02-23 at 13 33 14" src="https://user-images.githubusercontent.com/8251208/108875376-e2e6db80-75db-11eb-9fb6-9b62710b4ec8.png">

Daí bastaria fazer 
```
.map(([key, value]) => `${key}=${value}`)
```

2021-02-23 17:11 UTC, murilohns requested changes
Dúvida: Se quisermos calcular frete em outro serviço, conseguimos usar esse mesmo endpoint?

Os parâmetros de entrada são específicos para buscas nos correios, acha que deixar específico dessa forma é a melhor estratégia?

2021-02-23 17:11 UTC, murilohns commented on services/soapRequestService/index.js
> +      } else {
não precisa desse `else` aqui 💅🏾

2021-02-23 21:00 UTC, pedrosancao commented on services/soapRequestService/index.js
> +      } else {
Ao retirar o `else` ambos `reject` e `resolve` serão executados, esse não é o intuito.

Relacionado: https://stackoverflow.com/a/32536083/2932525

2021-02-23 21:47 UTC, murilohns commented on services/soapRequestService/index.js
> +      } else {
Você pode por o `return` pra evitar esse comportamento:

```js
  if(err) {
    return reject(err)
  }
  
  return resolve(err)
```

Se necessário você pode usar o return depois do reject também

```js
  reject(err)
  return
```

2021-02-23 23:52 UTC, pedrosancao commented
> Dúvida: Se quisermos calcular frete em outro serviço, conseguimos usar esse mesmo endpoint?
A princípio não, mas a proposta do PR é ser especifico do Correio.

> Os parâmetros de entrada são específicos para buscas nos correios, acha que deixar específico dessa forma é a melhor estratégia?
Pretendo fazer, além de ocultar/tornar opcional alguns dos parâmetros.

2021-02-24 21:09 UTC, pedrosancao commented
Pessoal, esses foram os comentários que achei mais relevantes no PR relacionado que fomentam a discussão:

> Sobre as questões:
> # Validação: body
> 
> Excelente ponto, acho que não foi discutido nada sobre isso +1 Eu sei que o Joy é muito comum, mas ele vai ser descontinuado. Não conhecia a solução que você usou, mas me pareceu bem simples. No passado eu tive uma experiência interessante com o `is-my-json-valid`. @lucianopf alguma opinião sobre isso?
> # Validação: mensagem de erro
> 
> Outro excelente ponto, acho que isso ainda não foi discutido também, mas de todos os serviços que vamos consultar, o BrasilAPI tem que criar uma "camada de anticorrupção" e normalizar todos os erros. Isso foi feito no `cep-promise`, pois lá também é feita a consulta de serviços diferentes.
> 
> Pelo que vi, no seu PR tem esses padrões para mensagens de erro:
> 
> ```
> {
>       name: "",
>       errors: [""],
>       message: ""
> }
> ```
> 
> E num outro momento:
> 
> ```
> {
>       error: {
>         message: "",
>         more_info: ""
>       }
>     }
> ```
> 
> E no caso do endpoint de consulta de cep, tem esse padrão:
> 
> ```
> {
>   "name": "",
>   "message": "",
>   "type": "",
>   "errors": [
>     {
>       "name": "",
>       "message": "",
>       "service": ""
>     }
>   ]
> }
> ```
> 
> A hora é agora de padronizarmos joy
> # Resposta de sucesso
> 
> Pelo que eu vi você usou tanto pra entrada quanto saída os parâmetros do serviço original. Sugiro sinceramente abstrair isso e implementar os próprios com um padrão mais atual e em iglês +1 tipo ao invés de `sCepOrigem` ser somente `origin` (dado que o contexto é cep).
> # Endpoint
> 
> Ao invés de `shipping` o que acha de talvez algo relacionado ao `correios` porque `shipping` é algo que pode se encaixar em qualquer serviço... por exemplo imagina implementar algo do `fedex`. Então talves até tava pensando aqui algo `/shipping/correios` o que acha? Ou definir o serviço no `body`.. não sei.
> # Consumir SOAP
> 
> O que acha de, ao invés de implementarmos a nossa solução, usar um módulo que já tenha resolvido isso?
> 
> Por exemplo:
> 
>     * https://www.npmjs.com/package/soap
> 
>     * https://www.npmjs.com/package/easy-soap-request

_Originalmente publicado por @filipedeschamps em https://github.com/BrasilAPI/BrasilAPI/issues/76#issuecomment-650595536_

---

> Seguindo a thread [...]
> ## Validação: body
> 
> Eu confesso que não conhecia esse Yup, dei uma lidinha na doc e gostei bastante! Inclusive nesse momento estava ofão de uma lib de validação pq o projeto Hapi ta sendo discontinuado e não curto muito o AJV.
> ## Validação: mensagem de erro
> 
> To total de acordo com o @filipedeschamps nessa, acho que estamos num bom ponto pra pensar em normalizar os formatos de resposta de errrors grimacing
> ## Resposta de sucesso
> 
> Concordo bastante tbm que da pra abstrair o nome dos parâmetros de entrada e os de saída, acho que vai ficar ainda mais simples de usar essa rota grimacing
> ## Endpoint
> 
> Boa mestre, super interessante a proposta de criar um "workspace" `shipping`, acho que libera várias novas implementações, tipo usando a Loggi grimacing
> ## Consumir SOAP
> 
> Concordo e inclusive acredito que tem lógica exclusiva do correio no arquivo `soapRequestService`, e que talvez devesse ser renomeado pra CorreiosSoapService ou tornar o arquivo atual mais genérico

_Originalmente publicado por @lucianopf em https://github.com/BrasilAPI/BrasilAPI/pull/76#pullrequestreview-438787294_

2021-04-04 08:30 UTC, Atiladanvi commented
@pedrosancao  Planos para quando será publicado ?

2022-10-15 01:39 UTC, LorhanSohaky commented
@pedrosancao , consegue atualizar o PR pra gente voltar a revisar?

2026-04-11 22:54 UTC, lucianopf commented
Olá @pedrosancao, calculadora de frete dos Correios é uma feature bastante pedida! Mas há bloqueadores significativos.

**Bloqueador 1: endpoint POST — BrasilAPI só usa GET**

O projeto tem uma restrição explícita: todos os endpoints devem usar o verbo HTTP **GET**. Um endpoint POST quebra esse princípio e o design geral da API.

Para cálculo de frete, os parâmetros poderiam ser query strings no GET:
```
GET /api/correios/v1/frete?servico=04014&cep_origem=01001000&cep_destino=20040020&peso=1&...
```

**Bloqueador 2: URL HTTP (não HTTPS)**

```js
url: 'http://ws.correios.com.br/calculador/CalcPrecoPrazo.asmx/...'
```

A comunicação com APIs externas deve ser via HTTPS. Além disso, esse webservice SOAP antigo dos Correios provavelmente foi descontinuado — os Correios lançaram APIs REST mais modernas.

**Bloqueador 3: Handler sem `app()` wrapper**

```js
// ❌
export default cors(shippingPrice);

// ✅
export default app().get(action);
```

**Outros problemas:**
- Nova dependência `Yup` quando `zod` já está no projeto para validação
- O PR está explicitamente incompleto (PR description lista tarefas pendentes: documentação, revisão, rebase)
- A response não usa as classes de erro do projeto (`BadRequestError`, etc.)
- A lógica `Object.getOwnPropertyNames(...).forEach(...)` não transforma os dados como esperado

Antes de prosseguir, vale verificar se a API REST mais nova dos Correios (https://viacep.com.br ou APIs REST dos Correios) oferece o cálculo de frete de forma pública e sem autenticação.

2026-08-07 22:45 UTC, lucianopf commented
Olá! Este PR está parado há mais de 2 anos sem atividade do autor, com mudanças solicitadas na revisão que não foram aplicadas (ou base muito desatualizada). Estamos fechando para limpar a fila, mas **sinta-se à vontade para reabrir** quando quiser retomar — basta rebasear na main e ajustar conforme as solicitações de review. 🙏

Se a feature ainda for desejada, um PR novo com base atualizada tem muito mais chance de aprovação.

2026-08-07 22:45 UTC, closed without merging