Endpoint listagem de municípios de um estado
BrasilAPI/BrasilAPI pull request #265
Opened 2021-03-02 01:28 UTC by reonardoleis

Criei uma nova endpoint (/api/municipios/v1/uf/[UF]) que acredito ser interessante para o projeto. Dado um UF é retornado a listagem de todos os municípios desse estado juntamente com o código IBGE do mesmo. Utilizo a API da Wikipedia para pegar esses dados, através da biblioteca wikijs.

2021-03-08 19:13 UTC, murilohns commented
Fala @reonardoleis, tudo certo?
Você pode adicionar testes para esse `endpoint` e adicioná-lo na docs também, por favor?

2021-03-13 16:19 UTC, pedrosancao requested changes
Gostei da solução, acho que precisa passar o ESLint para padronizar o estilo de código (tem algumas linhas em branco em excesso).
Para aprovar a PR é necessário criar os testes e atualizar a documentação.

2021-03-13 16:19 UTC, pedrosancao commented on pages/api/municipios/v1/uf/[uf].js
> +    const municipios = await getStateCities(CODIGOS_ESTADOS[uf], uf);
sugiro colocar `CODIGOS_ESTADOS` em `state-cities.js` e aqui passar apenas o parâmetro `uf`, para que `state-cities.js` não tenha uma dependência externa

2021-03-13 16:19 UTC, pedrosancao commented on package.json
> +    "wikijs": "^6.0.1"
Estamos travando a versão removendo o `^`, pois não sabemos quais dependências de fato usam versionamento semântico.

2021-03-15 23:53 UTC, reonardoleis commented on pages/api/municipios/v1/uf/[uf].js
> +    const municipios = await getStateCities(CODIGOS_ESTADOS[uf], uf);
Certo!

2021-03-15 23:53 UTC, reonardoleis commented on package.json
> +    "wikijs": "^6.0.1"
Ok! Faço as alterações durante essa semana e atualizo a PR :)

2021-03-17 15:42 UTC, reonardoleis commented on pages/api/municipios/v1/uf/[uf].js
> +    const municipios = await getStateCities(CODIGOS_ESTADOS[uf], uf);
Fiz as modificações e pushei pra branch. Passei o ESLint e não obtive nenhum erro no meu código. Troquei o CODIGOS_ESTADOS para o outro arquivo e adicionei documentação referente à essa nova endpoint.

2021-04-25 04:56 UTC, LorhanSohaky commented
Apliquei essas sugestões no PR #295

2022-02-17 03:25 UTC, LorhanSohaky commented
@reonardoleis , acredito que podemos fechar este PR. O que acha?

2022-05-28 22:57 UTC, closed without merging

2022-05-28 22:58 UTC, LorhanSohaky commented
Fechei, pois já foi implementado e já está em produção