feat/fipe
BrasilAPI/BrasilAPI pull request #301
Opened 2021-05-10 04:45 UTC by LorhanSohaky

API para pegar os dados da tabela fipe

2021-05-16 14:13 UTC, leoferreiralima reviewed
Ola tudo bem? Dei uma olhada no seu código e achei muito massa parabéns! Mas acredito que a algumas melhorias a serem feitas. 

A api de marcas de caminhões, carros e motos tem o código praticamente igual, acredito que seria interessante colocar todos eles em uma rota com o parametro de tipo de veiculo na url,
e fazer a escolha do serviço a ser chamado a partir desse parametro. Assim teriamos um arquivo só e reduziria  a duplicidade de código. Essa seria minha sugestão, mas se tiver alguma outra ideia para não repetir a mesma lógica nesses 3 arquivos fico a vontade para discutir.

Espero que meu review ajude!

2021-05-17 15:17 UTC, murilohns commented
@LorhanSohaky concordo com o comentário do @leoferreiralima 

o endpoint `/fipe/marcas/v1/:tipoVeiculo` está repetindo basicamente o mesmo código nos arquivos.

Sugestão: remover os arquivos "carros.js", "caminhoes.js" e "motos.js", e inserir um arquivo "[type].js" (pode ser outro nome), que contém uma lógica diferente de acordo com o `type` recebido, 

Acho que isso facilita o review e manutenção :)

2021-05-18 16:43 UTC, LorhanSohaky commented
@leoferreiralima , @murilohns  refatorei para o que vocês sugeriram!

2021-05-18 17:41 UTC, leoferreiralima approved these changes

2021-06-04 03:22 UTC, LorhanSohaky commented
@murilohns , o que acha?

2021-06-07 14:35 UTC, pedrosancao requested changes
Parabéns pelo trabalho! Pra mim é só fazer _squash_ (via `git rebase` ou `git reset`) e tá aprovado.

Apenas relembrando que apesar de o _squash_ poder ser feito durante o _merge_ por quem tem permissão, o autor tem mais conhecimento para escrever uma mensagem de _commit_ significativa com as informações necessárias.

2021-06-07 19:55 UTC, murilohns approved these changes

2021-06-07 19:56 UTC, murilohns commented
@LorhanSohaky tu pode adicionar a documentação desse endpoint nesse PR? assim que a docs estiver pronta fazemos o merge daí :)

2021-06-07 19:58 UTC, RodriAndreotti commented
> @LorhanSohaky tu pode adicionar a documentação desse endpoint nesse PR? assim que a docs estiver pronta fazemos o merge daí :)

Murilo, aquela questão da sugestão de alteração no formato na documentação não seria interessante para conciliar com esta nova?

2021-06-08 02:42 UTC, LorhanSohaky commented
> Parabéns pelo trabalho! Pra mim é só fazer _squash_ (via `git rebase` ou `git reset`) e tá aprovado.
> 
> Apenas relembrando que apesar de o _squash_ poder ser feito durante o _merge_ por quem tem permissão, o autor tem mais conhecimento para escrever uma mensagem de _commit_ significativa com as informações necessárias.

@pedrosancao , se eu fizer isso não atrapalha o code review? Se eu entendi corretamente teria de:
1- `git reset upstream/master`
2- `git commit`
3- `git push --force feature/fipe`

2021-06-08 02:43 UTC, LorhanSohaky commented
> @LorhanSohaky tu pode adicionar a documentação desse endpoint nesse PR? assim que a docs estiver pronta fazemos o merge daí :)

@murilohns , adicionei a documentação, mas tem um caso que não consegui documentar, que é a busca do preço de um carro com a tabela de referência inválida

2021-06-08 12:41 UTC, pedrosancao commented
> @pedrosancao , se eu fizer isso não atrapalha o code review? Se eu entendi corretamente teria de:
> 
>     1. `git reset upstream/master`
>     2. `git commit`
>     3. `git push --force feature/fipe`

Não afeta a revisão de código pois não tem mais comentários aparecendo em _Files changed_, todos foram resolvidos.
O comando 1 eu usaria `git reset --soft HEAD^15` apenas por preferência pessoal, gosto de usar comandos git bem explícitos.

E garantia antes do _push force_ eu olharia o gráfico com `git log --oneline --decorate --all --graph`.

2021-06-08 16:48 UTC, murilohns approved these changes

2021-06-08 16:51 UTC, merged