Fix non-breaking code smells
BrasilAPI/BrasilAPI pull request #311
Opened 2021-05-20 14:35 UTC by ferrarienz0

Fix all code smells identified by SonarCloud that doesn't interfere with the Next.js framework.

2021-05-20 14:39 UTC, murilohns approved these changes

2021-05-21 13:10 UTC, LorhanSohaky commented on package-lock.json
>  {
Sabe me dizer o motivo de ter mudado muita coisa no package-lock?

2021-05-21 13:57 UTC, ferrarienz0 commented on package-lock.json
>  {
Provavelmente estava usando uma versão do node diferente, o que acabou reescrevendo o lock

2021-05-21 14:01 UTC, murilohns commented on package-lock.json
>  {
@ferrarienz0 acho que é melhor tirar as alterações do package-lock :D

2021-05-21 14:06 UTC, ferrarienz0 commented on package-lock.json
>  {
@murilohns Feito ^^

2021-06-01 17:18 UTC, murilohns commented
@ferrarienz0, pode fazer rebase por favor?

Os testes estão quebrando e precisa ajeitar o import dos erros no arquivo de `pages/api/cnpj/v1/[cnpj].js`

Assim que corrigido podemos fazer o merge :)

2021-06-01 19:05 UTC, ferrarienz0 commented
> @ferrarienz0, pode fazer rebase por favor?
> 
> Os testes estão quebrando e precisa ajeitar o import dos erros no arquivo de `pages/api/cnpj/v1/[cnpj].js`
> 
> Assim que corrigido podemos fazer o merge :)

Dei o rebase =), não fiz alterações na parte dos testes que não está passando (IBGE), rodando localmente, vi que as requisições estão demorando muito, então suponho que o timeout está sendo levantado pelo próprio IBGE

2021-06-07 15:01 UTC, pedrosancao requested changes

2021-06-07 15:01 UTC, pedrosancao commented on services/cnpj.js
> +  const response = await axios.get(`https://minhareceita.org/${cnpj}`);
Ainda tem um [_code smell_](https://sonarcloud.io/project/issues?id=BrasilAPI_BrasilAPI&open=AXnIknYFne3tTsFwR9ec&resolved=false&types=CODE_SMELL) que pode ser resolvido com:

```js
export const getCnpjData = (cnpj) =>
  axios.get(`https://minhareceita.org/${cnpj}`);
```

2021-06-07 19:05 UTC, murilohns approved these changes

2021-06-07 19:06 UTC, merged