feat: automates updating the list of contributors
BrasilAPI/BrasilAPI pull request #314
Opened 2021-05-23 14:52 UTC by LorhanSohaky

2021-05-24 14:24 UTC, pedrosancao requested changes
O teste que está no link no [comentário na _issue_ 302](https://github.com/BrasilAPI/BrasilAPI/issues/302#issuecomment-846576453) duplicou a foto de várias pessoas e como cada imagem ocupa um bom espaço no readme gostaria de manter essa seção o mais enxuta possível, faz sentido? Seria melhor se pudesse filtrar, para manter os devidos destaques para os autores sem duplicar.

A _action_ separa colaboradores e contribuidores, mas no momento não fazemos essa distinção aqui. Ela também usa o nome das pessoas ao invés do usuário, o que tem mais chances de "quebrar" o layout da tabela, é possível configurar isso?

Importante também fazer "_squash_" dos _commits_ para manter o histórico mais limpo e o que tem sido solicitado em PRs anteriores.

2021-05-25 19:23 UTC, LorhanSohaky commented
Acho que o que você chama de duplicada é poq eu tinha mantido o readme antigo em baixo

2021-05-25 19:26 UTC, LorhanSohaky commented
Creio que o que ele chama de colaboradores são as pessoa da org que atuam diretamente no projeto

2021-05-25 19:26 UTC, LorhanSohaky commented
Sobre o squash do commit dá para eu fazer, mas também é possível na hora do merge

2021-05-25 19:31 UTC, LorhanSohaky commented
Sobre o ponto do nome de usuário eu abri uma issue para ver se é possível fazer isso

2021-05-25 19:54 UTC, pedrosancao commented
@LorhanSohaky algumas considerações:

> Acho que o que você chama de duplicada é poq eu tinha mantido o readme antigo em baixo

Vi que atualizou o exemplo, lá você removeu a seção "Autores" é algo que não acho legal de fazer, com a seção mantida vão aparecer fotos duplicadas, e isso acontece no exemplo onde a sua foto aparece duplicada.

> Creio que o que ele chama de colaboradores são as pessoa da org que atuam diretamente no projeto

No exemplo está separado você como Colaborador (no contexto do seu _fork_), que seria o equivalente à seção "Autores" existente, mas se usarmos o _placeholder_ para fazer a substituição o resultado vai ser diferente do que existe, e até pelo título da PR não acho que seja intenção alterar autores/colaboradores.

> Sobre o squash do commit dá para eu fazer, mas também é possível na hora do merge

Eu ainda prefiro que seja feito antes do _merge_, pois a pessoa que faz _merge_ geralmente não é o autor, e o autor tem mais conhecimento para criar uma mensagem de _commit_ com as informações necessárias.

---

PS: Por favor evite várias respostas seguidas, use a opção de editar. O GitHub envia e-mails para cada respostas (dependendo da configuração de cada um) e acaba gerando spam. Ontem mesmo uma pessoa [comentou](https://github.com/BrasilAPI/BrasilAPI/pull/285#issuecomment-847333494) pedindo para parar de receber os e-mails, é outro contexto mas é apenas um exemplo.

2021-05-27 00:43 UTC, LorhanSohaky commented
@pedrosancao , eu tinha separado para dar a noção de thread

2021-06-08 02:56 UTC, LorhanSohaky commented
Vou fechar esse PR em detrimento do PR #322

2021-06-08 02:56 UTC, closed without merging