Added new workflow ESlint
BrasilAPI/BrasilAPI pull request #318
Opened 2021-06-02 11:20 UTC by hotieall

Hi, I'm giving this pull request to create a new workflow for testing using ESlint.

**Suggestion:** Nowadays we shouldn't use the main branch with the name `master`, and rename it to `main`, if I'm not mistaken it was a change in linux terminology last year.

Sorry for two pulls I ended up doing something wrong in the previous request. But I would like to be contributing. #317

2021-06-02 18:28 UTC, pedrosancao commented
@hotieall não tenho certeza, mas parece que já existe um hook do git que já executa o eslint (via husky)

PS: Pode deixar a descrição em português, por favor?

2021-06-02 18:47 UTC, hotieall commented
> @hotieall não tenho certeza, mas parece que já existe um hook do git que já executa o eslint (via husky)
> 
> PS: Pode deixar a descrição em português, por favor?

sure!

2021-06-05 01:47 UTC, PauloGoncalvesBH requested changes

2021-06-05 01:47 UTC, PauloGoncalvesBH commented on .github/workflows/ESlint.yaml
> +        run: npm test
```suggestion
```

Os testes já são executados na pipeline `.github/workflows/e2e-tests.yml`. Remover esse trecho.

2021-06-05 01:47 UTC, PauloGoncalvesBH commented on .github/workflows/ESlint.yaml
> +            ${{ runner.os }}-node-
Qual a funcionalidade desse trecho?

2021-06-05 01:47 UTC, PauloGoncalvesBH commented on .github/workflows/ESlint.yaml
> +        run: npm install
```suggestion
        run: npm ci
```

O `npm ci` é o comando recomendado para executar instalação em pipeline. Realiza instalação limpa e garante que o `package-lock.json` está atualizado.

2021-06-05 01:47 UTC, PauloGoncalvesBH commented on .github/workflows/ESlint.yaml
> +      - v*
```suggestion
on:
  push:
    branches:
      - master
      - main
    pull_request:
```

Não vejo necessidade de limitar a execução do lint de tal maneira, o que acha de alterar para executar em todos os `pull_request` e em push na branch default?

Deixei `main` e `master` pois logo renomearemos a branch.

2021-06-05 01:47 UTC, PauloGoncalvesBH commented on .github/workflows/ESlint.yaml
> +  code:
```suggestion
  lint:
```

Esse nome me parece mais adequado.

2021-06-05 01:47 UTC, PauloGoncalvesBH commented on .github/workflows/ESlint.yaml
> +        uses: actions/setup-node@main
```suggestion
        uses: actions/setup-node@v1
```

É má prática não fixar versão.

2021-06-05 01:47 UTC, PauloGoncalvesBH commented on .github/workflows/ESlint.yaml
> +          node-version: ${{ matrix.node-version }}
Como executaremos apenas o lint nesse workflow não vejo sentido em utilizar matrix, mas sim focar em apenas uma versão LTS.

O workflow de testes E2E utiliza a versão 12.x, acredito que podemos ir pelo mesmo caminho.

2021-06-05 01:47 UTC, PauloGoncalvesBH commented on .github/workflows/ESlint.yaml
> +    name: Versões NodeJS
O `name` não parece que encaixa nesse contexto.

2021-06-05 01:47 UTC, PauloGoncalvesBH commented on .github/workflows/ESlint.yaml
> +        run: npm run fix
```suggestion
        run: npm run lint
```

O script `fix` executa o lint corrigindo os problemas encontrados, se executarmos ele na pipeline iremos mascarar os problemas existentes.

É preciso criar um novo script no package chamado (sugestão) `lint`, aonde vai executar o comando de `fix` sem o comando `--fix`.

Se possível renomear o `fix` para `lint:fix`.

2021-07-20 17:21 UTC, murilohns commented
@hotieall vamos olhar com mais calma esse PR
realmente precisamos mudar o nome da branch principal, mas acho que temos alguns hooks linkados na `master`, e trocar pra `main` pode quebrar alguma coisa

2021-09-24 04:53 UTC, LorhanSohaky commented
Existe, mas acho interessante ter um workflow que faz isso. Já vi máquinas Windows não executando o husky, aí o código vai para o ambiente sem seguir o estilo do projeto
> @hotieall não tenho certeza, mas parece que já existe um hook do git que já executa o eslint (via husky)
> 
> PS: Pode deixar a descrição em português, por favor?

2021-09-24 04:58 UTC, LorhanSohaky requested changes

2021-09-24 04:58 UTC, LorhanSohaky commented on .github/workflows/ESlint.yaml
> +      - main
Para funcionar com o que temos hoje será necessário deixar como master
```suggestion
      - master
```

2021-09-24 04:58 UTC, LorhanSohaky commented on .github/workflows/ESlint.yaml
> +        run: npm install
CI é o indicado para workflow
```suggestion
        run: npm ci
```

2021-09-24 04:58 UTC, LorhanSohaky commented on .github/workflows/ESlint.yaml
> +          - 15.x
O outro workflow utiliza a versão 12 do node, o que acha de manter o padrão?
```suggestion
          - 12.x
```

2021-09-24 04:58 UTC, LorhanSohaky commented on .github/workflows/ESlint.yaml
> +        uses: actions/setup-node@main
Qual a diferença desse para o `uses: actions/setup-node@v1`? Não conheço esse `@main`

2021-09-24 04:58 UTC, LorhanSohaky commented on .github/workflows/ESlint.yaml
> +        run: npm test
Já existe um workflow de teste, então acho que é desnecessário essa etapa

2021-11-22 13:37 UTC, closed without merging