Feature/readme contributors update
BrasilAPI/BrasilAPI pull request #322
Opened 2021-06-07 23:44 UTC by pedrosancao

Inspirado pela _issue_ #302 e pelo trabalho do Lorhan na PR #314 realizei a automação da atualização de contribuidores usando o script já existente no projeto.

Nessa PR a criei um `shell script` para obter a tabela atualizada de pessoas que contribuíram, identificar os marcadores de inicio e fim e substituir a tabela existente pela nova. Com isso atualizei também o script no npm, que agora passa a ser executado com `npm run contributors:update`.

Configurei também um _action_ do GitHub para automatizar o processo usando o script npm atualizado e a _action_ [_Add & Commit_](https://github.com/marketplace/actions/add-commit).

O _workflow_ está configurado para execução manual, pensei em colocar ao fazer _commit_ na ramificação principal mas em dias em que vários PRs são aprovados seria executado várias vezes, poluindo o histórico. Dessa forma as pessoas com acesso podem iniciar a execução manualmente ([artigo para saber mais](https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/)):
![workflow manual](https://user-images.githubusercontent.com/5047991/121098302-f0f7eb00-c7cb-11eb-8203-6cd85ed67195.png)

No meu _fork_ configurei a _action_ na ramificação "readme-contributors-update-post-commit". O log da execução de teste pode ser visto [aqui](https://github.com/pedrosancao/BrasilAPI/runs/2768888073?check_suite_focus=true) e o _commit_ criado automaticamente foi o [d1cb988](https://github.com/pedrosancao/BrasilAPI/commit/d1cb98809dc092b0db073eca996d2d536509fdc2).

---

### Testando

Infelizmente só é possível testar _actions_ do GitHub ao subir o arquivo yml na ramificação principal do repositório. Quem quiser ver o _workflow_ em ação pode configurar em seu próprio _fork_ com os comandos abaixo (executados na pasta local do fork):

```bash
git checkout master-bkp origin/master
git remote add pedrosancao https://github.com/pedrosancao/BrasilAPI.git
git fetch pedrosancao
git checkout pedrosancao/0307562
git push -f origin HEAD:master
```
Inicie a tarefa manualmente conforme a imagem acima.

Para restaurar seu _fork_ para o estado anterior execute `git push -f origin master-bkp:master && git checkout master`

2021-06-08 02:53 UTC, LorhanSohaky requested changes

2021-06-08 02:55 UTC, LorhanSohaky commented
@pedrosancao, achei muito massa!!! Fiquei curioso, seria possível fazer isso em js ou só com shell?

2021-06-08 11:50 UTC, pedrosancao commented
> @pedrosancao, achei muito massa!!! Fiquei curioso, seria possível fazer isso em js ou só com shell?

Possivel sempre é e a questão é a complexidade. Escolhi fazer com shell porque a manipulação de textos com `grep`, `head` e `tail` é bem simples. As soluções que imagino com js provavelmente usaria expressões regulares e é uma complexidade que não gostaria de adicionar.

2021-06-08 13:08 UTC, pedrosancao commented on .github/workflows/update-contributors.yml
> +
Eu entendi o ganho em fazer essa configuração e acho a sugestão muito válida, mas na [documentação do Husky](https://typicode.github.io/husky/#/?id=breaking-changes) tem uma _Breaking change_ dizendo que esse parâmetro foi removido, lá não consta em qual versão isso aconteceu 😞. Não fico muito confortável em adicionar essa configuração que de certa forma bloqueia a futura atualização do Husky.

A _action_ está configurada para adicionar com `git add` apenas o `README.md` e pelo que entendi o Husky usa apenas os arquivos no _stage_ do git para rodar o hook, dessa forma acredito que o impacto no husky no `pipeline` está na faixa de milissegundos e algo que não precisamos nos preocupar.

O que vocês acham?

2021-06-08 16:12 UTC, LorhanSohaky commented on .github/workflows/update-contributors.yml
> +
Entendi... A versão que estamos usando é a 4.x, essa breaking change deve ser na 6.y

O pior é que eu precisei disso em outro projeto, só não lembro se demorava muito para o husky configurar os hooks do git ou se era na instalação mesmo do husky

2021-06-25 14:37 UTC, LorhanSohaky approved these changes

2022-07-07 15:48 UTC, hebertcisco approved these changes

2022-07-07 15:59 UTC, murilohns commented
Nós trocamos o readme, e agora ele atualiza automaticamente os contribuidores.

2022-07-07 15:59 UTC, closed without merging