Separa documentação em arquivos individuais para cada módulo
BrasilAPI/BrasilAPI pull request #325
Opened 2021-06-09 22:59 UTC by RodriAndreotti

Este PR separa a estrutura da documentação, que atualmente é monolítica, em arquivos individuais para cada módulo.

Esta mudança seria interessante para simplificar a criação de nova documentação ou alteração de uma existente.
Também visa evitar conflitos em decorrência de versões diferentes da documentação, visto que cada contribuidor alterará um arquivo separado.

Issue relacionada: https://github.com/BrasilAPI/BrasilAPI/issues/324
PR com alterações na documentação: https://github.com/BrasilAPI/BrasilAPI/pull/306

Este PR contém todas a modificações realizadas no PR acima, porém modularizado.

2021-06-10 12:15 UTC, LorhanSohaky commented on next.config.js
> +module.exports = {
Por curiosidade, para que servem essas alterções de webpack?

2021-06-10 13:07 UTC, RodriAndreotti commented on next.config.js
> +module.exports = {
Opa... bom dia!
Elas são utilizadas, primeiro, para que:
1º - O next utilize o webpack5, em vez do 4
```
future: {
     webpack5: true
  },
```
Depois para fazer que o Webpack ignore o módulo fs do node no bundle do cliente (o que faria dar um erro na build)
```
  webpack: (config, { isServer }) => {
    if (!isServer) {
      /* eslint-disable no-param-reassign */
      config.resolve.fallback.fs = false;
      /* eslint-enable no-param-reassign */
    }
    return config;
  },
```

2021-06-23 03:01 UTC, LorhanSohaky submitted a review, later dismissed

2021-06-23 12:07 UTC, murilohns requested changes

2021-06-23 12:07 UTC, murilohns commented on CONTRIBUTING.md
> +Se possíve, além do endpoint crie também a documentação para o mesmo, utilizamos uma implementação básica da [OpenAPI 3.0](https://swagger.io/docs/specification/about/) em **json**.
```suggestion
Se possível, além do endpoint crie também a documentação para o mesmo, utilizamos uma implementação básica da [OpenAPI 3.0](https://swagger.io/docs/specification/about/) em **json**. 
```

2021-06-23 12:07 UTC, murilohns commented on CONTRIBUTING.md
> +Para mensagens de erro utilize o schema pré-existente `ErrorMessage`
🎉

2021-06-23 12:07 UTC, murilohns commented on pages/docs/doc/cep.json
> +        "/cep/v2/{cep}": {
Aqui tá faltando os dados de coordenadas, consegue adicionar?

2021-06-23 13:19 UTC, RodriAndreotti commented on pages/docs/doc/cep.json
> +        "/cep/v2/{cep}": {
Opa... consigo sim, @murilohns !
Vou verificar a resposta do endpoint e adiciono, como eu só fui separando os retornos que já existiam, isso deve ter passado batido

2021-06-25 14:35 UTC, LorhanSohaky requested changes

2021-06-25 14:35 UTC, LorhanSohaky commented on pages/docs/doc/cep.json
> +                "required": ["cep", "state", "city", "neighborhood", "street", "string"],
```suggestion
                "required": ["cep", "state", "city", "neighborhood", "street", "service"],
```

2021-06-25 14:36 UTC, RodriAndreotti commented on pages/docs/doc/cep.json
> +                "required": ["cep", "state", "city", "neighborhood", "street", "string"],
Mas que?
Como eu fiz isso? Devia estar com sono... kkk

2021-06-25 15:19 UTC, LorhanSohaky approved these changes

2021-06-25 15:19 UTC, LorhanSohaky commented on pages/docs/doc/cep.json
> +                "required": ["cep", "state", "city", "neighborhood", "street", "string"],
hahahaha acontece

2021-07-20 16:10 UTC, murilohns approved these changes

2021-07-20 16:10 UTC, merged