Criando endpoint para obter algumas taxas (Selic, CDI e IPCA)
BrasilAPI/BrasilAPI pull request #357
Opened 2021-11-10 16:19 UTC by yardz

Então eu encontrei esse pacote: https://www.npmjs.com/package/selic?fbclid=IwAR0k3oLFeEZykbEO82OFb4xF4O0i3rCgL7M6iqlGdM9AUD-oVi36vbGwgfQ

Ele faz o scrap de algumas taxas (atualmente, apenas Selic, IPCA e CDI. Quando vi o pacote pensei, poxa, é uma informação bem legal pra BrasilAPI né... Então, separei alguns minutos e fiz esse endpoint.

São 2 endpoints `GET /api/taxas/v1` e `/api/taxas/v1/{nome-da-taxa}`.

2021-11-14 11:23 UTC, LorhanSohaky requested changes
Achei interessante! Uma dúvida... É possível pegar um valor histórico da selic? por exemplo selic de 10/10/2020

2021-11-14 11:23 UTC, LorhanSohaky commented on package.json
> +    "selic": "^0.1.5",
O padrão do projeto é deixa pinada a versão
```suggestion
    "selic": "0.1.5",
```

2021-11-16 06:11 UTC, yardz commented
> Achei interessante! Uma dúvida... É possível pegar um valor histórico da selic? por exemplo selic de 10/10/2020

Não com esse pacote... Ele apenas faz o fetch e pega os dados. Talvez até exista alguma api/serviço que forneça isso porem eu não conheço.

Realmente seria muito legal conseguir pesquisar a taxa em uma data específica. Acredito que isso seria uma melhoria bem legal pra esse endpoint :-D

2021-11-17 19:55 UTC, yardz commented
@LorhanSohaky não esquece do PR não kkkkk

2021-11-18 10:29 UTC, LorhanSohaky reviewed
Uma coisa que acho importante entender é como vc está pensando o caso de uso dessa API. É para as pessoas verem o valor apenas uma vez ao dia ou a todo instante fazer uma requisição para verificar?

2021-11-18 10:29 UTC, LorhanSohaky commented on pages/api/taxas/v1/[sigla].js
> +  response.json({ nome: item.name, valor: item.apy });
Só dúvida se não precisa dar um return aqui
```suggestion
  return response.json({ nome: item.name, valor: item.apy });
```

2021-11-18 10:29 UTC, LorhanSohaky commented on pages/api/taxas/v1/index.js
> +  response.json(taxas.map((taxa) => ({ nome: taxa.name, valor: taxa.apy })));
```suggestion
  return response.json(taxas.map((taxa) => ({ nome: taxa.name, valor: taxa.apy })));
```

2021-11-18 10:46 UTC, RodriAndreotti commented
> Uma coisa que acho importante entender é como vc está pensando o caso de uso dessa API. É para as pessoas verem o valor apenas uma vez ao dia ou a todo instante fazer uma requisição para verificar?

Acho que isso consigo tentar ajudar na sua dúvida, @LorhanSohaky .
Até onde sei as taxas selic, ipca e cdi não se alteram durante o dia, são dia a dia, se observar no site do Bacen, vc terá a taxa dia a dia. 

Aliás, a SELIC é uma previsão anual, então se vc olhar no Bacen (https://www.bcb.gov.br/estabilidadefinanceira/selicdadosdiarios) verá que todos os dias é a mesma taxa, só muda quando tem reunião do copon, se não me engano a cada 2 ou 3 meses.
A CDI geralmente acompanha a SELIC, então segue a mesma lógica.
A única que tem variação mensal é a IPCA (https://www.ibge.gov.br/explica/inflacao.php)

Então imagino que esta consulta seja feita uma vez ao dia, ou até com frequência menor, por cada usuário da API.

2021-11-18 10:51 UTC, LorhanSohaky commented
> 
> 
> > Uma coisa que acho importante entender é como vc está pensando o caso de uso dessa API. É para as pessoas verem o valor apenas uma vez ao dia ou a todo instante fazer uma requisição para verificar?
> 
> Acho que isso consigo tentar ajudar na sua dúvida, @LorhanSohaky . Até onde sei as taxas selic, ipca e cdi não se alteram durante o dia, são dia a dia, se observar no site do Bacen, vc terá a taxa dia a dia.
> 
> Aliás, a SELIC é uma previsão anual, então se vc olhar no Bacen (https://www.bcb.gov.br/estabilidadefinanceira/selicdadosdiarios) verá que todos os dias é a mesma taxa, só muda quando tem reunião do copon, se não me engano a cada 2 ou 3 meses. A CDI geralmente acompanha a SELIC, então segue a mesma lógica. A única que tem variação mensal é a IPCA (https://www.ibge.gov.br/explica/inflacao.php)
> 
> Então imagino que esta consulta seja feita uma vez ao dia, ou até com frequência menor, por cada usuário da API.

Aaa show! É que se fosse algo que mudasse com mais constância teria que mudar o valor de cache e ver se faria sentido mesmo, senão as pessoas tomariam block da cloud flare

2021-11-18 12:20 UTC, RodriAndreotti commented
> > > Uma coisa que acho importante entender é como vc está pensando o caso de uso dessa API. É para as pessoas verem o valor apenas uma vez ao dia ou a todo instante fazer uma requisição para verificar?
> > 
> > 
> > Acho que isso consigo tentar ajudar na sua dúvida, @LorhanSohaky . Até onde sei as taxas selic, ipca e cdi não se alteram durante o dia, são dia a dia, se observar no site do Bacen, vc terá a taxa dia a dia.
> > Aliás, a SELIC é uma previsão anual, então se vc olhar no Bacen (https://www.bcb.gov.br/estabilidadefinanceira/selicdadosdiarios) verá que todos os dias é a mesma taxa, só muda quando tem reunião do copon, se não me engano a cada 2 ou 3 meses. A CDI geralmente acompanha a SELIC, então segue a mesma lógica. A única que tem variação mensal é a IPCA (https://www.ibge.gov.br/explica/inflacao.php)
> > Então imagino que esta consulta seja feita uma vez ao dia, ou até com frequência menor, por cada usuário da API.
> 
> Aaa show! É que se fosse algo que mudasse com mais constância teria que mudar o valor de cache e ver se faria sentido mesmo, senão as pessoas tomariam block da cloud flare

Saquei, é uma taxa um pouco menos volátil, se fosse cotação de dólar, por exemplo, seria mais complicado.

2021-11-18 12:48 UTC, yardz commented on pages/api/taxas/v1/[sigla].js
> +  response.json({ nome: item.name, valor: item.apy });
Não precisa de return. Request é um callback…

2021-11-18 12:50 UTC, yardz commented on pages/api/taxas/v1/index.js
> +  response.json(taxas.map((taxa) => ({ nome: taxa.name, valor: taxa.apy })));
Mesma coisa. Também não precisa de return…

Pode colocar (embora não vá fazer nada), mas eu copiei o mesmo padrão de outro endpoint, e nele o autor não colocou return.

2021-11-19 11:51 UTC, LorhanSohaky approved these changes

2021-11-23 17:24 UTC, lucianopf approved these changes
:heart: :rocket:

2021-11-23 17:24 UTC, lucianopf commented on pages/api/taxas/v1/[sigla].js
> +  response.json({ nome: item.name, valor: item.apy });
Curto bastante return aliado a response mesmo sendo callback tbm, mas não acho que é um blocker pro PR não!

2022-06-09 12:56 UTC, epcgrs approved these changes

2022-06-10 12:51 UTC, yardz commented
Pessoal, esse PR já está aberto a meses. Seria interessante fazerem o merge logo né... Meio chato o descaso :/

2022-06-10 12:56 UTC, epcgrs commented
@murilohns essa feature é bem interessante pro projeto, está pendente apenas o seu review.

2022-06-10 13:01 UTC, merged