refactor: update selic to v1.0.0
BrasilAPI/BrasilAPI pull request #406
Opened 2022-06-26 20:49 UTC by caio-ribeiro-pereira

Atualização do módulo `selic` para versão 1.0.0

2022-07-04 11:44 UTC, murilohns approved these changes

2022-07-07 00:06 UTC, LorhanSohaky requested changes
Só corrigiria o package-lock para manter na v1

2022-07-13 00:20 UTC, LorhanSohaky commented on pages/api/taxas/v1/index.js
> +const action = async (_request, response) => {
Entendi. Do request está tudo bem, só sobre o package-lock que é importante manter na V1. Você pode instalar uma versão um pouco mais antiga `npx npm@6.14.17 i --save`

2022-07-13 00:32 UTC, caio-ribeiro-pereira commented on pages/api/taxas/v1/index.js
> +const action = async (_request, response) => {
Blz, modificarei em breve, mas por curiosidade pq necessita manter v1 do package.json? Pois o próprio Sonar deu problema quando subi do jeito antigo

2022-07-13 17:27 UTC, LorhanSohaky commented on pages/api/taxas/v1/index.js
> +const action = async (_request, response) => {
É que seu PR contém alterações simples e que não estão diretamente ligadas ao package-lock. Quando o package-lock é modificado pode ser que ele atualize alguma dependência ou sub dependência, então nessas situações temos que olhar com mais atenção. Além disso, ao alterar o package-lock gerará conflito em todos so PRs abertos. Então as outras pessoas terão fazer rebase ou excluir o arquivo e instalar novamente

2022-07-13 18:12 UTC, murilohns commented
@caio-ribeiro-pereira fiz um Push no teu PR pra corrigir o `package-json`

Acontece que hoje fazemos o build do projeto na versão 12 do Node, e quando você deu o `npm install`, provavelmente estava na versão >= 14, então atualizou pra versão 2 do package-json.

Fiz um push na tua branch corrigindo isso, o resto tá certinho :)

Inclusive já está com meu Approve.

2022-07-13 18:21 UTC, LorhanSohaky approved these changes

2022-07-13 18:21 UTC, caio-ribeiro-pereira commented
Obrigado pelo help @murilohns pois de fato, eu iria demorar fazer essa correção devido as correrias aqui!

2022-07-13 18:26 UTC, murilohns approved these changes

2022-07-13 18:27 UTC, merged