feat: adiciona sexta-feira santa aos feriados nacionais
BrasilAPI/BrasilAPI pull request #408
Opened 2022-07-05 03:57 UTC by RenatoBrunetti

A implementação adiciona o feriado de sexta-feira santa a lista de feriados nacionais e que atende a [issue](https://github.com/BrasilAPI/BrasilAPI/issues/403).

2022-07-05 10:58 UTC, murilohns requested changes
Nenhum pacote foi adicionado, removido, ou alterado. Então tem necessidade de alterar o `package.json`.

Você consegue remover essa alteração, @RenatoBrunetti?

Fora isso tá aprovado!

2022-07-05 12:27 UTC, RenatoBrunetti commented
> Nenhum pacote foi adicionado, removido, ou alterado. Então tem necessidade de alterar o `package.json`.
> 
> Você consegue remover essa alteração, @RenatoBrunetti?
> 
> Fora isso tá aprovado!

Bom dia, claro amigo.
Já fiz a correção, obrigado pelo suporte. ;)

2022-07-05 12:29 UTC, murilohns approved these changes

2022-07-06 23:47 UTC, LorhanSohaky approved these changes
Aprovado! Só acharia interessante se tiver um provedor de dados com essas informações atualizadas para que não tenhamos a responsabilidade de adicionar novas datas ou remover algumas

2022-07-07 12:53 UTC, merged