feat: get ncm codes from list
BrasilAPI/BrasilAPI pull request #415
Opened 2022-08-18 22:21 UTC by reinaldoacdc

## O que é a tabela NCM

A tabela NCM (Nomeclatura Comum do Mercosul) é usada para identificar os produtos comercializados dentro do bloco econômico de acordo com sua natureza.

Fonte:
https://www.gov.br/receitafederal/pt-br/assuntos/aduana-e-comercio-exterior/classificacao-fiscal-de-mercadorias/ncm

## Como realizar a consulta 

A pesquisa pode ser feito tanto pela descrição da naturezado produto: `/api/ncm/v1?search=Xampus ` 
Como pelo código ncm: `/api/ncm/v1?search=33051000` 

Também é possível listar os itens por capitulo e posição (2 e 4 primeiros digitos do código): `/api/ncm/v1?search=3505` 
devolvendo uma listagem com todos seus respectivos itens.

2022-09-05 19:25 UTC, conradoojr submitted a review, later dismissed

2022-09-05 23:52 UTC, LorhanSohaky requested changes
Muito massa seu PR!!! Deixei algumas sugestões de melhorias, pff veja se faz sentido.

Se quiser ir além você pode modificar os arquivos `pages/sitemap.xml/index.jsx` e `pages/index.js` para que a API que você desenvolveu seja indexada pelos buscadores

2022-09-05 23:52 UTC, LorhanSohaky commented on tests/ncm-v1.test.js
> +    test('Utilizando um código inexistente: 00', async () => {
Se o código não existe não deveria retornar um erro? Um 404 talvez

2022-09-05 23:52 UTC, LorhanSohaky commented on tests/ncm-v1.test.js
> +      const requestUrl = `${global.SERVER_URL}/api/ncm/v1?search=localhost`;
Se a descrição não existe será que deveria retornar 404?

2022-09-05 23:52 UTC, LorhanSohaky commented on tests/ncm-v1.test.js
> +        expect(response.data).toMatchObject([]);
Faz sentido essas verificações estarem dentro do catch?

2022-09-05 23:52 UTC, LorhanSohaky commented on tests/ncm-v1.test.js
> +        expect(response.data).toMatchObject([]);
Faz sentido essas verificações estarem dentro do catch?

2022-09-05 23:52 UTC, LorhanSohaky commented on pages/api/ncm/v1/[code].js
> +  response.json(ncmData);
Minha sugestão é que você parsei a data para colocar no formato `Date` e colocar os dados em camel_case com todas as letras em minúsculo. Assim ficará bem próximo do padrão das demais rotas.

2022-09-05 23:52 UTC, LorhanSohaky commented on pages/api/ncm/v1/index.js
> +  response.json(ncmData);
Minha sugestão é que você parsei a data para colocar no formato `Date` e colocar os dados em camel_case com todas as letras em minúsculo. Assim ficará bem próximo do padrão das demais rotas.

2022-10-02 02:15 UTC, LorhanSohaky commented
@reinaldoacdc , ficou muito bom! Eu ia aprovar mas lembrei só agora. Nós temos uma página de documentação da API. Você poderia adicionar a documentação? Logo em seguida eu já aprovo

2022-10-03 16:37 UTC, LorhanSohaky approved these changes
🚀

2022-10-10 13:56 UTC, murilohns approved these changes

2022-10-11 03:49 UTC, merged

2022-10-11 03:49 UTC, LorhanSohaky commented
@reinaldoacdc, muito obrigado pela contribuição!! 👏 🚀 🎉