feat: Novo endpoint para busca de livros publicados no Brasil pelo ISBN
BrasilAPI/BrasilAPI pull request #421
Opened 2022-09-12 21:30 UTC by alessandrojean

Este PR adiciona um novo endpoint na API para a busca de informações de livros publicados no Brasil a partir do ISBN.

O endpoint suporta a busca em 4 principais provedores:
- [CBL (Câmara Brasileira do Livro)](https://www.cblservicos.org.br/isbn/): Agência brasileira do ISBN.
- [MercadoEditorial.org](https://mercadoeditorial.org/): Banco de dados aberto sobre metadados de livros.
- [Open Library](https://openlibrary.org/): Banco de dados aberto de livros criado pelo pessoal do Internet Archive.
- [Google Books](https://books.google.com.br/): Informações de ebooks e livros físicos catalogados e vendidos pelo Google.

Apesar dos provedores Open Library e Google Books suportarem a busca de livros publicados em outros países, acredito que permitir a busca deles iria fugir um pouco do escopo do projeto, então juntamente a validação do código ISBN é verificado se o mesmo é emitido aqui no Brasil (prefixo `65` ou `85`).

Por conta das informações de livros serem raramente alteradas nos banco de dados dos provedores (talvez somente com exceção aos abertos a edição do público geral), as respostas possuem o cache configurado pela header.

Nos exemplos da documentação da API e nos testes eu tomei a liberdade de escolher alguns livros específicos, mas estes podem ser alterados para outros se for necessário, só me avisar.

Esta é a minha primeira contribuição para o projeto, então quaisquer sugestões de melhorias são bem-vindas :)

2022-10-11 03:48 UTC, LorhanSohaky requested changes
Muito bom esse seu PR!!! Deixei algumas sugestões de melhorias, pff veja se fazem sentido.

Se quiser ir além você pode modificar os arquivos `pages/sitemap.xml/index.jsx` e `pages/index.js` para que a API que você desenvolveu seja indexada pelos buscadores. Isso trará mais pessoas usando a rota que você desenvolveu e possivelmente mais contribuidores!

2022-10-11 03:48 UTC, LorhanSohaky commented on pages/docs/doc/isbn.json
> +                        "enum": ["CBL", "MERCADO_EDITORIAL", "OPEN_LIBRARY", "GOOGLE_BOOKS"]
O que acha do formato dos providers serem iguais ao que foi passado pela URL? Creio que assim simplifique para o usuário

2022-10-11 03:48 UTC, LorhanSohaky commented on pages/api/isbn/v1/[isbn].js
> +  'max-age=0, s-maxage=86400, stale-while-revalidate, public';
O próprio app já tem o cache configurado, então imagino que você não precise disso
https://github.com/BrasilAPI/BrasilAPI/blob/main/app.js#L15

2022-10-11 03:48 UTC, LorhanSohaky commented on pages/api/isbn/v1/[isbn].js
> +    response.setHeader('Cache-Control', CACHE_CONTROL_HEADER_VALUE);
```suggestion
```

2022-10-11 03:48 UTC, LorhanSohaky commented on services/isbn/cbl.js
> +export default async function cblSearch(isbn) {
```suggestion
export default async function searchInCbl(isbn) {
```

2022-10-11 03:48 UTC, LorhanSohaky commented on services/isbn/cbl.js
> +    provider: 'CBL',
```suggestion
    provider: 'cbl',
```

2022-10-11 03:48 UTC, LorhanSohaky commented on services/isbn/googleBooks.js
> +export default async function googleBooksSearch(isbn) {
```suggestion
export default async function searchInGoogleBooks(isbn) {
```

2022-10-11 03:48 UTC, LorhanSohaky commented on services/isbn/googleBooks.js
> +    provider: 'GOOGLE_BOOKS',
```suggestion
    provider: 'google-books',
```

2022-10-11 03:48 UTC, LorhanSohaky commented on services/isbn/mercadoEditorial.js
> +export default async function mercadoEditorialSearch(isbn) {
```suggestion
export default async function searchInMercadoEditorial(isbn) {
```

2022-10-11 03:48 UTC, LorhanSohaky commented on services/isbn/mercadoEditorial.js
> +    provider: 'MERCADO_EDITORIAL',
```suggestion
    provider: 'mercado-editorial',
```

2022-10-11 03:48 UTC, LorhanSohaky commented on services/isbn/openLibrary.js
> +export default async function openLibrarySearch(isbn) {
```suggestion
export default async function searchInOpenLibrary(isbn) {
```

2022-10-11 03:48 UTC, LorhanSohaky commented on services/isbn/openLibrary.js
> +    provider: 'OPEN_LIBRARY',
```suggestion
    provider: 'open-library',
```

2022-10-11 03:48 UTC, LorhanSohaky commented on tests/isbn-v1.test.js
> +      })
O que acha de validar os outros campos também? Assim saberemos se no futuro ocorrerá algum erro no parseamento dos demais campos

2022-10-11 03:48 UTC, LorhanSohaky commented on tests/isbn-v1.test.js
> +      })
Mesmo ponto sobre validação dos demais campos

2022-10-11 03:48 UTC, LorhanSohaky commented on tests/isbn-v1.test.js
> +      })
Mesmo ponto sobre validação dos demais campos

2022-10-11 03:48 UTC, LorhanSohaky commented on tests/isbn-v1.test.js
> +    );
Mesmo ponto sobre validação dos demais campos

2022-10-11 03:48 UTC, LorhanSohaky commented on tests/isbn-v1.test.js
> +    );
Mesmo ponto sobre validação dos demais campos

2022-10-11 03:48 UTC, LorhanSohaky commented on tests/isbn-v1.test.js
> +});
É possível criar um caso de teste para o 404?

2022-10-11 21:34 UTC, alessandrojean commented
Oi, @LorhanSohaky. Eu atualizei o código para aplicar as sugestões do seu review :)

Só fiquei um pouco em dúvida quanto ao teste geral (no caso em que o provedor mais rápido é o retornado) já que os dados podem diferir entre eles, mas acredito que como cada provedor é testado individualmente não deve ser tanto um problema.

Se precisar que mais alguma coisa seja alterada, só me avisar :)

2022-10-12 00:15 UTC, alessandrojean commented
Acredito estar tudo certo agora, os testes estão passando 👍🏻.

Tive uma certa dificuldade, pois aparentemente a API do Google Books retorna alguns valores diferentes dependendo do IP de origem, mas acredito que consegui fazer os testes lidarem com isso e não falharem independente do país ou território onde os testes estão sendo executados.

Consultei a [documentação](https://developers.google.com/books/docs/v1/using#st_params) e infelizmente não tem como forçar a API a exibir resultados como estando em um determinado país. Testei no preview da Vercel agora para esse PR e parece que as chamadas lá também estão sendo feitas com um IP internacional, o que acaba limitando o acesso a algumas informações como o preço de venda, mas se eventualmente um dia o IP utilizado passe a ser brasileiro, o endpoint já estará pronto para tratar estes dados 👍🏻.

Eu fiz vários commits para arrumar os testes até achar e corrigir tudo que estava errado, então já peço desculpas se o GitHub enviou vários e-mails de notificações sobre isso, haha.

2022-10-12 20:30 UTC, LorhanSohaky commented
> 

Show de bola! Antes de eu revisar só uma coisa que me veio agora. Será que se você passar os headers de `accept-language` e / ou `accept-encoding` isso não é resolvido?

![image](https://user-images.githubusercontent.com/16273730/195441594-b0cc76e9-a3ad-4a89-b242-c905adc9ed24.png)

2022-10-12 21:07 UTC, alessandrojean commented
@LorhanSohaky, eu testei o `Accept-Language` antes, mas não funcionou infelizmente. Porém, eu resolvi dar uma busca a mais agora para ter certeza e [descobri](https://stackoverflow.com/a/15601925) que tem um parâmetro `country` não documentado que se eu passar `country=BR` ele retorna os valores de venda e as outras informações de cá sempre, testei até numa VPN para confirmar. Vou submeter um commit para adicionar esse parâmetro em alguns instantes :)

2022-10-12 21:18 UTC, alessandrojean commented
Pronto, tudo nos conformes agora, pode revisar novamente quando puder :)

2022-10-15 01:24 UTC, LorhanSohaky approved these changes
@alessandrojean , ficou sensacional!!!!

2022-10-18 10:27 UTC, murilohns approved these changes

2022-10-18 11:04 UTC, merged