Spell correction on homepage
BrasilAPI/BrasilAPI pull request #472
Opened 2023-02-22 22:12 UTC by Skaylan

A small spell correction on index page.

2023-02-23 22:43 UTC, RodriAndreotti submitted a review, later dismissed

2023-02-25 12:44 UTC, LorhanSohaky approved these changes

2023-02-28 01:04 UTC, LorhanSohaky requested changes
Na página está tudo certo. Será que consegue aplicar as mesmas correções no README?

2023-03-08 11:08 UTC, Skaylan commented
@LorhanSohaky adicionei as alterações no README

2023-03-09 01:23 UTC, LorhanSohaky approved these changes

2023-03-09 01:34 UTC, RodriAndreotti reviewed
Deixei algumas sugestões, vejam se faz sentido

2023-03-09 01:34 UTC, RodriAndreotti commented on README.md
> +O BrasilAPI é uma iniciativa feita de brasileiros para brasileiros, por favor, não abuse deste serviço. Estamos em beta e ainda elaborando os Termos de Uso, mas por enquanto por favor não utilize for
Aqui neste trecho acredito que a "," não caiba:
> Brasil estava revalidando, todos os ceps

Eu mudaria para:

> Brasil estava revalidando todos os ceps

E neste trecho:

> E para consultas com um alto volume automatizado, iremos mais para frente fornecer alguma solução, como por exemplo, conseguir fazer o download de toda a base de ceps em uma única request.

Será que da seguinte forma ficaria um pouco melhor?
> E para consultas com um alto volume automatizado iremos, mais para frente, fornecer alguma solução, como conseguir fazer o download de toda a base de ceps em uma única request.

Como e por exemplo na mesma frase acaba sendo um pouco de pleonasmo :-P

Vejam se concordam com a sugestão ;-)

2023-03-09 01:34 UTC, RodriAndreotti commented on pages/index.js
> +          Um exemplo prático disso foi quando um dos maiores provedores de telefonia do Brasil estava validando todos os CEPs (de 00000000 até 99999999) e ultrapassando em cinco vezes o limite atual
Acredito que as mesmas observações acima

2023-03-09 18:31 UTC, Skaylan commented on pages/index.js
> +          Um exemplo prático disso foi quando um dos maiores provedores de telefonia do Brasil estava validando todos os CEPs (de 00000000 até 99999999) e ultrapassando em cinco vezes o limite atual
opa, eu dei uma revisada no acordo ortográfico e em algumas regras do português, e também com a  ajuda de algumas ferramentas de correção de texto, cheguei nessa versão:

 "Um exemplo prático disso foi quando um dos maiores provedores de telefonia do Brasil estava validando novamente todos os CEPs (de 00000000 até 99999999) e ultrapassando em cinco vezes o limite atual da nossa conta no servidor. O volume de consultas deve ter a natureza de uma pessoa real requisitando um determinado dado. Para consultas com um alto volume automatizado, forneceremos posteriormente alguma solução, como, por exemplo, permitir o download de toda a base de CEPs em uma única requisição."

Eu acredito que não há pleonasmo já que não ocorre a repetição de uma mesma ideia, são dois exemplos objetivos diferentes.

o que acha?

2023-03-09 22:07 UTC, RodriAndreotti commented on pages/index.js
> +          Um exemplo prático disso foi quando um dos maiores provedores de telefonia do Brasil estava validando todos os CEPs (de 00000000 até 99999999) e ultrapassando em cinco vezes o limite atual
Opa... Curti, estava lendo aqui novamente a questão do como, por exemplo, e parece que é aceito quando há o intuito de adoro da frase, como acredito que seja nosso caso (essa conversa está se tornando digna de um convite ao Pasquale...kkk)
O que vc acha dessa vírgula nessa posição:

> Para consultas com um alto volume automatizado, forneceremos...
Para mim a frase ficaria bem sem ela, pois o conteúdo seguinte ainda dá a continuidade do texto anterior.

Mas fique a vontade para discordar :-P

2023-03-10 11:18 UTC, kaiosilveira commented on README.md
> +O BrasilAPI é uma iniciativa feita de brasileiros para brasileiros, por favor, não abuse deste serviço. Estamos em beta e ainda elaborando os Termos de Uso, mas por enquanto por favor não utilize for
Olá @Skaylan, como está?
Abri ontem [um PR](https://github.com/BrasilAPI/BrasilAPI/pull/478) para corrigir um pequeno erro de concordância exatamente nesse trecho que alterou. Se importaria de incorporar minha mudança como parte do seu PR? Assim eu poderia descartar meu PR e deixamos centralizadas aqui as mudanças nessa parte do código. 🤔 (detalhe, a mesma mudança teria que ser feita, também, em `pages/index.js`)

2023-03-10 11:32 UTC, Skaylan commented on pages/index.js
> +          Um exemplo prático disso foi quando um dos maiores provedores de telefonia do Brasil estava validando todos os CEPs (de 00000000 até 99999999) e ultrapassando em cinco vezes o limite atual
sim, fica bem sem a virgula, vou realizar as alterações no readme e na index.

2023-03-10 11:44 UTC, Skaylan commented on README.md
> +O BrasilAPI é uma iniciativa feita de brasileiros para brasileiros, por favor, não abuse deste serviço. Estamos em beta e ainda elaborando os Termos de Uso, mas por enquanto por favor não utilize for
Sim, eu irei realizar as alterações que eu e o @RodriAndreotti estávamos discutindo, acredito que as mudanças englobam as as alterações feita no seu PR

2023-03-10 11:47 UTC, kaiosilveira commented on README.md
> +O BrasilAPI é uma iniciativa feita de brasileiros para brasileiros, por favor, não abuse deste serviço. Estamos em beta e ainda elaborando os Termos de Uso, mas por enquanto por favor não utilize for
Top 💯 
Fecharei meu PR então. Obrigado!

2023-03-10 12:06 UTC, Skaylan commented on README.md
> +O BrasilAPI é uma iniciativa feita de brasileiros para brasileiros, por favor, não abuse deste serviço. Estamos em beta e ainda elaborando os Termos de Uso, mas por enquanto por favor não utilize for
;)

2023-03-11 13:44 UTC, kaiosilveira approved these changes
LGTM! 🔥

2023-03-12 13:13 UTC, RodriAndreotti approved these changes
Ficou show de bola!

2023-03-12 19:07 UTC, LorhanSohaky approved these changes

2023-03-12 19:08 UTC, merged

2023-03-12 19:08 UTC, LorhanSohaky commented
Muito obrigado pela contribuição! 🚀