Adicionando biblioteca PHP
BrasilAPI/BrasilAPI pull request #474
Opened 2023-02-23 13:28 UTC by carloscarucce

Adicionando biblioteca PHP à lista

2023-02-25 15:54 UTC, LorhanSohaky commented
@carloscarucce , poderia atualizar esse PR? Acabei de adicionar uma lib também em PHP

2023-02-25 15:55 UTC, LorhanSohaky requested changes
Pode atualizar o PR? colocando a sua lib como um sub item das libs em PHP?

2023-02-27 01:39 UTC, gtomanini approved these changes

2023-02-27 16:37 UTC, carloscarucce commented
@gtomanini feito :)

2023-02-27 22:08 UTC, LorhanSohaky approved these changes

2023-02-28 01:05 UTC, merged

2023-02-28 01:05 UTC, LorhanSohaky commented
@carloscarucce , obrigado pela contribuição!  Sua lib está lá 🚀