Indices - IGP-M
BrasilAPI/BrasilAPI pull request #475
Opened 2023-02-26 22:29 UTC by Met4tron

Fala pessoal!

Dando uma olhada nas issues acabei esbarrando na #453 sobre dados do IGP-M e acabei descobrindo uma fonte de dados diretamente do Banco Central e construi umas rotas para consumir esses dados

Aproveitei também para incluir a lib Joi no projeto, pra fazer toda a validação dos dados vindos da fonte externa

1) Consulta a lista completa de valores desde sua criação (30/06/1989)
2) Consulta os ultimos x valores a partir da data atual
3) Consulta valores dentro de um intervalo de datas

Links:
SGS => https://www3.bcb.gov.br/sgspub/consultarvalores/telaCvsSelecionarSeries.paint
Código BCB => 189

2023-03-10 11:11 UTC, LorhanSohaky requested changes

2023-03-10 11:11 UTC, LorhanSohaky commented on pages/api/indices/igpm/v1/intervalo/index.js
> +      type: 'INTERNAL',
Pode usar algo assim

```suggestion
      type: 'range_error',
```

2023-03-10 11:11 UTC, LorhanSohaky commented on pages/api/indices/igpm/v1/intervalo/index.js
> +  return response.json(igpmList);
Aqui vale o mesmo comentário de colocar um try catch em volta de tudo e gerar um erro 500 caso ocorra um erro inesperado

2023-03-10 11:11 UTC, LorhanSohaky commented on pages/api/indices/igpm/v1/ultimos/index.js
> +  const igpmList = await getIgpmByLastNRecords(codes.igpm, limit);
Só de curiosidade, o que acontece se o limit = `Infinity` ou limit = `NaN` ?

2023-03-10 11:11 UTC, LorhanSohaky commented on pages/docs/doc/igpm.json
> +      "description": "Informações referentes aos indices \nIGP-M"
Aqui talvez valha apena colocar uma descrição mais genérica para os índices ou mudar o nome da tag e consequentemente os paths das rotas

2023-03-10 11:11 UTC, LorhanSohaky commented on pages/docs/doc/igpm.json
> +        "description": "Retorna todos os ultimos últimos valores do IGP-M de acordo com a quantidade informada",
```suggestion
        "description": "Retorna todos os últimos valores do IGP-M de acordo com a quantidade de meses informada",
```

2023-03-10 11:11 UTC, LorhanSohaky commented on pages/docs/doc/igpm.json
> +            "description": "Quantidade de registros a serem obtidos",
Seria quantidade de meses ou registros? Só pro caso de haver mais de um índice pro mesmo mês
```suggestion
            "description": "Quantidade de meses a serem obtidos",
```

2023-03-10 11:11 UTC, LorhanSohaky commented on pages/docs/doc/igpm.json
> +        "description": "Retorna todos os valores de IGP-M desde sua criação",
Creio que aqui precise atualizar a documentação

2023-03-10 11:11 UTC, LorhanSohaky commented on pages/docs/doc/igpm.json
> +                    "type": "INTERNAL",
Aqui entra a sugestão de mudança de type

2023-03-10 11:12 UTC, LorhanSohaky commented
@Met4tron , muito massa essa API. Deixei algumas sugestões para essas rotas ficarem ainda melhor

2023-03-10 14:14 UTC, Met4tron commented on tests/indices/igpm.test.js
> +            value: expect.any(String),
Não havia me atentado a isso, corrigindo para float

2023-03-10 14:15 UTC, Met4tron commented on tests/indices/igpm.test.js
> +  });
Não, esse teste se caso o intervalo final seja anterior ao intervalo inicial, deverá retornar um erro 400

2023-03-10 14:18 UTC, Met4tron commented on pages/api/indices/igpm/v1/ultimos/index.js
> +  const igpmList = await getIgpmByLastNRecords(codes.igpm, limit);
Realmente! Coloquei um guard para caso seja NaN ou Infinity

2023-03-11 12:25 UTC, LorhanSohaky commented on pages/api/indices/igpm/v1/intervalo/index.js
> +    const finalDate = parseToDate(finalDateInterval, 'DD-MM-YYYY');
O padrão ISO é um pouco diferente
```suggestion
    const initialDate = parseToDate(initialDateInterval, 'YYYY-MM-DD');
    const finalDate = parseToDate(finalDateInterval, 'YYYY-MM-DD');
```

2023-03-11 12:25 UTC, LorhanSohaky commented on tests/indices/igpm.test.js
> +          final_date: '20/01/2005',
O formato ISO é ANO-MES-DIA

2023-03-11 12:26 UTC, LorhanSohaky commented on pages/api/indices/igpm/v1/intervalo/index.js
> +  const finalDate = parseToDate(final_date, 'DD/MM/YYYY');
Mesmo ponto sobre o formato iso que é ANO-MES-DIA

2023-03-11 12:33 UTC, LorhanSohaky commented on tests/indices/igpm.test.js
> +          final_date: '20-01-2005',
```suggestion
          initial_date: '2003-01-20',
          final_date: '2005-01-20',
```

2023-03-11 12:38 UTC, LorhanSohaky commented on services/indices/helpers.js
> +export const fetchData = async (url, params = {}, schema) => {
O sonarcloud indicou isso como um code smell. Seria interessante trocar a ordem desses parâmetros e consequentemente os locais que o chamam

![image](https://user-images.githubusercontent.com/16273730/224484809-fbdd1b97-6c8f-4804-bb15-116c48b51fcd.png)

```suggestion
export const fetchData = async (url, schema,  params = {}) => {
```

2023-03-11 12:38 UTC, LorhanSohaky commented on tests/indices/igpm.test.js
> +  });
Então, mas se `final < initial `, isso implica que ` initial > final`
o mesmo vale para `initial > final`, isso implica que `final < initial`

2023-03-11 12:41 UTC, LorhanSohaky reviewed
Acho que agora só ficou esses pequenos detalhes

2023-03-11 12:41 UTC, LorhanSohaky commented on tests/indices/igpm.test.js
> +            final_date: '20-01-2005',
```suggestion
            final_date: '2005-01-20',
```

2023-03-11 12:41 UTC, LorhanSohaky commented on tests/indices/igpm.test.js
> +            initial_date: '20-01-2005',
```suggestion
            initial_date: '2005-01-20',
```

2023-03-11 12:41 UTC, LorhanSohaky commented on tests/indices/igpm.test.js
> +            final_date: '19/01/2005',
```suggestion
            initial_date: '2005-01-20',
            final_date: '2005-01-19',
```

2023-03-11 12:41 UTC, LorhanSohaky commented on tests/indices/igpm.test.js
> +            final_date: '19-01-2005',
```suggestion
            initial_date: '2005-01-22',
            final_date: '2005-01-19',
```

2023-03-11 14:36 UTC, Met4tron commented on pages/docs/doc/igpm.json
> +      "description": "Informações referentes aos indices \nIGP-M"
Pensei em deixar indices mesmo, dado que existem outros diversos indices que podem ser implementados nos futuro

2023-03-11 14:36 UTC, Met4tron commented on pages/api/indices/igpm/v1/intervalo/index.js
> +    const finalDate = parseToDate(finalDateInterval, 'DD-MM-YYYY');
Show! Acabei ficando enrolando em outro assunto aqui, mas já faço a troca para ISO

2023-03-11 14:42 UTC, Met4tron commented on services/indices/helpers.js
> +export const fetchData = async (url, params = {}, schema) => {
Show! Feito a correção sugerida

2023-03-12 19:13 UTC, LorhanSohaky commented on pages/docs/doc/igpm.json
> +      "description": "Informações referentes aos indices \nIGP-M"
Aah, okay. É que como citava apenas o IGP-M por isso estranhei

2023-03-12 19:15 UTC, LorhanSohaky approved these changes
Ficou muito bom!! Muito obrigado pela contribuição!

2023-03-20 15:41 UTC, murilohns commented on pages/api/indices/igpm/v1/index.js
> +import app from '@/app';
@Met4tron esse PR tá adicionando 3 novas rotas no serviço, mas 1 rota só não daria conta?

só a rota `api/indices/igpm/v1` deveria conseguir fazer as 3 coisas acho.

Como está atualmente:

`api/indices/igpm/v1`: Bate na API do BCB, buscando todo o registro histórico de indices
`api/indices/igpm/v1/ultimos`: Bate na API do BCB, buscando todo o registro histórico de indices, mas envia o parâmetro de `lastRecords`
`api/indices/igpm/v1/intervalos`: 
Bate na API do BCB, buscando todo o registro histórico de indices, mas envia os parâmetros de `dataInicial` e `dataFinal`

Sugestão:

`api/indices/igpm/v1`: Rota aceitar os 3 parâmetros: `initial_date`, `final_date` e `limit`
Regras:
1. Se não tiver nenhum filtro aplicado, trás todos os registros
2. Se tiver `initial_date`, precisa ter `final_date` e vice-versa. Aplica o filtro de data na busca.
3. O parâmetro `limit` geralmente remete à quantos registros serão trazidos, então entram algumas opções:
- Se tiver `limit` não pode ter filtro de data
- Se tiver `limit` e filtro de data, devemos trazer só quantidade solicitada

É apenas uma sugestão, e estou abrindo a thread pra discussão

2023-04-06 01:32 UTC, LeoFC97 commented on pages/api/indices/igpm/v1/intervalo/index.js
> +        message: 'Intervalo de datas inválido, informe um intervalo correto',
Seria bacana informar qual é o formato de data do intervalo correto. YYYYMMDD ou algo assim por exemplo.

2023-04-06 10:10 UTC, LorhanSohaky commented on pages/api/indices/igpm/v1/intervalo/index.js
> +        message: 'Intervalo de datas inválido, informe um intervalo correto',
@Met4tron , o que acha?

2026-04-11 22:14 UTC, lucianopf commented
Muito obrigado pela contribuição, @Met4tron! 🙏

Seu esforço e dedicação fazem o BrasilAPI melhor para toda a comunidade de desenvolvedores brasileiros. Fico feliz de ter você contribuindo com o projeto!

2026-04-11 22:15 UTC, lucianopf commented
Olá @Met4tron! Obrigado pelo trabalho no endpoint de IGP-M — a implementação está bem estruturada e usa a API pública do BCB.

O PR está desatualizado com a branch main e tem conflitos em vários arquivos (`package.json`, `package-lock.json`, `services/date.js`, `pages/index.js`, `pages/sitemap.xml`). Seria possível fazer o rebase/merge do main para resolver os conflitos?

**Principais pontos a atualizar:**
- `services/date.js` recebeu novas funções (`isWeekend`, `subBusinessDays`, `validateDateComponents`) no main — as funções do PR (`isBefore`, `isAfter`, `toISOString`) devem ser preservadas junto com as novas
- `package.json` e `package-lock.json` precisam de regeneração após o rebase (rodar `npm install` para atualizar o lockfile com a entrada do joi)

Com o rebase feito, podemos mergear!

2026-04-11 22:50 UTC, lucianopf commented
Olá @Met4tron, usar a API do BCB para IGP-M é uma ótima escolha — fonte oficial! A estrutura do código está bastante boa. Alguns ajustes antes do merge:

**Correções necessárias:**

**1. Nova dependência `joi` quando `zod` já está no projeto**

O projeto já usa `zod` para validação de schemas (adicionado recentemente). Adicionar `joi` cria duas bibliotecas de validação no bundle. Use `zod` em vez de `joi` para manter consistência:

```js
// Equivalente em zod
import { z } from 'zod';
const igpmSchema = z.array(z.object({
  data: z.string(),
  valor: z.string(),
})).min(1);
```

**2. Testes com CommonJS e sem Vitest**

```js
// ❌
const axios = require('axios');

// ✅
import axios from 'axios';
import { describe, test, expect } from 'vitest';
import { testCorsForRoute } from './helpers/cors';
```

Adicione testes de CORS no final do arquivo de testes.

**3. Testes de erro sem `expect.assertions()`**

Os testes com `try/catch` não têm `expect.assertions(N)` no início, então se o request não lançar erro, as assertions no `catch` são silenciosamente ignoradas.

**4. `codes.js` em `pages/api/`**

`pages/api/indices/codes.js` não é um handler de API — é um módulo de constantes. Mova para `services/indices/codes.js` ou `lib/indices/codes.js`.

**5. Handler `index.js` sem `return`**

```js
// ❌
response.status(200);
response.json(igpmList);  // sem return!

// ✅
return response.status(200).json(igpmList);
```

**6. Modificações em `pages/index.js` e `pages/sitemap.xml/index.jsx`** — não relacionadas ao PR, por favor remova.

Com as correções dos pontos 1-4, o PR estará pronto. A lógica de negócio está bem implementada!

2026-08-07 22:45 UTC, lucianopf commented
Oi @Met4tron! Este PR foi **substituído pelo #841** — a feature (IGP-M via BCB) foi rebaseada na main e corrigida (o endpoint de intervalo retornava 500 porque o BCB só aceita datas em DD/MM/AAAA; o branch original também não tinha a base atual). Autoria preservada.

Fechando este em favor do #841 — obrigado pela contribuição original! 🙏

2026-08-07 22:45 UTC, closed without merging