Fix #476
BrasilAPI/BrasilAPI pull request #477
Opened 2023-03-04 20:18 UTC by RodriAndreotti

Corrige erro apontado no issue #476 Relacionado ao parse do csv para json quando o mesmo tem aspas devido a vírgulas dentro do nome.

2023-03-06 14:21 UTC, LorhanSohaky requested changes
Estava passando por um problema idêntico essa semana. Recomendo que usemos o papaparser para que este erro pare de acontecer

https://www.papaparse.com/docs#csv-to-json

2023-03-06 23:13 UTC, RodriAndreotti commented
> Estava passando por um problema idêntico essa semana. Recomendo que usemos o papaparser para que este erro pare de acontecer
> 
> https://www.papaparse.com/docs#csv-to-json

Rapazz, interessante isso ai, ele já até baixa o arquivo sem precisar baixar primeiro.....

Vou fazer aqui.

2023-03-07 01:37 UTC, LorhanSohaky reviewed
Acho que o único detalhe é a pinagem da versão

2023-03-07 01:37 UTC, LorhanSohaky commented on package.json
> +    "papaparse": "^5.4.0",
Só precisa pinar a versão

2023-03-07 01:37 UTC, LorhanSohaky commented on package-lock.json
> +        "papaparse": "^5.4.0",
Pinar a versão

2023-03-07 01:37 UTC, LorhanSohaky commented on package.json
> +    "papaparse": "^5.4.0",
Sugestão: npm install papaparse@5.4.0

2023-03-07 12:35 UTC, RodriAndreotti commented on package-lock.json
> +        "papaparse": "^5.4.0",
Resolvido

2023-03-07 17:15 UTC, LorhanSohaky approved these changes

2023-03-07 18:01 UTC, lucianopf approved these changes

2023-03-07 18:01 UTC, merged