cambio:Adicionando cambio de moedas com o real
BrasilAPI/BrasilAPI pull request #499
Opened 2023-06-21 15:25 UTC by vinihora

Adicionando câmbio a BrasilAPI

Fonte:
Banco central (https://olinda.bcb.gov.br/olinda/servico/PTAX/versao/v1/aplicacao#!/recursos)

A Nova API permite que o usuário escolha uma moeda e uma data, e terá como retorno a cotação desejada em relação ao Real.
Documentação adicionada

Exemplo de rota: /api/cambio/USD/20-06-2023

Rota genérica: /api/cambio/{moeda}/{data}

Data formato: DD-MM-AAAA

Moedas disponíveis em relação ao Real:
AUD 
CAD 
CHF
DKK
EUR
GBP
JPY
SEK
USD

2023-06-28 01:15 UTC, LorhanSohaky reviewed
Muito obrigado pela contribuição! Deixei alguns pontos de melhoria e precisamos que você adicione casos de testes para garantir que a API está funcionando corretamente

2023-06-28 01:15 UTC, LorhanSohaky commented on pages/api/cambio/[moeda]/[data].js
> +export default app(21600).get(Action);
Por padrão o cache é de 24h. Se não tiver necessidade de especificar algo diferente sugiro remover esse parâmetro

2023-06-28 01:15 UTC, LorhanSohaky commented on pages/docs/doc/cambio.json
> +            "description": "A moeda alvo desejada (AUD, CAD, CHF, DKK, EUR, GBP, JPY, SEK, USD)",
Seria interessante indicar algum site com todas as siglas de moedas disponíveis no sistema

2023-06-28 01:15 UTC, LorhanSohaky commented on pages/docs/doc/cambio.json
> +            "description": "A data desejada, o formato deve ser: DD-MM-AAAA. Os dados só estão disponíveis a partir de 28-11-1984.",
Por padrão são utilizadas datas no formato YYYY-MM-DD

2023-06-28 01:15 UTC, LorhanSohaky commented on pages/docs/doc/cambio.json
> +        }
Acho interessante que o formato seja nesse formato https://github.com/RodriAndreotti/BrasilAPI/blob/master/GOOD_PRACTICES.md#moedas

2023-06-28 01:15 UTC, LorhanSohaky commented on services/cambio/getCambio.js
> +  );
Sugiro separar os parâmetros da URL, assim ficará mais legível.

Um trecho de exemplo:
```js
axios.get('/user', {
    params: {
      ID: 12345
    }
  })
```

2023-06-28 01:15 UTC, LorhanSohaky commented on services/cambio/getCambio.js
> +  return resp;
Também sugiro alterar para algo assim e retornar apenas o dado necessário
```suggestion
  return resp.data;
```

2023-06-29 23:04 UTC, vinihora commented
@LorhanSohaky ajustes realizados, pode revisar novamente? Obrigado

2023-06-29 23:08 UTC, vinihora commented
Também realizei ajustes nos testes E2E, pois os resultados esperados de alguns dos testes estavam desatualizados com as informações atuais.

2023-06-29 23:23 UTC, vinihora commented
Atualização da documentação de câmbio

2023-06-30 18:30 UTC, LorhanSohaky reviewed
Novamente, muito obrigado pela contribuição. Deixei mais alguns pontos de melhoria, acho que depois disso deve ser aprovado pela minha parte

2023-06-30 18:30 UTC, LorhanSohaky commented on pages/api/cambio/[moeda]/[data].js
> +      });
```suggestion
   const moedas = infoMoedas.value.map((currency)) => currency.simbolo);
```

2023-06-30 18:30 UTC, LorhanSohaky commented on pages/api/cambio/[moeda]/[data].js
> +    }
Se utilizar a função que sugeri, você poderá gerar esse erro lá no começo

2023-06-30 18:30 UTC, LorhanSohaky commented on pages/api/cambio/[moeda]/[data].js
> +      });
Isso não será necessário ao utilizar a função que sugeri. Talvez até na mensagem de erro você pode citar algo sobre o formato esperado

2023-06-30 18:30 UTC, LorhanSohaky commented on pages/api/cambio/[moeda]/[data].js
> +    }
Mesmo comentário sobre quando o axios retorna status code != 200. E o erro para essa situação deveria ser do tipo interno

2023-06-30 18:30 UTC, LorhanSohaky commented on pages/api/cambio/[moeda]/[data].js
> +    });
```suggestion
    if (err instanceof BaseError) {
      throw err;
    }

    throw new InternalError({
      message: 'Erro ao buscar cambio',
      type: 'cambio_error',
      name: 'CAMBIO_ERROR',
    });
```

2023-06-30 18:35 UTC, LorhanSohaky commented on pages/docs/doc/cambio.json
>            {
Esse aqui pode ignorar kkkk, confundi com outro PR

2023-07-05 02:04 UTC, LorhanSohaky commented on services/cambio/getCambio.js
> +  }
Aqui você não precisa tratar a exceção, pois a `pages/api/cambio/v1/[moeda]/[data].js` já trata quando não é um erro esperado.

Mas se preferir realizar o tratamento mesmo assim sugiro fazer o seguinte:
```suggestion
  try {
    const resp = await axios.get(
      `https://olinda.bcb.gov.br/olinda/servico/PTAX/versao/v1/odata/CotacaoMoedaDia(moeda=@moeda,dataCotacao=@dataCotacao)?@moeda='${moeda}'&@dataCotacao='${data}'&$top=100&$format=json`
    );
    return { info: resp.data };
  } catch (error) {
    throw new InternalError({
      message: 'Não foi possível realizar a requisição',
      type: 'internal_error',
      name: 'INTERNAL_ERROR',
    });
  }
```

2023-07-05 11:18 UTC, LorhanSohaky approved these changes
Muito obrigado pela contribuição! 🚀

2023-08-03 20:45 UTC, murilohns reviewed
Ficou muito legal o PR!
Apenas deixarei o request changes pelo fato de misturar inglês e pt-br no meio do código.

Olhando nossa base de código, não temos nenhum caso assim, sempre optamos por usar inglês! Misturar com o pt-br acaba ficando estranho. Já imaginou se precisamos buscar algo pelo ano? Teríamos a função `getByAno` (get baiano).

Em resumo, só passa o que puder pra inglês da base de código, e a gente faz o merge do PR :D

Dá uma olhada no comentário do @LorhanSohaky também!

2023-08-03 20:45 UTC, murilohns commented on pages/api/cambio/v1/[moeda]/[data].js
> +    const newData = dayjs(data);
```suggestion
    const newDate = dayjs(data);
```

2023-08-03 20:45 UTC, murilohns commented on pages/api/cambio/v1/[moeda]/[data].js
> +        message: 'Formato de data inválida, utilize: AAAA-MM-DD',
```suggestion
        message: 'Formato de data inválida, utilize: YYYY-MM-DD',
```

2023-08-03 20:45 UTC, murilohns commented on pages/api/cambio/v1/[moeda]/[data].js
> +    const dataRetorno = formatDate(newData, 'YYYY-MM-DD');
```suggestion
    const searchDate = formatDate(newData, 'MM-DD-YYYY');
    const responseDate = formatDate(newData, 'YYYY-MM-DD');
```

2023-08-03 20:45 UTC, murilohns commented on pages/api/cambio/v1/[moeda]/[data].js
> +    const tamanhoArray = info.value.length;
```suggestion
    const arrayLength = info.value.length;
```

2023-08-03 20:45 UTC, murilohns commented on pages/docs/doc/cambio.json
> +            "description": "A data desejada, o formato deve ser: AAAA-MM-DD. Os dados só estão disponíveis a partir de 28-11-1984.",
```suggestion
            "description": "A data desejada, o formato deve ser: YYYY-MM-DD. Os dados só estão disponíveis a partir de 28-11-1984.",
```

2023-08-03 20:45 UTC, murilohns commented on services/cambio/getCambio.js
> +export const getCambio = async (data, moeda) => {
```suggestion
export const getExchange = async (data, moeda) => {
```

2023-08-03 20:45 UTC, murilohns commented on services/cambio/getMoedas.js
> +export const getMoedas = async () => {
SUGESTÃO:

```suggestion
export const getCoins = async () => {
```

2023-08-03 20:45 UTC, murilohns requested changes
Esqueci de marcar o request changes hehe

2025-02-19 12:01 UTC, merged

2025-02-19 12:04 UTC, LorhanSohaky commented
Feito no pr #661 . Muito obrigado pela contribuição