feat: endpoint /aeroportos
BrasilAPI/BrasilAPI pull request #501
Opened 2023-07-10 15:27 UTC by Joaomgsa

Adicionei um endpoint que retorna lista de todos aeroportos do Brasil baseado na fonte de dados da [ANAC](https://sistemas.anac.gov.br/dadosabertos/Aerodromos/Lista%20de%20aer%C3%B3dromos%20p%C3%BAblicos/AerodromosPublicos.json). 

As próximas serão consultas que retornem as informações do aeroporto passando parametros por estados e por cidades.

2023-08-26 11:11 UTC, LorhanSohaky requested changes

2023-08-26 11:11 UTC, LorhanSohaky commented on services/aeroportos/index.js
> +        LonGeoPoint: objeto.LonGeoPoint,
Aqui sugiro alterar como as chaves são acessadas e padronizar a saída para ficar no mesmo estilo dos demais endpoints
```suggestion
        codigo_oaci: objeto['CódigoOACI'],
        aeroporto: objeto['Nome'],
        cidade: objeto['Município'],
        estado: objeto['UF'],
        localizacao: {
          "type": "Point",
          "coordinates": {
            "longitude": parseFloat(objeto.['LonGeoPoint']),
            "latitude": parseFloat(objeto.['LatGeoPoint']),
          }
        }
```

Caso tenha interesse tem um PR que costumo usar como referência #268

2023-08-26 11:11 UTC, LorhanSohaky commented on services/aeroportos/index.js
> +    return aeroportosList;
Aqui entra um pouco de escolha de design se é melhor dar erro quando o provedor parar de fornecer o dado ou não. 

Se formos manter isso precisa parsear esse arquivo também

2023-08-26 11:11 UTC, LorhanSohaky commented on pages/docs/doc/aeroporto.json
> +                }
Precisa ajudar com o novo formato que sugeri

2023-08-26 11:11 UTC, LorhanSohaky commented on pages/docs/doc/aeroporto.json
> +                    }
Pelo que vejo do código isso nunca irá ocorrer por conta do fallback

2026-04-11 22:49 UTC, lucianopf commented
Olá @Joaomgsa, usar a API de dados abertos da ANAC é ótimo — fonte oficial e confiável! Há alguns ajustes necessários:

**Correções necessárias:**

**1. Campos de resposta em PascalCase — deveria ser snake_case**

O padrão da BrasilAPI é snake_case para propriedades de resposta:

```js
// ❌ atual
{ CodigoOACI: ..., NomeAeroporto: ..., Cidade: ..., Estado: ..., LatGeoPoint: ..., LonGeoPoint: ... }

// ✅ correto
{ codigo_oaci: ..., nome: ..., cidade: ..., estado: ..., lat_geo_point: ..., lon_geo_point: ... }
```

**2. Handler sem `return`**

```js
// ❌
response.status(200);
response.json(allAeroportosData);

// ✅
return response.status(200).json(allAeroportosData);
```

**3. Fallback silencioso para JSON estático**

```js
} catch (err) {
  return aeroportosList; // ← retorna dados desatualizados sem avisar
}
```

Se a ANAC estiver fora do ar, o consumidor receberá dados possivelmente desatualizados sem saber. Prefira propagar o erro:

```js
} catch (err) {
  throw new InternalError({ message: 'Erro ao buscar aeroportos' });
}
```

O middleware de cache (`s-maxage=86400`) já garante que dados recentes fiquem disponíveis via CDN por 24h mesmo se a ANAC estiver temporariamente fora.

**4. Testes com CommonJS e sem Vitest**

```js
// ❌
const axios = require('axios');

// ✅
import axios from 'axios';
import { describe, test, expect } from 'vitest';
import { testCorsForRoute } from './helpers/cors';
```

Adicione também um teste que valide a estrutura do retorno (campos do aeroporto) e o teste de CORS: `testCorsForRoute('/api/aeroportos/v1')`.

**5. Modificações não relacionadas**

`pages/index.js` e `pages/sitemap.xml/index.jsx` não devem estar neste PR.

A estrutura geral está no caminho certo! Com as correções acima o PR fica pronto.

2026-08-07 22:45 UTC, lucianopf commented
Olá! Este PR está parado há mais de 2 anos sem atividade do autor, com mudanças solicitadas na revisão que não foram aplicadas (ou base muito desatualizada). Estamos fechando para limpar a fila, mas **sinta-se à vontade para reabrir** quando quiser retomar — basta rebasear na main e ajustar conforme as solicitações de review. 🙏

Se a feature ainda for desejada, um PR novo com base atualizada tem muito mais chance de aprovação.

2026-08-07 22:45 UTC, closed without merging