Hotfix/eslint
BrasilAPI/BrasilAPI pull request #511
Opened 2023-08-24 23:35 UTC by RodriAndreotti

Ajuste do ESLint para usar Ecma2020, para rodar com a sintaxe nova usada no parseRequest.js e atualização da lib do eslint

2023-08-26 10:46 UTC, LorhanSohaky commented
@RodriAndreotti, não revisando, mas já revisando... Poderia pinar a versão do eslint e olhar porque o deploy na vercel está falhando?

2023-08-26 13:03 UTC, RodriAndreotti commented
> @RodriAndreotti, não revisando, mas já revisando... Poderia pinar a versão do eslint e olhar porque o deploy na vercel está falhando?

Então, fica a vontade para revisar... rs
eu também não entendi essa história da Vercel, eu rodei o build local e não deu o mesmo erro.

Sobre a versão, já pino agora.

2023-10-21 13:44 UTC, LorhanSohaky commented on package.json
> +    "core-js": "3.32.1",
Essa lib é necessária?

2023-10-21 13:57 UTC, RodriAndreotti commented on package.json
> +    "core-js": "3.32.1",
Rapaz, sendo bem sincero, não lembro porque ela entrou ai, faz algum tempo já :-D
Mas removi aqui, removi o lock e a node_modules e reinstalei e não deu erro (além dos testes)

2023-10-21 15:14 UTC, LorhanSohaky commented on package.json
> +    "core-js": "3.32.1",
![image](https://github.com/BrasilAPI/BrasilAPI/assets/16273730/f2fbea47-c74d-4a7c-a76d-3661ba2e6707)

2023-10-28 22:17 UTC, LorhanSohaky requested changes

2023-10-28 22:17 UTC, LorhanSohaky commented on package.json
> +    "core-js": "^3.33.1",
só pinar a versão e bora subir isso kkk

2023-10-30 12:15 UTC, RodriAndreotti commented on package.json
> +    "core-js": "^3.33.1",
Opa... feito!

2023-10-30 12:36 UTC, LorhanSohaky approved these changes

2023-11-09 22:44 UTC, merged