Removendo URL dinâmica no exemplo da RequestURL
BrasilAPI/BrasilAPI pull request #520
Opened 2023-09-13 17:38 UTC by Eumanuel

Deixar o link de exemplo da API como dinâmico causava erros quando o usuário não entrava utilizando o caminho esperado.

Exemplo:

Se você entrar na documentação por [https://brasilapi.com.br/docs#operation/ondaspredictionwithoutdays(/cptec/v1/ondas/:cityCode)](https://[brasilapi.com.br/docs](https://brasilapi.com.br/docs#operation/ondaspredictionwithoutdays(/cptec/v1/ondas/:cityCode))#operation/ondaspredictionwithoutdays(/cptec/v1/ondas/:cityCode)) e clicar para ver o exemplo da URL completa de alguma rota, essa será sua visão:
![image](https://github.com/BrasilAPI/BrasilAPI/assets/44380634/182bbdcf-3380-419e-8a8f-cafcfc90929a)

Um exemplo que completamente incorreto.

Estudei  a documentação e cheguei a conclusão que não há opção senão utilizar uma URL fixa, visto que o domínio e rotas não mudam constantemente e essa dinamicidade só é aproveitada caso em algum ambiente de desenvolvimento.

2023-09-13 18:02 UTC, Eumanuel commented
Sendo minha primeira contribuição, alguém poderia me auxiliar a entender o que aconteceu nos testes para ser negado?

2023-09-13 22:02 UTC, RodriAndreotti commented
> Sendo minha primeira contribuição, alguém poderia me auxiliar a entender o que aconteceu nos testes para ser negado?

Buenas, mestre!
Beleza?
Sobre o teste acredito que foi alguma instabilidade nos serviços, tenta fazer um commit com amend  que eles rodam novamente e podemos averiguar se é algo que precise realmente de atenção.

Sobre o seu PR, acredito que a alteração faça sentido, porém aparentemente só subiu o package-lock, conseguiria averiguar?

2023-09-14 10:30 UTC, Eumanuel commented
Bom dia,

Verifiquei aqui e realmente não subiu a minha alteração, ajustei por aqui e agora subiu certinho.

Os erros permanecem, mas apenas na sessão da API do CPTEC, eu tentei utilizar a API deles manualmente e está retornando erro, acredito que eles estão instáveis de fato... Qual é o procedimento nesse caso?

Obrigado!!

2023-09-14 11:51 UTC, RodriAndreotti commented
> Bom dia,
> 
> Verifiquei e realmente não subiu a minha alteração, ajustei por aqui e agora subiu certinho.
> 
> Os erros permanecem, mas apenas na seção da API do CPTEC, eu tentei utilizar a API deles manualmente e está retornando erro, acredito que eles estão instáveis de fato... Qual é o procedimento nesse caso?
> 
> Obrigado!!

Opa... neste caso não temos muito o que fazer, é esperar eles estabilizarem novamente para os testes passarem, os admins do repositório conseguem subir sem passar o teste, se for o caso acredito que possa ser o caminho.

2023-09-14 11:52 UTC, RodriAndreotti requested changes

2023-09-14 11:52 UTC, RodriAndreotti commented on package-lock.json
Eu acredito que possamos remover o package-lock do PR, o que acha?

2023-09-14 17:36 UTC, Eumanuel commented on package-lock.json
Retirei o package lock e de quebra ele já vai rodar novamente, vamos ver se agora passa os testes

2023-09-14 22:46 UTC, RodriAndreotti approved these changes

2023-09-14 22:48 UTC, merged