Feature: PEPs
BrasilAPI/BrasilAPI pull request #521
Opened 2023-09-23 20:41 UTC by Kaue-Romero

Essa feature é para adicionar a API de pessoas politicamente expostas da Issue: [363](https://github.com/BrasilAPI/BrasilAPI/issues/363).

Ela contém:
- Dados atualizados da última data de julho de 2023 adiquiridos através do site do [portal da transparência](https://portaldatransparencia.gov.br/download-de-dados/pep)

- Os retornos estão documentados e totalmente funcionais, podendo ser utilizado parâmetros de pesquisa como datas, CPF, nome, cargo e entre outras chaves

- Há poucos testes pois a lista de PEPs é muito grande então decidi deixar apenas os testes mais importantes (como: pesquisa por CPF, nome e data)

- A lista original é em CSV mas converti para JSON para facilitar o trabalho com as chaves

Espero ter ajudado. 👍🏻 
![Captura de tela de 2023-09-23 17-40-14](https://github.com/BrasilAPI/BrasilAPI/assets/69368947/6dcb7374-1b43-4ee1-a9d4-d320c09273b2)
![Captura de tela de 2023-09-23 17-41-13](https://github.com/BrasilAPI/BrasilAPI/assets/69368947/a8ffdb37-7096-445b-8ec0-0b91cddbaf73)

2023-10-28 10:08 UTC, LorhanSohaky requested changes
@Kaue-Romero , seria mais interessante se pegássemos a lista de PEP em tempo de execução ao invés de ter um arquivo estático

2023-11-06 17:29 UTC, Kaue-Romero commented
Tentei pegar o arquivo pelo js com o axios e fetch. Ambos retornam 403 com a resposta da CloudFront não autorizando o acesso ao arquivo.

2023-11-06 21:23 UTC, RodriAndreotti commented
> Tentei pegar o arquivo pelo js com o axios e fetch. Ambos retornam 403 com a resposta da CloudFront não autorizando o acesso ao arquivo. Acho que eles não permitem que o arquivo seja pego por algo que não seja um navegador, ou, tenha que configurar headers especificos. Segue o link do site que tentei acessar: https://portaldatransparencia.gov.br/download-de-dados/pep

Pelo que vi aqui, teoricamente, é um arquivo público, aparentemente vc baixaria um zip e com esse zip teria o tratamento.
esse cloudfront deve ter alguma coisa que limita pelo user_agent, se enviar um user-agent de firefox, ou chrome, será que não rolaria?

2026-04-11 22:49 UTC, lucianopf commented
Olá @Kaue-Romero, PEPs do Portal da Transparência é uma feature com demanda real! Há alguns pontos para discussão e correção.

**Ponto de discussão: dados estáticos vs. API oficial**

O PR empacota um arquivo JSON de julho/2023. Isso traz preocupações:
- Os dados ficam desatualizados imediatamente após o merge — novos PEPs entrarão na lista, outros sairão
- O `updated_at: '1688180400'` é hardcoded (não reflete quando o endpoint foi consultado)
- O arquivo provavelmente é grande (listas de PEPs costumam ter dezenas de milhares de registros)

O Portal da Transparência tem uma [API oficial](https://portaldatransparencia.gov.br/api-de-dados/pep) — mas requer cadastro/chave de API. Antes de implementar qualquer abordagem, isso precisa de discussão numa issue da comunidade (conforme princípio do projeto: serviços com chave de API precisam de aprovação prévia).

**Correções técnicas necessárias:**

**1. Não usa classes de erro do projeto**

```js
// ❌
return response.status(400).json({ message: '...', type: '...', name: '...' });

// ✅
throw new BadRequestError({ message: 'Nenhuma chave de pesquisa digitada' });
throw new NotFoundError({ message: 'Nenhum resultado encontrado' });
```

**2. `response.status(200)` sem `return response.json(...)`**

```js
// ❌
response.status(200);
return response.json({ data: result, ... });

// ✅
return response.status(200).json({ data: result, ... });
```

**3. Tamanho do arquivo JSON**

Se `202307_PEP.json` for muito grande (vários MB), pode causar problemas de performance no import do módulo e aumentar o bundle size do Vercel. Verifique o tamanho e avalie se pagination seria necessária.

Recomendo abrir uma issue de discussão sobre a abordagem (estático vs. API oficial com chave) antes de prosseguir com o PR.

2026-08-07 22:45 UTC, lucianopf commented
Olá! Este PR está parado há mais de 2 anos sem atividade do autor, com mudanças solicitadas na revisão que não foram aplicadas (ou base muito desatualizada). Estamos fechando para limpar a fila, mas **sinta-se à vontade para reabrir** quando quiser retomar — basta rebasear na main e ajustar conforme as solicitações de review. 🙏

Se a feature ainda for desejada, um PR novo com base atualizada tem muito mais chance de aprovação.

2026-08-07 22:45 UTC, closed without merging