Tests/isbn+cptec
BrasilAPI/BrasilAPI pull request #530
Opened 2023-10-20 22:27 UTC by alanmareines

# Fix testes ISBN + CPTEC/Cidades

## ISBN
Fix: remoção da comparação exata de preço. Adicionada uma checagem de valor como `Number`

## CPTEC/Cidades
Fix: atualização dos resultados para pesquisa mais URL friendly.

2023-10-20 22:36 UTC, RodriAndreotti requested changes
Buenas, Mestre!
No geral o PR ficou show, só deixei uma dúvida em uma das alterações.

2023-10-20 22:36 UTC, RodriAndreotti commented on tests/cpetc/cidade-v1.test.js
Mestre, algum motivo específico para alterar o nome da cidade no teste?
Pergunto, pois ele deveria funcionar também com o nome composto

2023-10-21 13:58 UTC, alanmareines commented on tests/cpetc/cidade-v1.test.js
Removi o commit para os testes de cidade, acho que podemos seguir.

2023-10-21 15:03 UTC, LorhanSohaky commented
Muito obrigado pelo PR!

closed by #515

2023-10-21 15:03 UTC, closed without merging