feat: dados abertos senado - servidores
BrasilAPI/BrasilAPI pull request #546
Opened 2023-11-30 09:09 UTC by vitorialira92

2023-12-01 17:43 UTC, alcidesmig commented on pages/api/senado/v1/servidores/ativos.js
> +        return response.json(result);
Uma coisa que percebi foi que vocês recebem os dados da API do senado e mandam direto para quem está chamando, se vocês observarem em outras partes do repositório eles fazem um mapeamento dos campos da resposta da API para campos próprios - isso daria algumas vantagens a implementação de vocês, fazendo com que o padrão (e os campos) da resposta pudesse ser controlado pela própria BrasilAPI, dando mais visibilidade no código dos campos respondidos, e permitindo contornar eventuais comportamentos estranhos ou quebras de contrato da API que vocês usaram.

2023-12-02 01:19 UTC, RodriAndreotti requested changes
No geral o PR ficou muito bom, quero agradecer a contribuição e parabenizar pelo código, pois é uma integração grande e sei que deu bastante trabalho para criar.

Se me permitirem eu gostaria de sugerir algumas alterações:

1- Nomes: Notei que tanto no código quanto nos arquivos há uma mistura de nomenclaturas em inglês e português (por ex.: `getAllInativos`), é sempre recomendável manter uma padronização.

Apesar de não termos uma recomendação oficial ainda para as nomenclaturas temos um documento que estamos trabalhando para caminhar a isso, e acredito que seja uma boa tentar dar uma analisada e ver se faz sentido adequar:
https://github.com/BrasilAPI/BrasilAPI/blob/6509fa5e96ed4544b193d6a56a5cfc1b48c29bf5/GOOD_PRACTICES.md

2- Verificar repetição de código: Se um código é usado em mais de um lugar sem alteração talvez seja interessante extraí-lo para um arquivo externo.

3- Indentação do código: apesar de não ser block é sempre uma boa prática manter o código bem indentado, notei que alguns arquivos aqui a indentação poderia receber alguma atenção, apesar de não estarem ruins.

Novamente obrigado pela contribuição e seria muito legal para a gente se quiserem contribuir com outras implementações ;-)

2023-12-02 01:19 UTC, RodriAndreotti commented on tests/senado-servidores-v1.test.js
Senti falta de testes para validar a algumas rotas aqui, por exemplo remunerações, horas extras etc.
Idealmente, para cada rota seria interessante termos ao menos um teste (melhor se for mais de um) para garantir que alguma alteração futura não a quebre.

2023-12-02 01:19 UTC, RodriAndreotti commented on pages/docs/doc/senado.json
> +                         "content": {
Apesar de não ser um block, poderia ficar um pouco mais fácil para leitura se os schemas fossem declarados separadamente e só referenciados nos responses.
Isso, inclusive, facilita o reuso de um schema que por ventura seja usado por duas ou mais rotas.

Um exemplo: https://github.com/BrasilAPI/BrasilAPI/blob/main/pages/docs/doc/cptec.json

2023-12-02 01:19 UTC, RodriAndreotti commented on pages/docs/doc/senado.json
> +              "400": {
Aqui nos possíveis erros recomendo o uso dos schemas que já temos:
https://github.com/BrasilAPI/BrasilAPI/blob/main/pages/docs/doc/error.json

2023-12-02 01:19 UTC, RodriAndreotti commented on pages/docs/doc/senado.json
> +                  "description": "Error",
Mesmo caso dos erros anteriores

2023-12-02 02:15 UTC, LorhanSohaky requested changes
Muito obrigado pela contribuição! Além de tudo que comentei, peço que adicione testes para todas as rotas, pois só assim detectaremos caso alguma delas comece a dar problema

2023-12-02 02:15 UTC, LorhanSohaky commented on pages/api/senado/v1/servidores/pensionistas/[ano]/[mes].js
> +          throw new BadRequestError({message: 'Ano e/ou mês inválido(s)'})
mesmos pontos sobre como as validações são feitas e as constantes

2023-12-02 02:15 UTC, LorhanSohaky commented on pages/api/senado/v1/servidores/pensionistas/index.js
> +        throw error;
mesmo sobre catch

2023-12-02 02:15 UTC, LorhanSohaky commented on pages/api/senado/v1/servidores/previsao-aposentadoria.js
> +        throw error;
mesmo sobre o catch

2023-12-02 02:15 UTC, LorhanSohaky commented on pages/api/senado/v1/servidores/quantitativos/cargos-funcoes.js
> +        throw error;
mesmo sobre o catch

2023-12-02 02:15 UTC, LorhanSohaky commented on pages/api/senado/v1/servidores/quantitativos/pessoal.js
> +        throw error;
mesmo sobre o catch

2023-12-02 02:15 UTC, LorhanSohaky commented on pages/api/senado/v1/servidores/remuneracoes/[ano]/[mes].js
> +        throw error;
mesmo sobre o catch

2023-12-02 02:15 UTC, LorhanSohaky commented on pages/api/senado/v1/servidores/servidores.js
> +  return vinculo == null || possibleValues.includes(vinculo);
a ideia é aceitar valores nulos?

2023-12-02 02:15 UTC, LorhanSohaky commented on pages/api/senado/v1/servidores/servidores.js
> +  return vinculo == null || possibleValues.includes(vinculo);
```suggestion
  return vinculo == null || possibleValues.includes(vinculo.toUpperCase()); 
```

2023-12-02 02:15 UTC, LorhanSohaky commented on pages/api/senado/v1/servidores/servidores.js
> +  return situacao == null || possibleValues.includes(situacao);
```suggestion
  return situacao == null || possibleValues.includes(situacao.toUpperCase()); 
```

2023-12-02 02:15 UTC, LorhanSohaky commented on pages/api/senado/v1/servidores/servidores.js
> +    }
mesmo sobre o catch

2023-12-02 02:15 UTC, LorhanSohaky commented on services/dados-publicos-senado/servidores/index.js
> +  return axios.get(API_URL +'/servidores' + params);
Sugiro fazer algo mais ou menos assim:
```suggestion
  return axios.get(API_URL +'/servidores', {
    params: {
      tipoVinculoEquals,
      situacaoEquals,
      lotacaoEquals,
      cargoEquals,
    }
  });
```

https://masteringjs.io/tutorials/axios/get-query-params

2023-12-02 02:15 UTC, LorhanSohaky commented on services/dados-publicos-senado/servidores/index.js
> +   return axios.get(endpoint);
```suggestion
   const {data} = await axios.get(endpoint);
   
   return data
```

2023-12-02 02:15 UTC, LorhanSohaky commented on tests/senado-servidores-v1.test.js
> +                padrao: null,
Sugiro deixar o teste mais genérico, validando apenas os tipos da resposta. Já tivemos problemas no passada validando o valor da resposta

2026-04-11 22:47 UTC, lucianopf commented
Olá @vitorialira92, usar a API de dados abertos do Senado é uma ótima ideia — é uma fonte oficial e pública! Mas o PR tem vários problemas técnicos que precisam ser corrigidos.

**Bloqueadores:**

**1. Bug grave em `getServidores`: todos os parâmetros usam o nome errado**

```js
// ❌ — todos os params ficam como 'tipoVinculoEquals'
if(situacaoEquals != null)
  params += `&tipoVinculoEquals=${situacaoEquals}`;  // deveria ser situacaoEquals=

if(lotacaoEquals != null)
  params += `&tipoVinculoEquals=${lotacaoEquals}`;   // deveria ser lotacaoEquals=

if(cargoEquals != null)
  params += `&tipoVinculoEquals=${lotacaoEquals}`;   // deveria ser cargoEquals= E usa a variável errada!
```

Isso tornaria todos os filtros disfuncionais em produção.

**2. Bug: `error.response.status` crash no handler `servidores.js`**

```js
throw new BadRequestError({message: "Parâmetros inválidos"})  // ← lançado acima

} catch (error) {
  if (error.response.status === 400) {  // ← crash: BadRequestError não tem .response
```

`BadRequestError` não tem propriedade `.response`. Isso causaria um `TypeError` sobrescrevendo o erro original.

**3. Testes com erros graves**

- `const axios = require('axios')` — CommonJS em projeto ESM
- Falta `import { describe, test, expect } from 'vitest'`
- `testEnvironment(...)` — esta função não existe. Use `test(...)`
- `'${global.SERVER.URL}/...'` — string literal com aspas simples, o template não é interpolado. Use backticks e `global.SERVER_URL`
- `expect.objectContaing` — typo, deveria ser `objectContaining`

**4. `console.log()` no handler** — remova antes do merge.

**Sugestões:**

- Use `const`/`let` em vez de `var`
- Use `===` em vez de `==`
- Use braces em todos os blocos `if`

Corrigindo esses pontos, o PR tem boa base para merge — a fonte de dados é oficial!

2026-08-07 22:45 UTC, lucianopf commented
Olá! Este PR está parado há mais de 2 anos sem atividade do autor, com mudanças solicitadas na revisão que não foram aplicadas (ou base muito desatualizada). Estamos fechando para limpar a fila, mas **sinta-se à vontade para reabrir** quando quiser retomar — basta rebasear na main e ajustar conforme as solicitações de review. 🙏

Se a feature ainda for desejada, um PR novo com base atualizada tem muito mais chance de aprovação.

2026-08-07 22:45 UTC, closed without merging