feat/bairros-por-municipio - Issue #266
BrasilAPI/BrasilAPI pull request #548
Opened 2023-11-30 09:22 UTC by luccacb16

Baseado na issue [#266](https://github.com/BrasilAPI/BrasilAPI/issues/266)

## Rotas
`GET api/ibge/bairros/v1/:municipio,estado`

## Notas

- Os bairros retornados pelo endpoint dependem de uma [planilha](https://docs.google.com/spreadsheets/d/1RKhFWbcdz9i1Y_jDDIpLXErdOL0IKIWg4jlhvvHpJTk/edit#gid=0), que me proponho manter. Qualquer um pode editá-la e iniciarei um movimento aqui na UFSCar para que muitos bairros sejam preenchidos de diversas cidades. **Essa foi a solução que encontrei para não depender de APIs externas, que costumam ser pagas e/ou com limite de requisições**;
- O parâmetro do endpoint deve ser 'São-Carlos,SP', por exemplo. Espaços devem ser trocados por - e deve ser colocada vírgula entre a cidade e o estado (evitando consultar uma cidade de outro estado com o mesmo nome)'.

Exemplo de retorno para api/ibge/bairros/v1/São-José-dos-Campos,SP:
`{"bairros":["Urbanova","Centro","Jardim das Colinas","Aquarius","Jardim São Dimas"]}`

2023-12-02 01:12 UTC, LorhanSohaky requested changes
A ideia do BrasilAPI é mais atuar como proxy, ou seja, facilitamos o acesso a outras API + cache. Então o ideal é que essas informações sejam fornecidas por terceiros.

2023-12-02 01:12 UTC, LorhanSohaky commented on package.json
> +    "csvtojson": "^2.0.10",
no repositório já temos uma dependência para transformar csv para json. Sugiro dar uma olhada no papa parse

2024-10-22 02:37 UTC, bigcharl commented
achei essa bomba [sidra ibge](https://sidra.ibge.gov.br/territorio#/N102) porém não tem todos os bairros, onde eu moro por exemplo não ta aí mas dependendendo da aplicação pode ser suficiente, por sorte pra mim é!
da pra ajeitar o filtro do próprio site e fazer o scrape à gosto, isso n é informação que muda com muita frequência ent acho q 1x por ano seja suficiente kkk

2026-04-11 22:46 UTC, lucianopf commented
Olá @luccacb16, busca de bairros por município é uma feature interessante! Mas há problemas para resolver antes do merge.

**Problema principal: dados mantidos manualmente por colaborador individual**

A descrição diz que os bairros vêm de uma planilha que você se propõe a manter. Isso é problemático porque:
- Se você parar de manter, os dados ficam desatualizados ou incorretos
- A BrasilAPI precisa de fontes de dados que não dependam de uma pessoa específica para serem atualizados
- O IBGE não tem API pública oficial para bairros (o que é o verdadeiro problema aqui)

Infelizmente, sem uma fonte oficial e autossustentável, bairros por município não pode entrar na BrasilAPI no momento. O correto seria abrir uma issue de discussão na comunidade antes de implementar, para alinhar a fonte de dados.

**Outros problemas técnicos:**

**1. CSV lido do disco em cada requisição sem cache**

```js
const json = await csvToJson().fromFile(csvFilePath); // em toda requisição!
```

Isso é lento. Se o arquivo for incluído, deve ser importado como módulo (lido uma vez) ou o resultado cacheado.

**2. Não usa classes de erro do projeto**

```js
// ❌
return res.status(400).json({ mensagem: 'Formato inválido...' });

// ✅
throw new BadRequestError({ message: 'Formato inválido...' });
```

**3. Campo `mensagem` em português**

O padrão de erros da BrasilAPI usa `message` (inglês), não `mensagem`. Veja a classe `BadRequestError`.

**4. Parâmetro de URL incomum**

`/api/ibge/bairros/v1/São-José-dos-Campos,SP` — misturar cidade e estado com vírgula em um único parâmetro é confuso. O padrão do projeto usa parâmetros separados ou rotas aninhadas: `/api/ibge/bairros/v1/:estado/:municipio`.

2026-08-07 22:45 UTC, lucianopf commented
Olá! Este PR está parado há mais de 2 anos sem atividade do autor, com mudanças solicitadas na revisão que não foram aplicadas (ou base muito desatualizada). Estamos fechando para limpar a fila, mas **sinta-se à vontade para reabrir** quando quiser retomar — basta rebasear na main e ajustar conforme as solicitações de review. 🙏

Se a feature ainda for desejada, um PR novo com base atualizada tem muito mais chance de aprovação.

2026-08-07 22:45 UTC, closed without merging