feat: Identificação de localização a partir de um Plus Code
BrasilAPI/BrasilAPI pull request #554
Opened 2023-11-30 10:24 UTC by lucaspquadros

## Issue Relacionada

Closes #418 - Lugares sem CEP

## Descrição

A partir da biblioteca "open-location-code", foi implementado uma solução que recebe como Input um Plus Code (simples código alfanumérico baseado em latitude e longitude para identificação exata de um local) e retorna, através da API Open Street Map, a rua, o bairro, a cidade, o país e o estado do local.
Para testar, basta obter um Plus Code do local desejado pelo Google Maps e verificar a saída gerada pela aplicação.

Exemplo de entrada:
![entrada](https://github.com/BrasilAPI/BrasilAPI/assets/139825984/1f7a8d8f-3d0e-4bd9-8a0e-bb28a2f2a5d2)

Exemplo de saída:
![saida](https://github.com/BrasilAPI/BrasilAPI/assets/139825984/f95baa1f-c8a1-40ed-8901-ed106b70463d)

Base do funcionamento:
![funcionamento](https://github.com/BrasilAPI/BrasilAPI/assets/139825984/319f6c2b-9c77-4a3a-8cee-e6c61f784e52)

2023-12-02 00:37 UTC, LorhanSohaky commented
@mau0414 , pode resolver os conflitos pff?

2023-12-02 01:01 UTC, LorhanSohaky requested changes
Muito obrigado pela contribuição. Além desses detalhes, precisamos que você adicione casos de testes

2023-12-02 13:54 UTC, RodriAndreotti requested changes
Obrigado pela contribuição!

O PR ficou muito legal, só deixei alguns comentários complementando os do @LorhanSohaky.

2023-12-02 13:54 UTC, RodriAndreotti commented on pages/api/pluscode/[pluscode].js
> +export default app().get(action);
Conhecendo a api do open street maps de experiências passadas, e sabendo que essa informação não deve mudar com muita frequência eu recomendaria usar um cache mais agressivo que o padrão do projeto, assim não corremos o risco de blocks.. .rs
```suggestion
export default app( { cache: 600000 } ).get(action);
```

2026-04-11 22:48 UTC, lucianopf commented
Olá @lucaspquadros, Plus Codes é uma ideia interessante! Mas há problemas antes do merge.

**Bloqueadores:**

**1. Nominatim (OpenStreetMap) requer User-Agent e tem limite de taxa**

```js
url: `https://nominatim.openstreetmap.org/reverse?...`
```

Os [Termos de Uso do Nominatim](https://operations.osmfoundation.org/policies/nominatim/) exigem:
- Máximo de 1 requisição por segundo
- Header `User-Agent` identificando a aplicação
- Proibição de uso massivo

Em produção, sem cache adequado e sem `User-Agent`, isso viola os ToS e pode resultar em bloqueio. Adicione pelo menos o header `User-Agent`.

**2. URL sem versão**

```
/api/pluscode/[pluscode].js  ❌
/api/pluscode/v1/[pluscode].js  ✅
```

Todos os endpoints da BrasilAPI usam versionamento na URL.

**3. Todos os erros são tratados como `InternalError`**

```js
throw new InternalError({ status: 400, message: 'Plus Code inválido' });
```

`InternalError` é status 500. Um Plus Code inválido deveria lançar `BadRequestError` (400). Além disso, o campo `status: 400` não é aceito pelo construtor de `InternalError` — o status HTTP é definido pela classe.

**4. Ausência de testes**

Nenhum arquivo de teste foi incluído no PR.

**Outros:**
- `import app from '@/app';;` — duplo ponto-e-vírgula
- `response.json(data)` sem `return` no handler — adicione `return response.status(200).json(data)`
- Modificação em `pages/sitemap.xml/index.jsx` não parece relacionada ao Plus Code

2026-08-07 22:45 UTC, lucianopf commented
Olá! Este PR está parado há mais de 2 anos sem atividade do autor, com mudanças solicitadas na revisão que não foram aplicadas (ou base muito desatualizada). Estamos fechando para limpar a fila, mas **sinta-se à vontade para reabrir** quando quiser retomar — basta rebasear na main e ajustar conforme as solicitações de review. 🙏

Se a feature ainda for desejada, um PR novo com base atualizada tem muito mais chance de aprovação.

2026-08-07 22:46 UTC, closed without merging