feat: add vlibras
BrasilAPI/BrasilAPI pull request #556
Opened 2023-11-30 11:02 UTC by MarlonHenq

Considerando que o repositório se compromete em ser uma plataforma que converte o Brasil em API, é fundamental que ele inclua as duas línguas oficiais brasileiras.
Assim proponho neste Pull Request a adição da tecnologia VLibras, a qual converte o site da API e Documentação para Linguagem brasileira de sinais.

2023-12-01 01:23 UTC, LorhanSohaky requested changes
Muito massa! Só é preciso atualizar o package-lock para que o PR fique correto

2023-12-02 00:37 UTC, LorhanSohaky commented
@MarlonHenq , pode resolver os conflitos pff?

2023-12-02 00:44 UTC, LorhanSohaky requested changes

2023-12-02 00:44 UTC, LorhanSohaky commented on package.json
> +    "@djpfs/react-vlibras": "^2.0.2",
Esqueci de comentar, mas neste projeto usamos a versão pinada das dependências. Então será preciso mudar aqui e refazer o `npm install`

```suggestion
    "@djpfs/react-vlibras": "2.0.2",
```

2024-01-04 17:03 UTC, Muurilo approved these changes

2024-01-04 18:34 UTC, LorhanSohaky approved these changes

2024-02-25 13:10 UTC, closed without merging

2024-02-25 15:58 UTC, MarlonHenq commented
?

2024-02-25 21:44 UTC, RodriAndreotti commented
> ?

Foi mergeado em outro PR (que foi criado só para resolver um conflito), por isso o Murilo fechou este.
Valeu pela contribuição mestre!

2024-02-25 22:09 UTC, MarlonHenq commented
vlw