Feature de novo Endpoint para verificação de área de risco dos Correios por CEP
BrasilAPI/BrasilAPI pull request #557
Opened 2023-11-30 11:56 UTC by SenaJesus

**Descrição da Nova Feature "Verificar Área de Risco dos Correios por CEP"**

Implementamos uma nova funcionalidade no BrasilAPI que permite verificar se um CEP está localizado em uma área de risco, conforme classificado pelos Correios do Brasil. Esta feature é essencial para informar consumidores e empresas sobre restrições de entrega em determinados CEPs, reduzindo a incidência de surpresas desagradáveis e contribuindo para um planejamento mais eficaz de envios e recebimentos de encomendas.

**Motivação**

A motivação para o desenvolvimento desta funcionalidade surgiu da necessidade de mitigar os impactos da segregação social exacerbada pela falta de informação sobre áreas com restrição de entrega. Consumidores, especialmente em regiões periféricas, frequentemente enfrentam desafios ao receber encomendas devido a essas restrições, um problema pouco divulgado pelas empresas de distribuição. A transparência na verificação de CEPs em áreas de risco é também uma exigência do Código de Defesa do Consumidor brasileiro, reforçando a relevância desta funcionalidade.

**Detalhes Técnicos**

- Análise de Arquitetura: A funcionalidade foi integrada respeitando a arquitetura existente dos endpoints do BrasilAPI, mantendo a coesão e a qualidade do código-fonte.
- Engenharia Reversa e Parsing de Dados: Realizamos engenharia reversa nas requisições HTTP do site dos Correios, extraindo informações de HTML com técnicas de parsing usando JSDOM.
- Tratamento de Erros e Exceções: Implementamos um sistema robusto para o manejo de erros, utilizando expressões regulares e constantes para mensagens de erro.
-  Requisições HTTP com Axios: Asseguramos requisições HTTP eficientes e corretas para a coleta dos dados necessários.
-  Otimizações de Código: Fizemos uma análise de complexidade do código, buscando otimizações por meio de modularização e reutilização de funções eficientes do JavaScript.
- Documentação: A documentação segue as diretrizes do OpenAPI 3.0, detalhando esquemas de requisição, status de resposta, e parâmetros.
- Testes Unitários: Foram realizados testes unitários abrangentes para garantir a confiabilidade e integridade da funcionalidade.

**Benefícios para Empresas e Consumidores**

Empresas de e-commerce, serviços de entrega, e consumidores se beneficiam diretamente desta funcionalidade. E-commerce, como a Magazine Luiza, poderá informar seus clientes antecipadamente sobre possíveis restrições de entrega em seus CEPs, aumentando a transparência e a satisfação do cliente. Serviços de entrega poderão planejar rotas mais eficientes, considerando as restrições existentes. Consumidores, por sua vez, estarão mais informados e poderão se planejar melhor para o recebimento de seus produtos.

**Solicitação de Integração**

Solicitamos a revisão desta implementação pela comunidade e a subsequente integração ao projeto principal do BrasilAPI, acreditando que esta funcionalidade agregará grande valor ao projeto e à sociedade brasileira.

2023-12-02 20:17 UTC, LorhanSohaky requested changes
Muito obrigado pela contribuição! Deixei alguns pedidos de melhoras

2023-12-02 20:17 UTC, LorhanSohaky commented on services/correios-restricao/index.js
> +    const response = await axios.post(correiosApi, params);
Creio que assim seja mais simples e não necessite da função de build
```suggestion
    const response = await axios.post(correiosApi, {
      params: {
        servico,
        cepOrigem,
        cepDestino
      }
    }, {
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded'
    }
});
```

2023-12-02 20:17 UTC, LorhanSohaky commented on services/correios-restricao/index.js
> +axios.defaults.headers.post['Content-Type'] = 'application/x-www-form-urlencoded';
Com o que comentei abaixo esse default não será necessário. E não sei se pode afetar as outras rotas da API

2023-12-02 20:17 UTC, LorhanSohaky commented on tests/correiosres.test.js
> +});
nos nossos testes deixamos acontecer a requisição de fato para que acompanhamos se ainda está funcionando e etc.

E as nossas requisições são feitas da api rodando localmente (olhar os testes das outras rotas)

2023-12-02 20:17 UTC, LorhanSohaky commented on pages/api/correiosres/v1/index.js
> +        } else if (err instanceof NotFoundError) {
```suggestion
        } else if (err instanceof BaseError) {
```

2023-12-02 20:17 UTC, LorhanSohaky commented on pages/docs/doc/correiosres.json
> +                            "example": 78735679
Não tenho certeza, mas talvez tenha que ser do tipo string, já que existem CEPs que iniciam com zero

2023-12-02 20:17 UTC, LorhanSohaky commented on pages/docs/doc/correiosres.json
> +                            "example": 33115090
Mesmo ponto aqui

2023-12-02 20:17 UTC, LorhanSohaky commented on pages/docs/doc/correiosres.json
> +                    "name": "CEP_NOT_FOUND"
Se alterar o name, também será preciso mexer aqui

2023-12-02 20:17 UTC, LorhanSohaky commented on pages/docs/doc/correiosres.json
> +                    "isDeliverable": {
```suggestion
                    "is_deliverable": {
```

2023-12-02 20:17 UTC, LorhanSohaky commented on pages/docs/doc/correiosres.json
> +                    "isDeliverable": false
```suggestion
                    "is_deliverable": false
```

2023-12-02 20:17 UTC, LorhanSohaky commented on pages/docs/doc/correiosres.json
> +                "required": ["response", "isDeliverable"],
```suggestion
                "required": ["response", "is_deliverable"],
```

2023-12-02 20:17 UTC, LorhanSohaky commented on pages/api/correiosres/v1/index.js
Sugeriria de deixar aqui o mais simples possível e deixar a maioria das funções e constantes dentro do service

2023-12-02 20:17 UTC, LorhanSohaky commented on pages/api/correiosres/v1/index.js
> +        const {cepOrigem, cepDestino, servico} = request.query;
Acho interessante adotar o padrão snake_case para as variáveis que vêm do cliente e vão para o cliente

```suggestion
        const {cep_origem: cepOrigem, cep_destino: cepDestino, servico} = request.query;
```

2023-12-02 20:17 UTC, LorhanSohaky commented on pages/api/correiosres/v1/index.js
> +            response.status(200).json('{"response": "CEP sem restricao de entrega", "isDeliverable": true}');
```suggestion
            response.status(200).json({message: "CEP em zona restrita", is_deliverable: false});
            return;
        }

        if (positiveDiv) {
            response.status(200).json({message:"CEP sem restricao de entrega", is_deliverable": true});
```

2023-12-03 00:08 UTC, lucianopf commented on pages/api/correiosres/v1/index.js
Será que vale criar uma rota mãe chamada `/correios` e colocar dentro dela `/correios/cep` e `/correios/risco`?

Obviamente ainda mantendo um symlink do cep atual pra não deixar de funionar :thinking:

2023-12-03 00:10 UTC, lucianopf commented on pages/api/correiosres/v1/index.js
> +        regex: /alert\(\'CEP de origem n.*o encontrado na base de dados dos Correios \(-1\).\'\)/,
Por qual motivo estamos lidando com matchers na acentuação? A ideia é garantir que mesmo sem saber o encoding a gnt lidar corretamente?

2023-12-03 00:13 UTC, lucianopf commented on pages/api/correiosres/v1/index.js
> +}
Dado que o esperado é que na maioria das vezes não hajam alertas será que não é melhor primeiro validar se existe um alerta e caso exista a gnt iterar sobre os possíveis alertas pra mapear corretamente o erro? (pensando especialmente que fazer validações com Regex pode ser bem exaustivo)

2023-12-03 00:14 UTC, lucianopf commented on pages/api/correiosres/v1/index.js
> +function validarCEP(cepOrigem, cepDestino) {
Seria interessante manter o nome das funções em inglês como o restante da codebase :pray:

2023-12-03 00:49 UTC, lucianopf commented on pages/api/correiosres/v1/index.js
> +        if (!(servico in SERVICOS)) {
Pq fazer dessa forma e não da seguinte forma?

```suggestion
        if (!SERVICOS[servico]) {
```

2023-12-03 00:50 UTC, lucianopf commented on pages/api/correiosres/v1/index.js
> +        validarCEP(cepOrigem, cepDestino);
Será que aqui um nome melhor pra função não seria `validateParams` e nessa função validar os 3 parametros? :eyes:

2023-12-03 00:57 UTC, lucianopf commented on pages/api/correiosres/v1/index.js
> +        }
Partindo do comentário https://github.com/BrasilAPI/BrasilAPI/pull/557/files#r1412902104

A gnt poderia reescrever esse trecho pra algo tipo

```suggestion
        const foundAlert = getAlert(correiosData);

        if (foundAlert) {
            throw new NotFoundError({
                message: foundAlert,
                type: 'cep_error',
                name: 'CEP_NOT_FOUND',
            });
        }
```

2023-12-03 01:05 UTC, lucianopf commented on pages/api/correiosres/v1/index.js
> +        const { errorDiv, positiveDiv } = parseCorreiosHtml(correiosData);
Na prática mesmo o que a gnt ta querendo aqui é baseado no html definir se a entrega é possível ou não, correto?

Será que não seria melhor essa função na vdd retornar um boolean e baseado nisso a gnt define a resposta?

2026-04-11 22:48 UTC, lucianopf commented
Olá @SenaJesus, a proposta de verificar áreas de risco dos Correios por CEP é socialmente relevante! Mas há problemas fundamentais antes do merge.

**Bloqueador principal: web scraping do site dos Correios**

A própria descrição confirma: _"Realizamos engenharia reversa nas requisições HTTP do site dos Correios, extraindo informações de HTML com técnicas de parsing usando JSDOM"_.

Web scraping não é aceito na BrasilAPI:
- O Correios pode alterar o HTML/formulário a qualquer momento, quebrando o endpoint
- Parsing de HTML de sites é frágil e não é uma fonte de dados oficial
- O Correios pode bloquear requisições automatizadas

Se os Correios tiverem uma API pública e oficial para restrições de entrega, use-a. Caso contrário, esta funcionalidade não pode entrar no projeto no momento.

**Outros problemas técnicos:**

1. **Mistura CommonJS e ESM**: O service usa `const axios = require('axios')` e `exports.requestHtmlCorreios = ...` enquanto o handler usa `import`. Escolha um padrão (o projeto usa ESM).

2. **`require('jsdom')` no handler**: Mistura de `require()` com `import`.

3. **`axios.defaults.headers.post` modificado globalmente** no service — afeta todos os requests axios do projeto, não só os seus.

4. **`.json()` recebendo uma string em vez de objeto**:
   ```js
   // ❌ — double-encoded: {"response": "CEP em zona restrita"...} vira uma string no JSON
   response.status(200).json('{\"response\": \"CEP em zona restrita\", ...}');
   
   // ✅
   response.status(200).json({ response: 'CEP em zona restrita', isDeliverable: false });
   ```

5. **Serviço inválido retorna `InternalError` (500)** — deveria ser `BadRequestError` (400).

6. **Mudança em `app.js`** (só whitespace) não deve estar neste PR.

2026-08-07 22:46 UTC, lucianopf commented
Olá! Este PR está parado há mais de 2 anos sem atividade do autor, com mudanças solicitadas na revisão que não foram aplicadas (ou base muito desatualizada). Estamos fechando para limpar a fila, mas **sinta-se à vontade para reabrir** quando quiser retomar — basta rebasear na main e ajustar conforme as solicitações de review. 🙏

Se a feature ainda for desejada, um PR novo com base atualizada tem muito mais chance de aprovação.

2026-08-07 22:46 UTC, closed without merging