Implementação do Endpoint de Feriados V2 por Estado e Município no BrasilAPI
BrasilAPI/BrasilAPI pull request #558
Opened 2023-11-30 12:26 UTC by vitoriahilgert

**Descrição da Feature**

Nesta atualização do BrasilAPI, expandimos a funcionalidade do endpoint de feriados para incluir não apenas os feriados nacionais, mas também os específicos de cada estado e município brasileiro. Agora, o endpoint é capaz de fornecer informações precisas sobre feriados locais em qualquer ano solicitado.

**Motivação**

A motivação para esta atualização surgiu da necessidade de fornecer dados mais precisos e abrangentes sobre feriados no Brasil. Observamos que a versão anterior do endpoint de feriados era limitada, pois retornava apenas feriados nacionais, muitos dos quais não eram observados em todos os municípios. Além disso, a seleção de feriados de todo o Brasil resultava na exibição de feriados de uma capital aleatória, como São Paulo ou Rio de Janeiro, em vez de todos os feriados nacionais.

**Detalhes Técnicos**

- Ampliação do Endpoint de Feriados: O novo endpoint agora retorna informações de feriados nacionais, estaduais e municipais, com a capacidade de filtrar por ano.
- Precisão de Dados: Garantimos a precisão e a atualização dos dados, coletando informações de fontes oficiais e confiáveis.
- Documentação Conforme Padrões do Repositório: Elaboramos a documentação detalhada do novo endpoint, seguindo as regras e diretrizes estabelecidas no BrasilAPI.
- Testes Unitários: Realizamos testes unitários extensivos para assegurar a confiabilidade e a precisão dos dados retornados pelo novo endpoint.
- Pull Request: O PR foi criado com detalhes completos da implementação, documentação e resultados dos testes.

**Benefícios para Usuários e Desenvolvedores**

Esta atualização beneficiará diretamente desenvolvedores, empresas e usuários que necessitam de informações precisas sobre feriados em diferentes regiões do Brasil. Desenvolvedores poderão integrar facilmente esses dados em aplicativos e sistemas, enquanto empresas poderão planejar melhor suas operações considerando feriados locais. Para os usuários, essa funcionalidade traz a conveniência de acessar informações sobre feriados em suas localidades de maneira rápida e confiável.

**Solicitação de Integração**

Solicitamos a revisão e aceitação desta implementação pela comunidade do BrasilAPI, acreditando que ela adiciona valor significativo ao projeto, ampliando sua utilidade e precisão para todos os usuários.

2023-12-01 01:38 UTC, RodriAndreotti requested changes
A proposta do PR é bastante interessante, deixei algumas observações, se puder ver se fazem sentido para você ;-)

2023-12-01 01:38 UTC, RodriAndreotti commented on services/holidays-v2/index.js
Notei que houve uma mistura de variáveis com nomes em português e outras com nome em inglês.
Apesar de não ser um block, talvez fosse interessante manter uma padronização.

2023-12-01 01:38 UTC, RodriAndreotti commented on services/holidays-v2/index.js
> +    }
Será que não faria sentido ter essa camada de consulta a dados em um serviço externo?

Hoje já temos um service para dados do ibge (services/ibge/gov.js), talvez fosse interessante reaproveitar o que puder dele e somente criar novas funções dentro do mesmo arquivo, visando o princípio da responsabilidade única.

2023-12-01 01:38 UTC, RodriAndreotti commented on tests/feriados-v2.test.js
Pelo que vi do serviço usado parece que a url é sempre montada com o nome da cidade sem acentuação, seria interessante testar esse cenário tentando enviar uma cidade com o acento no nome, o que acha?

2023-12-01 15:06 UTC, fczuardi commented on services/holidays-v2/index.js
> +        const responseUF = await fetch(urlUF);
a lista de siglas de estados é algo que muda muito pouco, talvez não justifique pegar do ibge dinamicamente sempre, poderia estar estática no código, ou num lugar também estático que faça parte da build, para economizar um http get, (caro, sujeito a erros de rede, etc)

2023-12-02 23:46 UTC, lucianopf commented on pages/api/feriados/v2/index.js
> +    }
Será que isso é realmente necessário dado que caso não haja na query esses parametros eles serão falsy? :grimacing: 

Se a gnt só ignora isso e passa pro getHolidays lá a gnt só precisa validar se o valor contido no caminho existe e é truthy ^^

2023-12-02 23:48 UTC, lucianopf commented on services/holidays-v2/index.js
Gosto da sugestão de manter o código em ingles tbm! ^^

2026-04-11 22:45 UTC, lucianopf commented
Olá @vitoriahilgert, obrigado pela contribuição! A ideia de feriados por estado e município é muito útil, mas o PR tem problemas arquiteturais que impedem o merge.

**Bloqueador principal: web scraping de `feriados.com.br`**

```js
const url = `https://www.feriados.com.br/feriados-${city}-${uf}.php?ano=${year}`;
const response = await fetch(url);
const html = await response.text();
const dom = new JSDOM(html); // parseia HTML com jsdom
```

A BrasilAPI não pode depender de web scraping:
- Se o site mudar o HTML, o endpoint quebra imediatamente
- Não é uma fonte oficial ou pública de dados
- `jsdom` é uma dependência pesada não incluída no projeto

Para feriados estaduais, as opções são:
1. **Dados hardcoded** (como PR #552 faz) — simples e sem dependências externas, adequado para feriados fixos
2. **APIs públicas oficiais** — o IBGE e o governo federal não oferecem API de feriados municipais, então dados estáticos são a abordagem comum

**Outros problemas:**

- Mistura `require()` (CommonJS) com `import` (ESM) no mesmo arquivo: `const { JSDOM } = require('jsdom')`
- Usa `fetch()` nativo em vez de `axios` (padrão do projeto)
- Usa `var` em vez de `const`/`let`
- Usa `!=` em vez de `!==` (comparação não estrita)
- Testes usam CommonJS (`const axios = require('axios')`) e não importam Vitest

Recomendo examinar o PR #552 que implementa feriados estaduais com dados estáticos — é a abordagem correta para este tipo de dado.

2026-08-07 22:46 UTC, lucianopf commented
Olá! Este PR está parado há mais de 2 anos sem atividade do autor, com mudanças solicitadas na revisão que não foram aplicadas (ou base muito desatualizada). Estamos fechando para limpar a fila, mas **sinta-se à vontade para reabrir** quando quiser retomar — basta rebasear na main e ajustar conforme as solicitações de review. 🙏

Se a feature ainda for desejada, um PR novo com base atualizada tem muito mais chance de aprovação.

2026-08-07 22:46 UTC, closed without merging