Adiciona feriado nacional do dia da consciência negra a partir de 2024
BrasilAPI/BrasilAPI pull request #567
Opened 2023-12-28 14:14 UTC by joaovitors1g

**Descrição**

A partir de 2024 o dia da consciência negra será considerado feriado nacional, pensando nisso fiz a inclusão do feriado a partir de 2024 no endpoint holidays.

2024-01-04 18:22 UTC, LorhanSohaky commented
@joaovitors1g , você tem o link de onde isso saiu no diário oficial?

2024-01-04 18:59 UTC, joaovitors1g commented
> @joaovitors1g , você tem o link de onde isso saiu no diário oficial?

Claro, [Diário Oficial](https://www.gov.br/planalto/pt-br/acompanhe-o-planalto/noticias/2023/12/presidente-sanciona-lei-que-declara-o-dia-nacional-de-zumbi-e-da-consciencia-negra-feriado-em-todo-o-pais#:~:text=O%20presidente%20Luiz%20In%C3%A1cio%20Lula,sexta%2Dfeira%20(22).)

2024-01-04 19:00 UTC, joaovitors1g commented
> Muito bom! Para complementar seria interessante colocar uns testes buscando por feriados em 2023 e 2024 vendo se em um o feriado está incluso e no outro não

Obrigado pelo feedback! Adicionei os testes.

2024-01-04 21:09 UTC, RodriAndreotti requested changes

2024-01-04 21:09 UTC, RodriAndreotti commented on tests/feriados-v1.test.js
> +        getHolidays(2024, ['Dia da consciência negra'])
Aqui não deveria ser 2023?

2024-01-04 23:37 UTC, joaovitors1g commented on tests/feriados-v1.test.js
> +        getHolidays(2024, ['Dia da consciência negra'])
Como estou verificando se o array não contém, uso o `getHolidays` pra buscar os feriados de 2024 e filtro somente o "Dia da consciência negra", não consegui pensar em outra maneira de validar.

2024-01-05 00:48 UTC, RodriAndreotti commented on tests/feriados-v1.test.js
> +        getHolidays(2024, ['Dia da consciência negra'])
Pelo que entendi a lógica está correta, mas em 2024 o dia deveria estar presente, não?
Ou seja, em 2023 não teria o dia em questão e 2024 teria, me diga se eu estiver comendo bola... rs

2024-01-05 12:33 UTC, joaovitors1g commented on tests/feriados-v1.test.js
> +        getHolidays(2024, ['Dia da consciência negra'])
Pra validar eu fiz 2 testes, nesse caso de teste em específico estou buscando os feriados de 2023 na API e depois verifico se não contém o feriado "Dia da consciência negra", tem outro teste que verifica para esse caso de 2024 que você mencionou, onde eu busco os feriados de 2024 na API, filtro o "Dia da consciência negra" usando o `getHolidays` e uso o `expect.arrayContaining` para validar.

2024-02-24 01:20 UTC, LorhanSohaky approved these changes

2024-04-29 18:46 UTC, yuriaps commented
Poxa, eh uma pena que o PR ainda nao esteja aprovado, o codigo parece correto

2024-04-30 15:15 UTC, lucianopf approved these changes

2024-04-30 15:16 UTC, merged

2024-05-01 01:15 UTC, LorhanSohaky commented
@joaovitors1g , muito obrigado pela contribuição!! 

@yuriaps , já está em produção, obrigado pelo remember