Merge Feature/parties list
BrasilAPI/BrasilAPI pull request #632
Opened 2024-09-13 13:38 UTC by adeirjunior

merge feature: adiciona listagem de partidos

2024-09-26 02:40 UTC, LorhanSohaky commented
@adeirjunior , pode atualizar o PR resolvendo os conflitos?

2024-09-26 13:06 UTC, adeirjunior commented
> @adeirjunior , pode atualizar o PR resolvendo os conflitos?

Vou atualizar agora mesmo 👍

2024-09-29 01:18 UTC, adeirjunior commented
> @adeirjunior , pode atualizar o PR resolvendo os conflitos?

Esta feito 👍

2024-10-01 11:18 UTC, LorhanSohaky requested changes
Deixei alguns comentários de melhorias. Além disso, sugiro atualizar o sitemap e `pages/index.js` para incluir os partidos e ele ser indexado no google

2024-10-01 11:18 UTC, LorhanSohaky commented on pages/docs/doc/partidos.json
> +          "uri": "https://brasilapi.com.br/api/partidos/36844"
mudar a uri para incluir a versão

2024-10-01 11:18 UTC, LorhanSohaky commented on pages/docs/doc/partidos.json
> +      "ALL_PARTIDOS": {
o que acha de manter tudo em inglês ou tudo em português?

2024-10-01 11:18 UTC, LorhanSohaky commented on pages/docs/doc/partidos.json
> +      "DATA_PARTIDO": {
o que acha de manter tudo em inglês ou tudo em português?

2024-10-01 11:18 UTC, LorhanSohaky commented on pages/docs/doc/partidos.json
> +              "description": "Nome resumido do partido"
```suggestion
              "description": "Sigla do partido"
```

2024-10-01 11:18 UTC, LorhanSohaky commented on pages/docs/doc/partidos.json
> +              "description": "Identiicação do partido"
```suggestion
              "description": "Identificação do partido"
```

2024-10-01 11:18 UTC, LorhanSohaky commented on pages/docs/doc/partidos.json
> +            "description": "Identiicação do partido"
```suggestion
            "description": "Identificação do partido"
```

2024-10-01 11:18 UTC, LorhanSohaky commented on pages/docs/doc/partidos.json
> +              "description": "URI para acesso aos dados do partido"
Alterar texto

2024-10-01 11:18 UTC, LorhanSohaky commented on pages/docs/doc/partidos.json
> +              "description": "URI para acesso aos dados do partido"
Alterar texto

2024-10-01 11:18 UTC, LorhanSohaky commented on pages/docs/doc/partidos.json
> +              "description": "URI para acesso aos dados do partido"
Alterar texto

2024-10-01 11:18 UTC, LorhanSohaky commented on pages/docs/doc/partidos.json
> +              "description": "URI para acesso aos dados do partido"
Alterar texto

2024-10-01 11:18 UTC, LorhanSohaky commented on pages/docs/doc/partidos.json
> +              "description": "URI para acesso aos dados do partido"
Alterar texto

2024-10-01 11:18 UTC, LorhanSohaky commented on pages/docs/doc/partidos.json
> +              "description": "URI para acesso aos dados do partido"
Alterar texto

2024-10-01 11:18 UTC, LorhanSohaky commented on pages/docs/doc/partidos.json
> +                "description": "URI para acesso aos dados do partido"
Alterar texto

2024-10-01 11:18 UTC, LorhanSohaky commented on pages/docs/doc/partidos.json
> +                "description": "URI para acesso aos dados do partido"
Alterar texto

2024-10-01 11:18 UTC, LorhanSohaky commented on pages/docs/doc/partidos.json
> +                "description": "URI para acesso aos dados do partido"
Alterar texto

2024-10-01 11:18 UTC, LorhanSohaky commented on pages/docs/doc/partidos.json
> +                "description": "URI para acesso aos dados do partido"
Alterar texto

2024-10-01 11:18 UTC, LorhanSohaky commented on pages/docs/doc/partidos.json
> +                "description": "URI para acesso aos dados do partido"
Alterar texto

2024-10-01 11:18 UTC, LorhanSohaky commented on pages/docs/doc/partidos.json
> +                "description": "URI para acesso aos dados do partido"
Alterar texto

2024-10-01 11:18 UTC, LorhanSohaky commented on pages/docs/doc/partidos.json
> +                "description": "URI para acesso aos dados do partido"
Alterar texto

2024-10-01 11:18 UTC, LorhanSohaky commented on pages/docs/doc/partidos.json
> +            "description": "URI para acesso aos dados do partido"
Alterar texto

2024-10-01 11:18 UTC, LorhanSohaky commented on pages/docs/doc/partidos.json
> +            "description": "URI para acesso aos dados do partido"
Alterar texto

2024-10-01 11:18 UTC, LorhanSohaky commented on pages/docs/doc/partidos.json
> +            "description": "URI para acesso aos dados do partido"
Alterar texto

2024-10-01 11:18 UTC, LorhanSohaky commented on pages/docs/doc/partidos.json
> +            "description": "URI para acesso aos dados do partido"
Alterar texto

2024-10-01 11:18 UTC, LorhanSohaky commented on pages/docs/doc/partidos.json
> +            "idLegislatura": {
```suggestion
            "id_legislatura": {
```

2024-10-01 11:18 UTC, LorhanSohaky commented on pages/docs/doc/partidos.json
> +            "totalPosse": {
```suggestion
            "total_posse": {
```

2024-10-01 11:18 UTC, LorhanSohaky commented on pages/docs/doc/partidos.json
> +            "totalMembros": {
```suggestion
            "total_membros": {
```

2024-10-01 11:18 UTC, LorhanSohaky commented on pages/docs/doc/partidos.json
> +            "uriMembros": {
```suggestion
            "uri_membros": {
```

2024-10-01 11:18 UTC, LorhanSohaky commented on pages/docs/doc/partidos.json
> +              "siglaPartido": {
```suggestion
              "sigla_partido": {
```

2024-10-01 11:18 UTC, LorhanSohaky commented on pages/docs/doc/partidos.json
> +              "uriPartido": {
```suggestion
              "uri_partido": {
```

2024-10-01 11:18 UTC, LorhanSohaky commented on pages/docs/doc/partidos.json
> +              "idLegislatura": {
```suggestion
              "id_legislatura": {
```

2024-10-01 11:18 UTC, LorhanSohaky commented on pages/docs/doc/partidos.json
> +              "urlFoto": {
```suggestion
              "url_foto": {
```

2024-10-01 11:18 UTC, LorhanSohaky commented on pages/docs/doc/partidos.json
> +          "numeroEleitoral": {
```suggestion
          "numero_eleitoral": {
```

2024-10-01 11:18 UTC, LorhanSohaky commented on pages/docs/doc/partidos.json
> +          "urlLogo": {
```suggestion
          "url_logo": {
```

2024-10-01 11:18 UTC, LorhanSohaky commented on pages/docs/doc/partidos.json
> +          "urlWebSite": {
```suggestion
          "url_website": {
```

2024-10-01 11:18 UTC, LorhanSohaky commented on pages/docs/doc/partidos.json
> +          "urlFacebook": {
```suggestion
          "url_facebook": {
```

2024-10-01 11:18 UTC, LorhanSohaky commented on pages/docs/doc/partidos.json
> +          "urlFacebook": "",
Ajustar chaves do json conforme sugerido, pois optamos por padronizar em snake case

2024-10-01 11:18 UTC, LorhanSohaky commented on pages/docs/doc/partidos.json
> +          "uri": "https://brasilapi.com.br/api/partidos/37901"
Mudar url para incluir versão

2024-10-01 11:18 UTC, LorhanSohaky commented on services/partidos/get.js
> +  const baseUrlCâmara = 'https://dadosabertos.camara.leg.br/api/v2/partidos/';
```suggestion
  const baseUrlCamara = 'https://dadosabertos.camara.leg.br/api/v2/partidos/';
```

2024-10-01 11:18 UTC, LorhanSohaky commented on services/partidos/get.js
> +  const baseUrlBrasilAPI = 'https://brasilapi.com.br/api/partidos/';
Ajustar para incluir número da versão

2024-10-01 11:18 UTC, LorhanSohaky commented on services/partidos/get.js
> +    return 'URL não corresponde ao formato esperado.';
Devemos gerar erro nessa situação?

2024-10-01 11:18 UTC, LorhanSohaky commented on services/partidos/get.js
> +        Accept: 'application/xml',
Você pode alterar para esperar receber um json, assim simplifica seu parser

2024-10-01 11:18 UTC, LorhanSohaky commented on services/partidos/get.js
> +  }
Deixar estourar o erro ou gerar um erro customizado

2024-10-01 11:18 UTC, LorhanSohaky commented on services/partidos/get.js
> +    }
Deixar estourar o erro ou gerar um erro customizado

2024-10-01 11:18 UTC, LorhanSohaky commented on services/partidos/get.js
> +        Accept: 'application/xml',
mudar para json e assim simplificar o parser

2024-10-01 11:18 UTC, LorhanSohaky commented on services/partidos/get.js
> +    const { data } = await axios.get(URL, {
Pelo que vi a API é paginada, então você precisa reproduzir isso ou fazer requisição para todas as páginas

2024-10-01 11:18 UTC, LorhanSohaky commented on services/partidos/get.js
> +    };
Ajustar nomes das chaves para snake case

2024-10-01 11:18 UTC, LorhanSohaky commented on services/partidos/get.js
> +  }
Deixar estourar o erro ou gerar um erro customizado

2024-10-01 11:18 UTC, LorhanSohaky commented on services/partidos/get.js
> +    }
Mesmo comentário sobre simplificar o parser utilizando o json

2024-11-01 21:51 UTC, closed without merging