feat: nova rota para listar veiculos por marca e tipo de veiculo
BrasilAPI/BrasilAPI pull request #645
Opened 2024-11-03 16:06 UTC by Eduard0803

nova rota para listar veiculos por marca e tipo de veiculo.

Resolvendo a issue #623

2024-11-04 03:29 UTC, LorhanSohaky requested changes
Muito obrigado pela sua contribuição. Deixei algumas sugestões de melhorias, fico no aguardo para fazer outra revisão

2024-11-04 03:29 UTC, LorhanSohaky commented on pages/docs/doc/fipe.json
> +                        "required": false,
Por ser parte do path me parece ser obrigatório
```suggestion
                        "required": true,
```

2024-11-04 03:29 UTC, LorhanSohaky commented on pages/docs/doc/fipe.json
> +                        "description": "Código da marca do veiculo.\n",
Talvez seja interessante dar uma dica de onde encontrar as marcas
```suggestion
                        "description": "Código da marca do veiculo. Para consultar as marcas acesse a rota `/fipe/marcas/v1/`",
```

2024-11-04 03:29 UTC, LorhanSohaky commented on services/cep/cep.js
Me parece que este arquivo não deveria ter sido alterado. Sugiro rodar `npm run fix` para corrigir code style

2024-11-04 03:29 UTC, LorhanSohaky commented on pages/api/fipe/veiculos/v1/[vehicleType].js
> +  const makerCode = request.query.codigoMarca;
Pelos meus testes este campo é obrigatório. Quando testei sem, tive erro 500

https://brasilapi-8g1gbo3to-brasilapi.vercel.app/api/fipe/veiculos/v1/carros?codigoMarca=2

2024-11-04 03:29 UTC, LorhanSohaky commented on pages/api/fipe/veiculos/v1/[vehicleType].js
> +  const makerCode = request.query.codigoMarca;
Além disso, por convenção, utilizamos snake case para as interfaces das apis
```suggestion
  const makerCode = request.query.codigo_marca;
```

2024-11-04 03:29 UTC, LorhanSohaky commented on pages/docs/doc/fipe.json
> +                        "name": "codigoMarca",
```suggestion
                        "name": "codigo_marca",
```

2024-11-04 03:29 UTC, LorhanSohaky commented on services/fipe/vehiclesByMakers.js
Creio que em todas as funções poderia receber a tabela de referência e, caso ela não seja passada, então utilizar a tabela mais recente. Dessa forma você estará permitindo a busca de dados de tabelas fipes do passado

2024-11-04 03:29 UTC, LorhanSohaky commented on pages/api/fipe/veiculos/v1/[vehicleType].js
Pelo que vi, me parece fazer sentido incluir o código da marca no path, dessa maneira as requisições serão cacheadas
``pages/api/fipe/veiculos/v1/[vehicleType]/[codigoMarca].js`

2024-11-04 17:42 UTC, Eduard0803 commented on pages/docs/doc/fipe.json
> +                        "required": false,
documentação atualizada.

2024-11-04 17:43 UTC, Eduard0803 commented on pages/docs/doc/fipe.json
> +                        "description": "Código da marca do veiculo.\n",
documentação atualizada.

2024-11-04 17:43 UTC, Eduard0803 commented on services/cep/cep.js
esse arquivo foi alterado justamente quando rodei o `npm run fix`

2024-11-04 17:44 UTC, Eduard0803 commented on pages/docs/doc/fipe.json
> +                        "name": "codigoMarca",
documentação atualizada.

2024-11-04 17:45 UTC, Eduard0803 commented on pages/api/fipe/veiculos/v1/[vehicleType].js
rota atualizada para receber o código da marca no path.

2024-11-04 17:46 UTC, Eduard0803 commented on pages/api/fipe/veiculos/v1/[vehicleType].js
> +  const makerCode = request.query.codigoMarca;
code style atualizado.

2024-11-04 17:47 UTC, Eduard0803 commented on pages/api/fipe/veiculos/v1/[vehicleType].js
> +  const makerCode = request.query.codigoMarca;
código da marca está sendo passado pelo path da rota.

2024-11-05 03:25 UTC, LorhanSohaky approved these changes

2024-11-05 14:30 UTC, RodriAndreotti approved these changes

2024-11-05 18:39 UTC, lucianopf commented on services/fipe/vehiclesByMakers.js
> +  const { data } = await axios.post(
Eita, o get lá na fonte é com POST 👀

2024-11-06 20:37 UTC, LorhanSohaky commented on services/fipe/vehiclesByMakers.js
> +  const { data } = await axios.post(
Sim, é post

2024-11-08 00:07 UTC, merged